/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImDrawListSplitter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImDrawListSplitter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImDrawListSplitter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImDrawListSplitter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_Current(int value) {
    CImGuiJNI.ImDrawListSplitter__Current_set(swigCPtr, this, value);
  }

  public int get_Current() {
    return CImGuiJNI.ImDrawListSplitter__Current_get(swigCPtr, this);
  }

  public void set_Count(int value) {
    CImGuiJNI.ImDrawListSplitter__Count_set(swigCPtr, this, value);
  }

  public int get_Count() {
    return CImGuiJNI.ImDrawListSplitter__Count_get(swigCPtr, this);
  }

  public void set_Channels(ImVector_ImDrawChannel value) {
    CImGuiJNI.ImDrawListSplitter__Channels_set(swigCPtr, this, ImVector_ImDrawChannel.getCPtr(value), value);
  }

  public ImVector_ImDrawChannel get_Channels() {
    long cPtr = CImGuiJNI.ImDrawListSplitter__Channels_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImDrawChannel(cPtr, false);
  }

  public ImDrawListSplitter() {
    this(CImGuiJNI.new_ImDrawListSplitter(), true);
  }

}
