/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImDrawList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImDrawList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImDrawList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImDrawList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCmdBuffer(ImVector_ImDrawCmd value) {
    CImGuiJNI.ImDrawList_CmdBuffer_set(swigCPtr, this, ImVector_ImDrawCmd.getCPtr(value), value);
  }

  public ImVector_ImDrawCmd getCmdBuffer() {
    long cPtr = CImGuiJNI.ImDrawList_CmdBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImDrawCmd(cPtr, false);
  }

  public void setIdxBuffer(ImVector_ImDrawIdx value) {
    CImGuiJNI.ImDrawList_IdxBuffer_set(swigCPtr, this, ImVector_ImDrawIdx.getCPtr(value), value);
  }

  public ImVector_ImDrawIdx getIdxBuffer() {
    long cPtr = CImGuiJNI.ImDrawList_IdxBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImDrawIdx(cPtr, false);
  }

  public void setVtxBuffer(ImVector_ImDrawVert value) {
    CImGuiJNI.ImDrawList_VtxBuffer_set(swigCPtr, this, ImVector_ImDrawVert.getCPtr(value), value);
  }

  public ImVector_ImDrawVert getVtxBuffer() {
    long cPtr = CImGuiJNI.ImDrawList_VtxBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImDrawVert(cPtr, false);
  }

  public void setFlags(int value) {
    CImGuiJNI.ImDrawList_Flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return CImGuiJNI.ImDrawList_Flags_get(swigCPtr, this);
  }

  public void set_Data(ImDrawListSharedData value) {
    CImGuiJNI.ImDrawList__Data_set(swigCPtr, this, ImDrawListSharedData.getCPtr(value), value);
  }

  public ImDrawListSharedData get_Data() {
    long cPtr = CImGuiJNI.ImDrawList__Data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawListSharedData(cPtr, false);
  }

  public void set_OwnerName(String value) {
    CImGuiJNI.ImDrawList__OwnerName_set(swigCPtr, this, value);
  }

  public String get_OwnerName() {
    return CImGuiJNI.ImDrawList__OwnerName_get(swigCPtr, this);
  }

  public void set_VtxCurrentOffset(long value) {
    CImGuiJNI.ImDrawList__VtxCurrentOffset_set(swigCPtr, this, value);
  }

  public long get_VtxCurrentOffset() {
    return CImGuiJNI.ImDrawList__VtxCurrentOffset_get(swigCPtr, this);
  }

  public void set_VtxCurrentIdx(long value) {
    CImGuiJNI.ImDrawList__VtxCurrentIdx_set(swigCPtr, this, value);
  }

  public long get_VtxCurrentIdx() {
    return CImGuiJNI.ImDrawList__VtxCurrentIdx_get(swigCPtr, this);
  }

  public void set_VtxWritePtr(ImDrawVert value) {
    CImGuiJNI.ImDrawList__VtxWritePtr_set(swigCPtr, this, ImDrawVert.getCPtr(value), value);
  }

  public ImDrawVert get_VtxWritePtr() {
    long cPtr = CImGuiJNI.ImDrawList__VtxWritePtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawVert(cPtr, false);
  }

  public void set_IdxWritePtr(SWIGTYPE_p_unsigned_short value) {
    CImGuiJNI.ImDrawList__IdxWritePtr_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short get_IdxWritePtr() {
    long cPtr = CImGuiJNI.ImDrawList__IdxWritePtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void set_ClipRectStack(ImVector_ImVec4 value) {
    CImGuiJNI.ImDrawList__ClipRectStack_set(swigCPtr, this, ImVector_ImVec4.getCPtr(value), value);
  }

  public ImVector_ImVec4 get_ClipRectStack() {
    long cPtr = CImGuiJNI.ImDrawList__ClipRectStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImVec4(cPtr, false);
  }

  public void set_TextureIdStack(ImVector_ImTextureID value) {
    CImGuiJNI.ImDrawList__TextureIdStack_set(swigCPtr, this, ImVector_ImTextureID.getCPtr(value), value);
  }

  public ImVector_ImTextureID get_TextureIdStack() {
    long cPtr = CImGuiJNI.ImDrawList__TextureIdStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImTextureID(cPtr, false);
  }

  public void set_Path(ImVector_ImVec2 value) {
    CImGuiJNI.ImDrawList__Path_set(swigCPtr, this, ImVector_ImVec2.getCPtr(value), value);
  }

  public ImVector_ImVec2 get_Path() {
    long cPtr = CImGuiJNI.ImDrawList__Path_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImVec2(cPtr, false);
  }

  public void set_Splitter(ImDrawListSplitter value) {
    CImGuiJNI.ImDrawList__Splitter_set(swigCPtr, this, ImDrawListSplitter.getCPtr(value), value);
  }

  public ImDrawListSplitter get_Splitter() {
    long cPtr = CImGuiJNI.ImDrawList__Splitter_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawListSplitter(cPtr, false);
  }

  public ImDrawList() {
    this(CImGuiJNI.new_ImDrawList(), true);
  }

}
