/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImDrawVert {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImDrawVert(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImDrawVert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImDrawVert(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPos(ImVec2 value) {
    CImGuiJNI.ImDrawVert_pos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getPos() {
    long cPtr = CImGuiJNI.ImDrawVert_pos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setUv(ImVec2 value) {
    CImGuiJNI.ImDrawVert_uv_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getUv() {
    long cPtr = CImGuiJNI.ImDrawVert_uv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setCol(long value) {
    CImGuiJNI.ImDrawVert_col_set(swigCPtr, this, value);
  }

  public long getCol() {
    return CImGuiJNI.ImDrawVert_col_get(swigCPtr, this);
  }

  public ImDrawVert() {
    this(CImGuiJNI.new_ImDrawVert(), true);
  }

}
