/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImDrawCornerFlags_ {
  public final static int ImDrawCornerFlags_None = 0;
  public final static int ImDrawCornerFlags_TopLeft = 1 << 0;
  public final static int ImDrawCornerFlags_TopRight = 1 << 1;
  public final static int ImDrawCornerFlags_BotLeft = 1 << 2;
  public final static int ImDrawCornerFlags_BotRight = 1 << 3;
  public final static int ImDrawCornerFlags_Top = ImDrawCornerFlags_TopLeft|ImDrawCornerFlags_TopRight;
  public final static int ImDrawCornerFlags_Bot = ImDrawCornerFlags_BotLeft|ImDrawCornerFlags_BotRight;
  public final static int ImDrawCornerFlags_Left = ImDrawCornerFlags_TopLeft|ImDrawCornerFlags_BotLeft;
  public final static int ImDrawCornerFlags_Right = ImDrawCornerFlags_TopRight|ImDrawCornerFlags_BotRight;
  public final static int ImDrawCornerFlags_All = 0xF;
}

