/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImDrawDataBuilder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImDrawDataBuilder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImDrawDataBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImDrawDataBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLayers(ImVector_ImDrawListPtr value) {
    CImGuiJNI.ImDrawDataBuilder_Layers_set(swigCPtr, this, ImVector_ImDrawListPtr.getCPtr(value), value);
  }

  public ImVector_ImDrawListPtr getLayers() {
    long cPtr = CImGuiJNI.ImDrawDataBuilder_Layers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImDrawListPtr(cPtr, false);
  }

  public ImDrawDataBuilder() {
    this(CImGuiJNI.new_ImDrawDataBuilder(), true);
  }

}
