/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImFontGlyphRangesBuilder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImFontGlyphRangesBuilder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImFontGlyphRangesBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImFontGlyphRangesBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUsedChars(ImVector_ImU32 value) {
    CImGuiJNI.ImFontGlyphRangesBuilder_UsedChars_set(swigCPtr, this, ImVector_ImU32.getCPtr(value), value);
  }

  public ImVector_ImU32 getUsedChars() {
    long cPtr = CImGuiJNI.ImFontGlyphRangesBuilder_UsedChars_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImU32(cPtr, false);
  }

  public ImFontGlyphRangesBuilder() {
    this(CImGuiJNI.new_ImFontGlyphRangesBuilder(), true);
  }

}
