/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImFont {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImFont(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImFont obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImFont(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIndexAdvanceX(ImVector_float value) {
    CImGuiJNI.ImFont_IndexAdvanceX_set(swigCPtr, this, ImVector_float.getCPtr(value), value);
  }

  public ImVector_float getIndexAdvanceX() {
    long cPtr = CImGuiJNI.ImFont_IndexAdvanceX_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_float(cPtr, false);
  }

  public void setFallbackAdvanceX(float value) {
    CImGuiJNI.ImFont_FallbackAdvanceX_set(swigCPtr, this, value);
  }

  public float getFallbackAdvanceX() {
    return CImGuiJNI.ImFont_FallbackAdvanceX_get(swigCPtr, this);
  }

  public void setFontSize(float value) {
    CImGuiJNI.ImFont_FontSize_set(swigCPtr, this, value);
  }

  public float getFontSize() {
    return CImGuiJNI.ImFont_FontSize_get(swigCPtr, this);
  }

  public void setIndexLookup(ImVector_ImWchar value) {
    CImGuiJNI.ImFont_IndexLookup_set(swigCPtr, this, ImVector_ImWchar.getCPtr(value), value);
  }

  public ImVector_ImWchar getIndexLookup() {
    long cPtr = CImGuiJNI.ImFont_IndexLookup_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImWchar(cPtr, false);
  }

  public void setGlyphs(ImVector_ImFontGlyph value) {
    CImGuiJNI.ImFont_Glyphs_set(swigCPtr, this, ImVector_ImFontGlyph.getCPtr(value), value);
  }

  public ImVector_ImFontGlyph getGlyphs() {
    long cPtr = CImGuiJNI.ImFont_Glyphs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImFontGlyph(cPtr, false);
  }

  public void setFallbackGlyph(ImFontGlyph value) {
    CImGuiJNI.ImFont_FallbackGlyph_set(swigCPtr, this, ImFontGlyph.getCPtr(value), value);
  }

  public ImFontGlyph getFallbackGlyph() {
    long cPtr = CImGuiJNI.ImFont_FallbackGlyph_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImFontGlyph(cPtr, false);
  }

  public void setDisplayOffset(ImVec2 value) {
    CImGuiJNI.ImFont_DisplayOffset_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getDisplayOffset() {
    long cPtr = CImGuiJNI.ImFont_DisplayOffset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setContainerAtlas(ImFontAtlas value) {
    CImGuiJNI.ImFont_ContainerAtlas_set(swigCPtr, this, ImFontAtlas.getCPtr(value), value);
  }

  public ImFontAtlas getContainerAtlas() {
    long cPtr = CImGuiJNI.ImFont_ContainerAtlas_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImFontAtlas(cPtr, false);
  }

  public void setConfigData(ImFontConfig value) {
    CImGuiJNI.ImFont_ConfigData_set(swigCPtr, this, ImFontConfig.getCPtr(value), value);
  }

  public ImFontConfig getConfigData() {
    long cPtr = CImGuiJNI.ImFont_ConfigData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImFontConfig(cPtr, false);
  }

  public void setConfigDataCount(short value) {
    CImGuiJNI.ImFont_ConfigDataCount_set(swigCPtr, this, value);
  }

  public short getConfigDataCount() {
    return CImGuiJNI.ImFont_ConfigDataCount_get(swigCPtr, this);
  }

  public void setFallbackChar(int value) {
    CImGuiJNI.ImFont_FallbackChar_set(swigCPtr, this, value);
  }

  public int getFallbackChar() {
    return CImGuiJNI.ImFont_FallbackChar_get(swigCPtr, this);
  }

  public void setEllipsisChar(int value) {
    CImGuiJNI.ImFont_EllipsisChar_set(swigCPtr, this, value);
  }

  public int getEllipsisChar() {
    return CImGuiJNI.ImFont_EllipsisChar_get(swigCPtr, this);
  }

  public void setDirtyLookupTables(boolean value) {
    CImGuiJNI.ImFont_DirtyLookupTables_set(swigCPtr, this, value);
  }

  public boolean getDirtyLookupTables() {
    return CImGuiJNI.ImFont_DirtyLookupTables_get(swigCPtr, this);
  }

  public void setScale(float value) {
    CImGuiJNI.ImFont_Scale_set(swigCPtr, this, value);
  }

  public float getScale() {
    return CImGuiJNI.ImFont_Scale_get(swigCPtr, this);
  }

  public void setAscent(float value) {
    CImGuiJNI.ImFont_Ascent_set(swigCPtr, this, value);
  }

  public float getAscent() {
    return CImGuiJNI.ImFont_Ascent_get(swigCPtr, this);
  }

  public void setDescent(float value) {
    CImGuiJNI.ImFont_Descent_set(swigCPtr, this, value);
  }

  public float getDescent() {
    return CImGuiJNI.ImFont_Descent_get(swigCPtr, this);
  }

  public void setMetricsTotalSurface(int value) {
    CImGuiJNI.ImFont_MetricsTotalSurface_set(swigCPtr, this, value);
  }

  public int getMetricsTotalSurface() {
    return CImGuiJNI.ImFont_MetricsTotalSurface_get(swigCPtr, this);
  }

  public ImFont() {
    this(CImGuiJNI.new_ImFont(), true);
  }

}
