/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImFontAtlas {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImFontAtlas(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImFontAtlas obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImFontAtlas(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLocked(boolean value) {
    CImGuiJNI.ImFontAtlas_Locked_set(swigCPtr, this, value);
  }

  public boolean getLocked() {
    return CImGuiJNI.ImFontAtlas_Locked_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    CImGuiJNI.ImFontAtlas_Flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return CImGuiJNI.ImFontAtlas_Flags_get(swigCPtr, this);
  }

  public void setTexID(SWIGTYPE_p_void value) {
    CImGuiJNI.ImFontAtlas_TexID_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getTexID() {
    long cPtr = CImGuiJNI.ImFontAtlas_TexID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setTexDesiredWidth(int value) {
    CImGuiJNI.ImFontAtlas_TexDesiredWidth_set(swigCPtr, this, value);
  }

  public int getTexDesiredWidth() {
    return CImGuiJNI.ImFontAtlas_TexDesiredWidth_get(swigCPtr, this);
  }

  public void setTexGlyphPadding(int value) {
    CImGuiJNI.ImFontAtlas_TexGlyphPadding_set(swigCPtr, this, value);
  }

  public int getTexGlyphPadding() {
    return CImGuiJNI.ImFontAtlas_TexGlyphPadding_get(swigCPtr, this);
  }

  public void setTexPixelsAlpha8(SWIGTYPE_p_unsigned_char value) {
    CImGuiJNI.ImFontAtlas_TexPixelsAlpha8_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getTexPixelsAlpha8() {
    long cPtr = CImGuiJNI.ImFontAtlas_TexPixelsAlpha8_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setTexPixelsRGBA32(SWIGTYPE_p_unsigned_int value) {
    CImGuiJNI.ImFontAtlas_TexPixelsRGBA32_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getTexPixelsRGBA32() {
    long cPtr = CImGuiJNI.ImFontAtlas_TexPixelsRGBA32_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setTexWidth(int value) {
    CImGuiJNI.ImFontAtlas_TexWidth_set(swigCPtr, this, value);
  }

  public int getTexWidth() {
    return CImGuiJNI.ImFontAtlas_TexWidth_get(swigCPtr, this);
  }

  public void setTexHeight(int value) {
    CImGuiJNI.ImFontAtlas_TexHeight_set(swigCPtr, this, value);
  }

  public int getTexHeight() {
    return CImGuiJNI.ImFontAtlas_TexHeight_get(swigCPtr, this);
  }

  public void setTexUvScale(ImVec2 value) {
    CImGuiJNI.ImFontAtlas_TexUvScale_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getTexUvScale() {
    long cPtr = CImGuiJNI.ImFontAtlas_TexUvScale_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setTexUvWhitePixel(ImVec2 value) {
    CImGuiJNI.ImFontAtlas_TexUvWhitePixel_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getTexUvWhitePixel() {
    long cPtr = CImGuiJNI.ImFontAtlas_TexUvWhitePixel_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setFonts(ImVector_ImFontPtr value) {
    CImGuiJNI.ImFontAtlas_Fonts_set(swigCPtr, this, ImVector_ImFontPtr.getCPtr(value), value);
  }

  public ImVector_ImFontPtr getFonts() {
    long cPtr = CImGuiJNI.ImFontAtlas_Fonts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImFontPtr(cPtr, false);
  }

  public void setCustomRects(ImVector_ImFontAtlasCustomRect value) {
    CImGuiJNI.ImFontAtlas_CustomRects_set(swigCPtr, this, ImVector_ImFontAtlasCustomRect.getCPtr(value), value);
  }

  public ImVector_ImFontAtlasCustomRect getCustomRects() {
    long cPtr = CImGuiJNI.ImFontAtlas_CustomRects_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImFontAtlasCustomRect(cPtr, false);
  }

  public void setConfigData(ImVector_ImFontConfig value) {
    CImGuiJNI.ImFontAtlas_ConfigData_set(swigCPtr, this, ImVector_ImFontConfig.getCPtr(value), value);
  }

  public ImVector_ImFontConfig getConfigData() {
    long cPtr = CImGuiJNI.ImFontAtlas_ConfigData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImFontConfig(cPtr, false);
  }

  public void setCustomRectIds(SWIGTYPE_p_int value) {
    CImGuiJNI.ImFontAtlas_CustomRectIds_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getCustomRectIds() {
    long cPtr = CImGuiJNI.ImFontAtlas_CustomRectIds_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ImFontAtlas() {
    this(CImGuiJNI.new_ImFontAtlas(), true);
  }

}
