/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImFontAtlasCustomRect {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImFontAtlasCustomRect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImFontAtlasCustomRect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImFontAtlasCustomRect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setID(long value) {
    CImGuiJNI.ImFontAtlasCustomRect_ID_set(swigCPtr, this, value);
  }

  public long getID() {
    return CImGuiJNI.ImFontAtlasCustomRect_ID_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    CImGuiJNI.ImFontAtlasCustomRect_Width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return CImGuiJNI.ImFontAtlasCustomRect_Width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    CImGuiJNI.ImFontAtlasCustomRect_Height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return CImGuiJNI.ImFontAtlasCustomRect_Height_get(swigCPtr, this);
  }

  public void setX(int value) {
    CImGuiJNI.ImFontAtlasCustomRect_X_set(swigCPtr, this, value);
  }

  public int getX() {
    return CImGuiJNI.ImFontAtlasCustomRect_X_get(swigCPtr, this);
  }

  public void setY(int value) {
    CImGuiJNI.ImFontAtlasCustomRect_Y_set(swigCPtr, this, value);
  }

  public int getY() {
    return CImGuiJNI.ImFontAtlasCustomRect_Y_get(swigCPtr, this);
  }

  public void setGlyphAdvanceX(float value) {
    CImGuiJNI.ImFontAtlasCustomRect_GlyphAdvanceX_set(swigCPtr, this, value);
  }

  public float getGlyphAdvanceX() {
    return CImGuiJNI.ImFontAtlasCustomRect_GlyphAdvanceX_get(swigCPtr, this);
  }

  public void setGlyphOffset(ImVec2 value) {
    CImGuiJNI.ImFontAtlasCustomRect_GlyphOffset_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getGlyphOffset() {
    long cPtr = CImGuiJNI.ImFontAtlasCustomRect_GlyphOffset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setFont(ImFont value) {
    CImGuiJNI.ImFontAtlasCustomRect_Font_set(swigCPtr, this, ImFont.getCPtr(value), value);
  }

  public ImFont getFont() {
    long cPtr = CImGuiJNI.ImFontAtlasCustomRect_Font_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImFont(cPtr, false);
  }

  public ImFontAtlasCustomRect() {
    this(CImGuiJNI.new_ImFontAtlasCustomRect(), true);
  }

}
