/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImFontConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImFontConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImFontConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImFontConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFontData(SWIGTYPE_p_void value) {
    CImGuiJNI.ImFontConfig_FontData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getFontData() {
    long cPtr = CImGuiJNI.ImFontConfig_FontData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setFontDataSize(int value) {
    CImGuiJNI.ImFontConfig_FontDataSize_set(swigCPtr, this, value);
  }

  public int getFontDataSize() {
    return CImGuiJNI.ImFontConfig_FontDataSize_get(swigCPtr, this);
  }

  public void setFontDataOwnedByAtlas(boolean value) {
    CImGuiJNI.ImFontConfig_FontDataOwnedByAtlas_set(swigCPtr, this, value);
  }

  public boolean getFontDataOwnedByAtlas() {
    return CImGuiJNI.ImFontConfig_FontDataOwnedByAtlas_get(swigCPtr, this);
  }

  public void setFontNo(int value) {
    CImGuiJNI.ImFontConfig_FontNo_set(swigCPtr, this, value);
  }

  public int getFontNo() {
    return CImGuiJNI.ImFontConfig_FontNo_get(swigCPtr, this);
  }

  public void setSizePixels(float value) {
    CImGuiJNI.ImFontConfig_SizePixels_set(swigCPtr, this, value);
  }

  public float getSizePixels() {
    return CImGuiJNI.ImFontConfig_SizePixels_get(swigCPtr, this);
  }

  public void setOversampleH(int value) {
    CImGuiJNI.ImFontConfig_OversampleH_set(swigCPtr, this, value);
  }

  public int getOversampleH() {
    return CImGuiJNI.ImFontConfig_OversampleH_get(swigCPtr, this);
  }

  public void setOversampleV(int value) {
    CImGuiJNI.ImFontConfig_OversampleV_set(swigCPtr, this, value);
  }

  public int getOversampleV() {
    return CImGuiJNI.ImFontConfig_OversampleV_get(swigCPtr, this);
  }

  public void setPixelSnapH(boolean value) {
    CImGuiJNI.ImFontConfig_PixelSnapH_set(swigCPtr, this, value);
  }

  public boolean getPixelSnapH() {
    return CImGuiJNI.ImFontConfig_PixelSnapH_get(swigCPtr, this);
  }

  public void setGlyphExtraSpacing(ImVec2 value) {
    CImGuiJNI.ImFontConfig_GlyphExtraSpacing_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getGlyphExtraSpacing() {
    long cPtr = CImGuiJNI.ImFontConfig_GlyphExtraSpacing_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setGlyphOffset(ImVec2 value) {
    CImGuiJNI.ImFontConfig_GlyphOffset_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getGlyphOffset() {
    long cPtr = CImGuiJNI.ImFontConfig_GlyphOffset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setGlyphRanges(SWIGTYPE_p_unsigned_short value) {
    CImGuiJNI.ImFontConfig_GlyphRanges_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getGlyphRanges() {
    long cPtr = CImGuiJNI.ImFontConfig_GlyphRanges_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setGlyphMinAdvanceX(float value) {
    CImGuiJNI.ImFontConfig_GlyphMinAdvanceX_set(swigCPtr, this, value);
  }

  public float getGlyphMinAdvanceX() {
    return CImGuiJNI.ImFontConfig_GlyphMinAdvanceX_get(swigCPtr, this);
  }

  public void setGlyphMaxAdvanceX(float value) {
    CImGuiJNI.ImFontConfig_GlyphMaxAdvanceX_set(swigCPtr, this, value);
  }

  public float getGlyphMaxAdvanceX() {
    return CImGuiJNI.ImFontConfig_GlyphMaxAdvanceX_get(swigCPtr, this);
  }

  public void setMergeMode(boolean value) {
    CImGuiJNI.ImFontConfig_MergeMode_set(swigCPtr, this, value);
  }

  public boolean getMergeMode() {
    return CImGuiJNI.ImFontConfig_MergeMode_get(swigCPtr, this);
  }

  public void setRasterizerFlags(long value) {
    CImGuiJNI.ImFontConfig_RasterizerFlags_set(swigCPtr, this, value);
  }

  public long getRasterizerFlags() {
    return CImGuiJNI.ImFontConfig_RasterizerFlags_get(swigCPtr, this);
  }

  public void setRasterizerMultiply(float value) {
    CImGuiJNI.ImFontConfig_RasterizerMultiply_set(swigCPtr, this, value);
  }

  public float getRasterizerMultiply() {
    return CImGuiJNI.ImFontConfig_RasterizerMultiply_get(swigCPtr, this);
  }

  public void setEllipsisChar(int value) {
    CImGuiJNI.ImFontConfig_EllipsisChar_set(swigCPtr, this, value);
  }

  public int getEllipsisChar() {
    return CImGuiJNI.ImFontConfig_EllipsisChar_get(swigCPtr, this);
  }

  public void setName(String value) {
    CImGuiJNI.ImFontConfig_Name_set(swigCPtr, this, value);
  }

  public String getName() {
    return CImGuiJNI.ImFontConfig_Name_get(swigCPtr, this);
  }

  public void setDstFont(ImFont value) {
    CImGuiJNI.ImFontConfig_DstFont_set(swigCPtr, this, ImFont.getCPtr(value), value);
  }

  public ImFont getDstFont() {
    long cPtr = CImGuiJNI.ImFontConfig_DstFont_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImFont(cPtr, false);
  }

  public ImFontConfig() {
    this(CImGuiJNI.new_ImFontConfig(), true);
  }

}
