/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiSeparatorFlags_ {
  public final static int ImGuiSeparatorFlags_None = 0;
  public final static int ImGuiSeparatorFlags_Horizontal = 1 << 0;
  public final static int ImGuiSeparatorFlags_Vertical = 1 << 1;
  public final static int ImGuiSeparatorFlags_SpanAllColumns = 1 << 2;
}

