/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiNextWindowDataFlags_ {
  public final static int ImGuiNextWindowDataFlags_None = 0;
  public final static int ImGuiNextWindowDataFlags_HasPos = 1 << 0;
  public final static int ImGuiNextWindowDataFlags_HasSize = 1 << 1;
  public final static int ImGuiNextWindowDataFlags_HasContentSize = 1 << 2;
  public final static int ImGuiNextWindowDataFlags_HasCollapsed = 1 << 3;
  public final static int ImGuiNextWindowDataFlags_HasSizeConstraint = 1 << 4;
  public final static int ImGuiNextWindowDataFlags_HasFocus = 1 << 5;
  public final static int ImGuiNextWindowDataFlags_HasBgAlpha = 1 << 6;
}

