/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiDir_ {
  public final static int ImGuiDir_None = -1;
  public final static int ImGuiDir_Left = 0;
  public final static int ImGuiDir_Right = 1;
  public final static int ImGuiDir_Up = 2;
  public final static int ImGuiDir_Down = 3;
  public final static int ImGuiDir_COUNT = ImGuiDir_Down + 1;
}

