/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiMouseCursor_ {
  public final static int ImGuiMouseCursor_None = -1;
  public final static int ImGuiMouseCursor_Arrow = 0;
  public final static int ImGuiMouseCursor_TextInput = ImGuiMouseCursor_Arrow + 1;
  public final static int ImGuiMouseCursor_ResizeAll = ImGuiMouseCursor_TextInput + 1;
  public final static int ImGuiMouseCursor_ResizeNS = ImGuiMouseCursor_ResizeAll + 1;
  public final static int ImGuiMouseCursor_ResizeEW = ImGuiMouseCursor_ResizeNS + 1;
  public final static int ImGuiMouseCursor_ResizeNESW = ImGuiMouseCursor_ResizeEW + 1;
  public final static int ImGuiMouseCursor_ResizeNWSE = ImGuiMouseCursor_ResizeNESW + 1;
  public final static int ImGuiMouseCursor_Hand = ImGuiMouseCursor_ResizeNWSE + 1;
  public final static int ImGuiMouseCursor_NotAllowed = ImGuiMouseCursor_Hand + 1;
  public final static int ImGuiMouseCursor_COUNT = ImGuiMouseCursor_NotAllowed + 1;
}

