/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiStorage {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiStorage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiStorage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiStorage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(ImVector_ImGuiStoragePair value) {
    CImGuiJNI.ImGuiStorage_Data_set(swigCPtr, this, ImVector_ImGuiStoragePair.getCPtr(value), value);
  }

  public ImVector_ImGuiStoragePair getData() {
    long cPtr = CImGuiJNI.ImGuiStorage_Data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiStoragePair(cPtr, false);
  }

  public ImGuiStorage() {
    this(CImGuiJNI.new_ImGuiStorage(), true);
  }

}
