/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiMouseButton_ {
  public final static int ImGuiMouseButton_Left = 0;
  public final static int ImGuiMouseButton_Right = 1;
  public final static int ImGuiMouseButton_Middle = 2;
  public final static int ImGuiMouseButton_COUNT = 5;
}

