/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiTreeNodeFlags_ {
  public final static int ImGuiTreeNodeFlags_None = 0;
  public final static int ImGuiTreeNodeFlags_Selected = 1 << 0;
  public final static int ImGuiTreeNodeFlags_Framed = 1 << 1;
  public final static int ImGuiTreeNodeFlags_AllowItemOverlap = 1 << 2;
  public final static int ImGuiTreeNodeFlags_NoTreePushOnOpen = 1 << 3;
  public final static int ImGuiTreeNodeFlags_NoAutoOpenOnLog = 1 << 4;
  public final static int ImGuiTreeNodeFlags_DefaultOpen = 1 << 5;
  public final static int ImGuiTreeNodeFlags_OpenOnDoubleClick = 1 << 6;
  public final static int ImGuiTreeNodeFlags_OpenOnArrow = 1 << 7;
  public final static int ImGuiTreeNodeFlags_Leaf = 1 << 8;
  public final static int ImGuiTreeNodeFlags_Bullet = 1 << 9;
  public final static int ImGuiTreeNodeFlags_FramePadding = 1 << 10;
  public final static int ImGuiTreeNodeFlags_SpanAvailWidth = 1 << 11;
  public final static int ImGuiTreeNodeFlags_SpanFullWidth = 1 << 12;
  public final static int ImGuiTreeNodeFlags_NavLeftJumpsBackHere = 1 << 13;
  public final static int ImGuiTreeNodeFlags_CollapsingHeader = ImGuiTreeNodeFlags_Framed|ImGuiTreeNodeFlags_NoTreePushOnOpen|ImGuiTreeNodeFlags_NoAutoOpenOnLog;
}

