/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiAxis {
  public final static int ImGuiAxis_None = -1;
  public final static int ImGuiAxis_X = 0;
  public final static int ImGuiAxis_Y = 1;
}

