/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiDragDropFlags_ {
  public final static int ImGuiDragDropFlags_None = 0;
  public final static int ImGuiDragDropFlags_SourceNoPreviewTooltip = 1 << 0;
  public final static int ImGuiDragDropFlags_SourceNoDisableHover = 1 << 1;
  public final static int ImGuiDragDropFlags_SourceNoHoldToOpenOthers = 1 << 2;
  public final static int ImGuiDragDropFlags_SourceAllowNullID = 1 << 3;
  public final static int ImGuiDragDropFlags_SourceExtern = 1 << 4;
  public final static int ImGuiDragDropFlags_SourceAutoExpirePayload = 1 << 5;
  public final static int ImGuiDragDropFlags_AcceptBeforeDelivery = 1 << 10;
  public final static int ImGuiDragDropFlags_AcceptNoDrawDefaultRect = 1 << 11;
  public final static int ImGuiDragDropFlags_AcceptNoPreviewTooltip = 1 << 12;
  public final static int ImGuiDragDropFlags_AcceptPeekOnly = ImGuiDragDropFlags_AcceptBeforeDelivery|ImGuiDragDropFlags_AcceptNoDrawDefaultRect;
}

