/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiLogType {
  public final static int ImGuiLogType_None = 0;
  public final static int ImGuiLogType_TTY = ImGuiLogType_None + 1;
  public final static int ImGuiLogType_File = ImGuiLogType_TTY + 1;
  public final static int ImGuiLogType_Buffer = ImGuiLogType_File + 1;
  public final static int ImGuiLogType_Clipboard = ImGuiLogType_Buffer + 1;
}

