/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiNextItemDataFlags_ {
  public final static int ImGuiNextItemDataFlags_None = 0;
  public final static int ImGuiNextItemDataFlags_HasWidth = 1 << 0;
  public final static int ImGuiNextItemDataFlags_HasOpen = 1 << 1;
}

