/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiColorEditFlags_ {
  public final static int ImGuiColorEditFlags_None = 0;
  public final static int ImGuiColorEditFlags_NoAlpha = 1 << 1;
  public final static int ImGuiColorEditFlags_NoPicker = 1 << 2;
  public final static int ImGuiColorEditFlags_NoOptions = 1 << 3;
  public final static int ImGuiColorEditFlags_NoSmallPreview = 1 << 4;
  public final static int ImGuiColorEditFlags_NoInputs = 1 << 5;
  public final static int ImGuiColorEditFlags_NoTooltip = 1 << 6;
  public final static int ImGuiColorEditFlags_NoLabel = 1 << 7;
  public final static int ImGuiColorEditFlags_NoSidePreview = 1 << 8;
  public final static int ImGuiColorEditFlags_NoDragDrop = 1 << 9;
  public final static int ImGuiColorEditFlags_AlphaBar = 1 << 16;
  public final static int ImGuiColorEditFlags_AlphaPreview = 1 << 17;
  public final static int ImGuiColorEditFlags_AlphaPreviewHalf = 1 << 18;
  public final static int ImGuiColorEditFlags_HDR = 1 << 19;
  public final static int ImGuiColorEditFlags_DisplayRGB = 1 << 20;
  public final static int ImGuiColorEditFlags_DisplayHSV = 1 << 21;
  public final static int ImGuiColorEditFlags_DisplayHex = 1 << 22;
  public final static int ImGuiColorEditFlags_Uint8 = 1 << 23;
  public final static int ImGuiColorEditFlags_Float = 1 << 24;
  public final static int ImGuiColorEditFlags_PickerHueBar = 1 << 25;
  public final static int ImGuiColorEditFlags_PickerHueWheel = 1 << 26;
  public final static int ImGuiColorEditFlags_InputRGB = 1 << 27;
  public final static int ImGuiColorEditFlags_InputHSV = 1 << 28;
  public final static int ImGuiColorEditFlags__OptionsDefault = ImGuiColorEditFlags_Uint8|ImGuiColorEditFlags_DisplayRGB|ImGuiColorEditFlags_InputRGB|ImGuiColorEditFlags_PickerHueBar;
  public final static int ImGuiColorEditFlags__DisplayMask = ImGuiColorEditFlags_DisplayRGB|ImGuiColorEditFlags_DisplayHSV|ImGuiColorEditFlags_DisplayHex;
  public final static int ImGuiColorEditFlags__DataTypeMask = ImGuiColorEditFlags_Uint8|ImGuiColorEditFlags_Float;
  public final static int ImGuiColorEditFlags__PickerMask = ImGuiColorEditFlags_PickerHueWheel|ImGuiColorEditFlags_PickerHueBar;
  public final static int ImGuiColorEditFlags__InputMask = ImGuiColorEditFlags_InputRGB|ImGuiColorEditFlags_InputHSV;
}

