/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiStyleMod {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiStyleMod(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiStyleMod obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiStyleMod(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVarIdx(int value) {
    CImGuiJNI.ImGuiStyleMod_VarIdx_set(swigCPtr, this, value);
  }

  public int getVarIdx() {
    return CImGuiJNI.ImGuiStyleMod_VarIdx_get(swigCPtr, this);
  }

  public void setBackupInt(SWIGTYPE_p_int value) {
    CImGuiJNI.ImGuiStyleMod_BackupInt_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getBackupInt() {
    long cPtr = CImGuiJNI.ImGuiStyleMod_BackupInt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setBackupFloat(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiStyleMod_BackupFloat_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBackupFloat() {
    long cPtr = CImGuiJNI.ImGuiStyleMod_BackupFloat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public ImGuiStyleMod() {
    this(CImGuiJNI.new_ImGuiStyleMod(), true);
  }

}
