/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiNavHighlightFlags_ {
  public final static int ImGuiNavHighlightFlags_None = 0;
  public final static int ImGuiNavHighlightFlags_TypeDefault = 1 << 0;
  public final static int ImGuiNavHighlightFlags_TypeThin = 1 << 1;
  public final static int ImGuiNavHighlightFlags_AlwaysDraw = 1 << 2;
  public final static int ImGuiNavHighlightFlags_NoRounding = 1 << 3;
}

