/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiPopupData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiPopupData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiPopupData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiPopupData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPopupId(long value) {
    CImGuiJNI.ImGuiPopupData_PopupId_set(swigCPtr, this, value);
  }

  public long getPopupId() {
    return CImGuiJNI.ImGuiPopupData_PopupId_get(swigCPtr, this);
  }

  public void setWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiPopupData_Window_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getWindow() {
    long cPtr = CImGuiJNI.ImGuiPopupData_Window_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setSourceWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiPopupData_SourceWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getSourceWindow() {
    long cPtr = CImGuiJNI.ImGuiPopupData_SourceWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setOpenFrameCount(int value) {
    CImGuiJNI.ImGuiPopupData_OpenFrameCount_set(swigCPtr, this, value);
  }

  public int getOpenFrameCount() {
    return CImGuiJNI.ImGuiPopupData_OpenFrameCount_get(swigCPtr, this);
  }

  public void setOpenParentId(long value) {
    CImGuiJNI.ImGuiPopupData_OpenParentId_set(swigCPtr, this, value);
  }

  public long getOpenParentId() {
    return CImGuiJNI.ImGuiPopupData_OpenParentId_get(swigCPtr, this);
  }

  public void setOpenPopupPos(ImVec2 value) {
    CImGuiJNI.ImGuiPopupData_OpenPopupPos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getOpenPopupPos() {
    long cPtr = CImGuiJNI.ImGuiPopupData_OpenPopupPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setOpenMousePos(ImVec2 value) {
    CImGuiJNI.ImGuiPopupData_OpenMousePos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getOpenMousePos() {
    long cPtr = CImGuiJNI.ImGuiPopupData_OpenMousePos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public ImGuiPopupData() {
    this(CImGuiJNI.new_ImGuiPopupData(), true);
  }

}
