/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiGroupData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiGroupData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiGroupData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiGroupData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBackupCursorPos(ImVec2 value) {
    CImGuiJNI.ImGuiGroupData_BackupCursorPos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getBackupCursorPos() {
    long cPtr = CImGuiJNI.ImGuiGroupData_BackupCursorPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setBackupCursorMaxPos(ImVec2 value) {
    CImGuiJNI.ImGuiGroupData_BackupCursorMaxPos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getBackupCursorMaxPos() {
    long cPtr = CImGuiJNI.ImGuiGroupData_BackupCursorMaxPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setBackupIndent(ImVec1 value) {
    CImGuiJNI.ImGuiGroupData_BackupIndent_set(swigCPtr, this, ImVec1.getCPtr(value), value);
  }

  public ImVec1 getBackupIndent() {
    long cPtr = CImGuiJNI.ImGuiGroupData_BackupIndent_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec1(cPtr, false);
  }

  public void setBackupGroupOffset(ImVec1 value) {
    CImGuiJNI.ImGuiGroupData_BackupGroupOffset_set(swigCPtr, this, ImVec1.getCPtr(value), value);
  }

  public ImVec1 getBackupGroupOffset() {
    long cPtr = CImGuiJNI.ImGuiGroupData_BackupGroupOffset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec1(cPtr, false);
  }

  public void setBackupCurrLineSize(ImVec2 value) {
    CImGuiJNI.ImGuiGroupData_BackupCurrLineSize_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getBackupCurrLineSize() {
    long cPtr = CImGuiJNI.ImGuiGroupData_BackupCurrLineSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setBackupCurrLineTextBaseOffset(float value) {
    CImGuiJNI.ImGuiGroupData_BackupCurrLineTextBaseOffset_set(swigCPtr, this, value);
  }

  public float getBackupCurrLineTextBaseOffset() {
    return CImGuiJNI.ImGuiGroupData_BackupCurrLineTextBaseOffset_get(swigCPtr, this);
  }

  public void setBackupActiveIdIsAlive(long value) {
    CImGuiJNI.ImGuiGroupData_BackupActiveIdIsAlive_set(swigCPtr, this, value);
  }

  public long getBackupActiveIdIsAlive() {
    return CImGuiJNI.ImGuiGroupData_BackupActiveIdIsAlive_get(swigCPtr, this);
  }

  public void setBackupActiveIdPreviousFrameIsAlive(boolean value) {
    CImGuiJNI.ImGuiGroupData_BackupActiveIdPreviousFrameIsAlive_set(swigCPtr, this, value);
  }

  public boolean getBackupActiveIdPreviousFrameIsAlive() {
    return CImGuiJNI.ImGuiGroupData_BackupActiveIdPreviousFrameIsAlive_get(swigCPtr, this);
  }

  public void setEmitItem(boolean value) {
    CImGuiJNI.ImGuiGroupData_EmitItem_set(swigCPtr, this, value);
  }

  public boolean getEmitItem() {
    return CImGuiJNI.ImGuiGroupData_EmitItem_get(swigCPtr, this);
  }

  public ImGuiGroupData() {
    this(CImGuiJNI.new_ImGuiGroupData(), true);
  }

}
