/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiPopupFlags_ {
  public final static int ImGuiPopupFlags_None = 0;
  public final static int ImGuiPopupFlags_MouseButtonLeft = 0;
  public final static int ImGuiPopupFlags_MouseButtonRight = 1;
  public final static int ImGuiPopupFlags_MouseButtonMiddle = 2;
  public final static int ImGuiPopupFlags_MouseButtonMask_ = 0x1F;
  public final static int ImGuiPopupFlags_MouseButtonDefault_ = 1;
  public final static int ImGuiPopupFlags_NoOpenOverExistingPopup = 1 << 5;
  public final static int ImGuiPopupFlags_NoOpenOverItems = 1 << 6;
  public final static int ImGuiPopupFlags_AnyPopupId = 1 << 7;
  public final static int ImGuiPopupFlags_AnyPopupLevel = 1 << 8;
  public final static int ImGuiPopupFlags_AnyPopup = ImGuiPopupFlags_AnyPopupId|ImGuiPopupFlags_AnyPopupLevel;
}

