/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiStoragePair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiStoragePair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiStoragePair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiStoragePair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKey(long value) {
    CImGuiJNI.ImGuiStoragePair_key_set(swigCPtr, this, value);
  }

  public long getKey() {
    return CImGuiJNI.ImGuiStoragePair_key_get(swigCPtr, this);
  }

  public void setVal_i(int value) {
    CImGuiJNI.ImGuiStoragePair_val_i_set(swigCPtr, this, value);
  }

  public int getVal_i() {
    return CImGuiJNI.ImGuiStoragePair_val_i_get(swigCPtr, this);
  }

  public void setVal_f(float value) {
    CImGuiJNI.ImGuiStoragePair_val_f_set(swigCPtr, this, value);
  }

  public float getVal_f() {
    return CImGuiJNI.ImGuiStoragePair_val_f_get(swigCPtr, this);
  }

  public void setVal_p(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiStoragePair_val_p_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getVal_p() {
    long cPtr = CImGuiJNI.ImGuiStoragePair_val_p_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public ImGuiStoragePair() {
    this(CImGuiJNI.new_ImGuiStoragePair(), true);
  }

}
