/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiButtonFlags_ {
  public final static int ImGuiButtonFlags_None = 0;
  public final static int ImGuiButtonFlags_Repeat = 1 << 0;
  public final static int ImGuiButtonFlags_PressedOnClick = 1 << 1;
  public final static int ImGuiButtonFlags_PressedOnClickRelease = 1 << 2;
  public final static int ImGuiButtonFlags_PressedOnClickReleaseAnywhere = 1 << 3;
  public final static int ImGuiButtonFlags_PressedOnRelease = 1 << 4;
  public final static int ImGuiButtonFlags_PressedOnDoubleClick = 1 << 5;
  public final static int ImGuiButtonFlags_PressedOnDragDropHold = 1 << 6;
  public final static int ImGuiButtonFlags_FlattenChildren = 1 << 7;
  public final static int ImGuiButtonFlags_AllowItemOverlap = 1 << 8;
  public final static int ImGuiButtonFlags_DontClosePopups = 1 << 9;
  public final static int ImGuiButtonFlags_Disabled = 1 << 10;
  public final static int ImGuiButtonFlags_AlignTextBaseLine = 1 << 11;
  public final static int ImGuiButtonFlags_NoKeyModifiers = 1 << 12;
  public final static int ImGuiButtonFlags_NoHoldingActiveId = 1 << 13;
  public final static int ImGuiButtonFlags_NoNavFocus = 1 << 14;
  public final static int ImGuiButtonFlags_NoHoveredOnFocus = 1 << 15;
  public final static int ImGuiButtonFlags_MouseButtonLeft = 1 << 16;
  public final static int ImGuiButtonFlags_MouseButtonRight = 1 << 17;
  public final static int ImGuiButtonFlags_MouseButtonMiddle = 1 << 18;
  public final static int ImGuiButtonFlags_MouseButtonMask_ = ImGuiButtonFlags_MouseButtonLeft|ImGuiButtonFlags_MouseButtonRight|ImGuiButtonFlags_MouseButtonMiddle;
  public final static int ImGuiButtonFlags_MouseButtonShift_ = 16;
  public final static int ImGuiButtonFlags_MouseButtonDefault_ = ImGuiButtonFlags_MouseButtonLeft;
  public final static int ImGuiButtonFlags_PressedOnMask_ = ImGuiButtonFlags_PressedOnClick|ImGuiButtonFlags_PressedOnClickRelease|ImGuiButtonFlags_PressedOnClickReleaseAnywhere|ImGuiButtonFlags_PressedOnRelease|ImGuiButtonFlags_PressedOnDoubleClick|ImGuiButtonFlags_PressedOnDragDropHold;
  public final static int ImGuiButtonFlags_PressedOnDefault_ = ImGuiButtonFlags_PressedOnClickRelease;
}

