/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiDataAuthority_ {
  public final static int ImGuiDataAuthority_Auto = 0;
  public final static int ImGuiDataAuthority_DockNode = ImGuiDataAuthority_Auto + 1;
  public final static int ImGuiDataAuthority_Window = ImGuiDataAuthority_DockNode + 1;
}

