/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiTooltipFlags_ {
  public final static int ImGuiTooltipFlags_None = 0;
  public final static int ImGuiTooltipFlags_OverridePreviousTooltip = 1 << 0;
}

