/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiNavInput_ {
  public final static int ImGuiNavInput_Activate = 0;
  public final static int ImGuiNavInput_Cancel = ImGuiNavInput_Activate + 1;
  public final static int ImGuiNavInput_Input = ImGuiNavInput_Cancel + 1;
  public final static int ImGuiNavInput_Menu = ImGuiNavInput_Input + 1;
  public final static int ImGuiNavInput_DpadLeft = ImGuiNavInput_Menu + 1;
  public final static int ImGuiNavInput_DpadRight = ImGuiNavInput_DpadLeft + 1;
  public final static int ImGuiNavInput_DpadUp = ImGuiNavInput_DpadRight + 1;
  public final static int ImGuiNavInput_DpadDown = ImGuiNavInput_DpadUp + 1;
  public final static int ImGuiNavInput_LStickLeft = ImGuiNavInput_DpadDown + 1;
  public final static int ImGuiNavInput_LStickRight = ImGuiNavInput_LStickLeft + 1;
  public final static int ImGuiNavInput_LStickUp = ImGuiNavInput_LStickRight + 1;
  public final static int ImGuiNavInput_LStickDown = ImGuiNavInput_LStickUp + 1;
  public final static int ImGuiNavInput_FocusPrev = ImGuiNavInput_LStickDown + 1;
  public final static int ImGuiNavInput_FocusNext = ImGuiNavInput_FocusPrev + 1;
  public final static int ImGuiNavInput_TweakSlow = ImGuiNavInput_FocusNext + 1;
  public final static int ImGuiNavInput_TweakFast = ImGuiNavInput_TweakSlow + 1;
  public final static int ImGuiNavInput_KeyMenu_ = ImGuiNavInput_TweakFast + 1;
  public final static int ImGuiNavInput_KeyLeft_ = ImGuiNavInput_KeyMenu_ + 1;
  public final static int ImGuiNavInput_KeyRight_ = ImGuiNavInput_KeyLeft_ + 1;
  public final static int ImGuiNavInput_KeyUp_ = ImGuiNavInput_KeyRight_ + 1;
  public final static int ImGuiNavInput_KeyDown_ = ImGuiNavInput_KeyUp_ + 1;
  public final static int ImGuiNavInput_COUNT = ImGuiNavInput_KeyDown_ + 1;
  public final static int ImGuiNavInput_InternalStart_ = ImGuiNavInput_KeyMenu_;
}

