/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiTabBarFlags_ {
  public final static int ImGuiTabBarFlags_None = 0;
  public final static int ImGuiTabBarFlags_Reorderable = 1 << 0;
  public final static int ImGuiTabBarFlags_AutoSelectNewTabs = 1 << 1;
  public final static int ImGuiTabBarFlags_TabListPopupButton = 1 << 2;
  public final static int ImGuiTabBarFlags_NoCloseWithMiddleMouseButton = 1 << 3;
  public final static int ImGuiTabBarFlags_NoTabListScrollingButtons = 1 << 4;
  public final static int ImGuiTabBarFlags_NoTooltip = 1 << 5;
  public final static int ImGuiTabBarFlags_FittingPolicyResizeDown = 1 << 6;
  public final static int ImGuiTabBarFlags_FittingPolicyScroll = 1 << 7;
  public final static int ImGuiTabBarFlags_FittingPolicyMask_ = ImGuiTabBarFlags_FittingPolicyResizeDown|ImGuiTabBarFlags_FittingPolicyScroll;
  public final static int ImGuiTabBarFlags_FittingPolicyDefault_ = ImGuiTabBarFlags_FittingPolicyResizeDown;
}

