/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiSelectableFlags_ {
  public final static int ImGuiSelectableFlags_None = 0;
  public final static int ImGuiSelectableFlags_DontClosePopups = 1 << 0;
  public final static int ImGuiSelectableFlags_SpanAllColumns = 1 << 1;
  public final static int ImGuiSelectableFlags_AllowDoubleClick = 1 << 2;
  public final static int ImGuiSelectableFlags_Disabled = 1 << 3;
  public final static int ImGuiSelectableFlags_AllowItemOverlap = 1 << 4;
}

