/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiComboFlags_ {
  public final static int ImGuiComboFlags_None = 0;
  public final static int ImGuiComboFlags_PopupAlignLeft = 1 << 0;
  public final static int ImGuiComboFlags_HeightSmall = 1 << 1;
  public final static int ImGuiComboFlags_HeightRegular = 1 << 2;
  public final static int ImGuiComboFlags_HeightLarge = 1 << 3;
  public final static int ImGuiComboFlags_HeightLargest = 1 << 4;
  public final static int ImGuiComboFlags_NoArrowButton = 1 << 5;
  public final static int ImGuiComboFlags_NoPreview = 1 << 6;
  public final static int ImGuiComboFlags_HeightMask_ = ImGuiComboFlags_HeightSmall|ImGuiComboFlags_HeightRegular|ImGuiComboFlags_HeightLarge|ImGuiComboFlags_HeightLargest;
}

