/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiSelectableFlagsPrivate_ {
  public final static int ImGuiSelectableFlags_NoHoldingActiveID = 1 << 20;
  public final static int ImGuiSelectableFlags_SelectOnClick = 1 << 21;
  public final static int ImGuiSelectableFlags_SelectOnRelease = 1 << 22;
  public final static int ImGuiSelectableFlags_SpanAvailWidth = 1 << 23;
  public final static int ImGuiSelectableFlags_DrawHoveredWhenHeld = 1 << 24;
  public final static int ImGuiSelectableFlags_SetNavIdOnHover = 1 << 25;
}

