/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiTextBuffer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiTextBuffer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiTextBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiTextBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBuf(ImVector_char value) {
    CImGuiJNI.ImGuiTextBuffer_Buf_set(swigCPtr, this, ImVector_char.getCPtr(value), value);
  }

  public ImVector_char getBuf() {
    long cPtr = CImGuiJNI.ImGuiTextBuffer_Buf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_char(cPtr, false);
  }

  public ImGuiTextBuffer() {
    this(CImGuiJNI.new_ImGuiTextBuffer(), true);
  }

}
