/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiFocusedFlags_ {
  public final static int ImGuiFocusedFlags_None = 0;
  public final static int ImGuiFocusedFlags_ChildWindows = 1 << 0;
  public final static int ImGuiFocusedFlags_RootWindow = 1 << 1;
  public final static int ImGuiFocusedFlags_AnyWindow = 1 << 2;
  public final static int ImGuiFocusedFlags_RootAndChildWindows = ImGuiFocusedFlags_RootWindow|ImGuiFocusedFlags_ChildWindows;
}

