/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiColumnsFlags_ {
  public final static int ImGuiColumnsFlags_None = 0;
  public final static int ImGuiColumnsFlags_NoBorder = 1 << 0;
  public final static int ImGuiColumnsFlags_NoResize = 1 << 1;
  public final static int ImGuiColumnsFlags_NoPreserveWidths = 1 << 2;
  public final static int ImGuiColumnsFlags_NoForceWithinWindow = 1 << 3;
  public final static int ImGuiColumnsFlags_GrowParentContentsSize = 1 << 4;
}

