/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiInputReadMode {
  public final static int ImGuiInputReadMode_Down = 0;
  public final static int ImGuiInputReadMode_Pressed = ImGuiInputReadMode_Down + 1;
  public final static int ImGuiInputReadMode_Released = ImGuiInputReadMode_Pressed + 1;
  public final static int ImGuiInputReadMode_Repeat = ImGuiInputReadMode_Released + 1;
  public final static int ImGuiInputReadMode_RepeatSlow = ImGuiInputReadMode_Repeat + 1;
  public final static int ImGuiInputReadMode_RepeatFast = ImGuiInputReadMode_RepeatSlow + 1;
}

