/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiInputSource {
  public final static int ImGuiInputSource_None = 0;
  public final static int ImGuiInputSource_Mouse = ImGuiInputSource_None + 1;
  public final static int ImGuiInputSource_Nav = ImGuiInputSource_Mouse + 1;
  public final static int ImGuiInputSource_NavKeyboard = ImGuiInputSource_Nav + 1;
  public final static int ImGuiInputSource_NavGamepad = ImGuiInputSource_NavKeyboard + 1;
  public final static int ImGuiInputSource_COUNT = ImGuiInputSource_NavGamepad + 1;
}

