/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiDockNodeFlags_ {
  public final static int ImGuiDockNodeFlags_None = 0;
  public final static int ImGuiDockNodeFlags_KeepAliveOnly = 1 << 0;
  public final static int ImGuiDockNodeFlags_NoDockingInCentralNode = 1 << 2;
  public final static int ImGuiDockNodeFlags_PassthruCentralNode = 1 << 3;
  public final static int ImGuiDockNodeFlags_NoSplit = 1 << 4;
  public final static int ImGuiDockNodeFlags_NoResize = 1 << 5;
  public final static int ImGuiDockNodeFlags_AutoHideTabBar = 1 << 6;
}

