/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiDockContext {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiDockContext(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiDockContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiDockContext(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNodes(ImGuiStorage value) {
    CImGuiJNI.ImGuiDockContext_Nodes_set(swigCPtr, this, ImGuiStorage.getCPtr(value), value);
  }

  public ImGuiStorage getNodes() {
    long cPtr = CImGuiJNI.ImGuiDockContext_Nodes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiStorage(cPtr, false);
  }

  public void setRequests(ImVector_ImGuiDockRequest value) {
    CImGuiJNI.ImGuiDockContext_Requests_set(swigCPtr, this, ImVector_ImGuiDockRequest.getCPtr(value), value);
  }

  public ImVector_ImGuiDockRequest getRequests() {
    long cPtr = CImGuiJNI.ImGuiDockContext_Requests_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiDockRequest(cPtr, false);
  }

  public void setNodesSettings(ImVector_ImGuiDockNodeSettings value) {
    CImGuiJNI.ImGuiDockContext_NodesSettings_set(swigCPtr, this, ImVector_ImGuiDockNodeSettings.getCPtr(value), value);
  }

  public ImVector_ImGuiDockNodeSettings getNodesSettings() {
    long cPtr = CImGuiJNI.ImGuiDockContext_NodesSettings_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiDockNodeSettings(cPtr, false);
  }

  public void setWantFullRebuild(boolean value) {
    CImGuiJNI.ImGuiDockContext_WantFullRebuild_set(swigCPtr, this, value);
  }

  public boolean getWantFullRebuild() {
    return CImGuiJNI.ImGuiDockContext_WantFullRebuild_get(swigCPtr, this);
  }

  public ImGuiDockContext() {
    this(CImGuiJNI.new_ImGuiDockContext(), true);
  }

}
