/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiTreeNodeFlagsPrivate_ {
  public final static int ImGuiTreeNodeFlags_ClipLabelForTrailingButton = 1 << 20;
}

