/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiKeyModFlags_ {
  public final static int ImGuiKeyModFlags_None = 0;
  public final static int ImGuiKeyModFlags_Ctrl = 1 << 0;
  public final static int ImGuiKeyModFlags_Shift = 1 << 1;
  public final static int ImGuiKeyModFlags_Alt = 1 << 2;
  public final static int ImGuiKeyModFlags_Super = 1 << 3;
}

