/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiColumns {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiColumns(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiColumns obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiColumns(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setID(long value) {
    CImGuiJNI.ImGuiColumns_ID_set(swigCPtr, this, value);
  }

  public long getID() {
    return CImGuiJNI.ImGuiColumns_ID_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    CImGuiJNI.ImGuiColumns_Flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return CImGuiJNI.ImGuiColumns_Flags_get(swigCPtr, this);
  }

  public void setIsFirstFrame(boolean value) {
    CImGuiJNI.ImGuiColumns_IsFirstFrame_set(swigCPtr, this, value);
  }

  public boolean getIsFirstFrame() {
    return CImGuiJNI.ImGuiColumns_IsFirstFrame_get(swigCPtr, this);
  }

  public void setIsBeingResized(boolean value) {
    CImGuiJNI.ImGuiColumns_IsBeingResized_set(swigCPtr, this, value);
  }

  public boolean getIsBeingResized() {
    return CImGuiJNI.ImGuiColumns_IsBeingResized_get(swigCPtr, this);
  }

  public void setCurrent(int value) {
    CImGuiJNI.ImGuiColumns_Current_set(swigCPtr, this, value);
  }

  public int getCurrent() {
    return CImGuiJNI.ImGuiColumns_Current_get(swigCPtr, this);
  }

  public void setCount(int value) {
    CImGuiJNI.ImGuiColumns_Count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return CImGuiJNI.ImGuiColumns_Count_get(swigCPtr, this);
  }

  public void setOffMinX(float value) {
    CImGuiJNI.ImGuiColumns_OffMinX_set(swigCPtr, this, value);
  }

  public float getOffMinX() {
    return CImGuiJNI.ImGuiColumns_OffMinX_get(swigCPtr, this);
  }

  public void setOffMaxX(float value) {
    CImGuiJNI.ImGuiColumns_OffMaxX_set(swigCPtr, this, value);
  }

  public float getOffMaxX() {
    return CImGuiJNI.ImGuiColumns_OffMaxX_get(swigCPtr, this);
  }

  public void setLineMinY(float value) {
    CImGuiJNI.ImGuiColumns_LineMinY_set(swigCPtr, this, value);
  }

  public float getLineMinY() {
    return CImGuiJNI.ImGuiColumns_LineMinY_get(swigCPtr, this);
  }

  public void setLineMaxY(float value) {
    CImGuiJNI.ImGuiColumns_LineMaxY_set(swigCPtr, this, value);
  }

  public float getLineMaxY() {
    return CImGuiJNI.ImGuiColumns_LineMaxY_get(swigCPtr, this);
  }

  public void setHostCursorPosY(float value) {
    CImGuiJNI.ImGuiColumns_HostCursorPosY_set(swigCPtr, this, value);
  }

  public float getHostCursorPosY() {
    return CImGuiJNI.ImGuiColumns_HostCursorPosY_get(swigCPtr, this);
  }

  public void setHostCursorMaxPosX(float value) {
    CImGuiJNI.ImGuiColumns_HostCursorMaxPosX_set(swigCPtr, this, value);
  }

  public float getHostCursorMaxPosX() {
    return CImGuiJNI.ImGuiColumns_HostCursorMaxPosX_get(swigCPtr, this);
  }

  public void setHostClipRect(ImRect value) {
    CImGuiJNI.ImGuiColumns_HostClipRect_set(swigCPtr, this, ImRect.getCPtr(value), value);
  }

  public ImRect getHostClipRect() {
    long cPtr = CImGuiJNI.ImGuiColumns_HostClipRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImRect(cPtr, false);
  }

  public void setHostWorkRect(ImRect value) {
    CImGuiJNI.ImGuiColumns_HostWorkRect_set(swigCPtr, this, ImRect.getCPtr(value), value);
  }

  public ImRect getHostWorkRect() {
    long cPtr = CImGuiJNI.ImGuiColumns_HostWorkRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImRect(cPtr, false);
  }

  public void setColumns(ImVector_ImGuiColumnData value) {
    CImGuiJNI.ImGuiColumns_Columns_set(swigCPtr, this, ImVector_ImGuiColumnData.getCPtr(value), value);
  }

  public ImVector_ImGuiColumnData getColumns() {
    long cPtr = CImGuiJNI.ImGuiColumns_Columns_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiColumnData(cPtr, false);
  }

  public void setSplitter(ImDrawListSplitter value) {
    CImGuiJNI.ImGuiColumns_Splitter_set(swigCPtr, this, ImDrawListSplitter.getCPtr(value), value);
  }

  public ImDrawListSplitter getSplitter() {
    long cPtr = CImGuiJNI.ImGuiColumns_Splitter_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawListSplitter(cPtr, false);
  }

  public ImGuiColumns() {
    this(CImGuiJNI.new_ImGuiColumns(), true);
  }

}
