/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiContext {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiContext(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiContext(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInitialized(boolean value) {
    CImGuiJNI.ImGuiContext_Initialized_set(swigCPtr, this, value);
  }

  public boolean getInitialized() {
    return CImGuiJNI.ImGuiContext_Initialized_get(swigCPtr, this);
  }

  public void setFontAtlasOwnedByContext(boolean value) {
    CImGuiJNI.ImGuiContext_FontAtlasOwnedByContext_set(swigCPtr, this, value);
  }

  public boolean getFontAtlasOwnedByContext() {
    return CImGuiJNI.ImGuiContext_FontAtlasOwnedByContext_get(swigCPtr, this);
  }

  public void setIO(ImGuiIO value) {
    CImGuiJNI.ImGuiContext_IO_set(swigCPtr, this, ImGuiIO.getCPtr(value), value);
  }

  public ImGuiIO getIO() {
    long cPtr = CImGuiJNI.ImGuiContext_IO_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiIO(cPtr, false);
  }

  public void setStyle(ImGuiStyle value) {
    CImGuiJNI.ImGuiContext_Style_set(swigCPtr, this, ImGuiStyle.getCPtr(value), value);
  }

  public ImGuiStyle getStyle() {
    long cPtr = CImGuiJNI.ImGuiContext_Style_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiStyle(cPtr, false);
  }

  public void setFont(ImFont value) {
    CImGuiJNI.ImGuiContext_Font_set(swigCPtr, this, ImFont.getCPtr(value), value);
  }

  public ImFont getFont() {
    long cPtr = CImGuiJNI.ImGuiContext_Font_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImFont(cPtr, false);
  }

  public void setFontSize(float value) {
    CImGuiJNI.ImGuiContext_FontSize_set(swigCPtr, this, value);
  }

  public float getFontSize() {
    return CImGuiJNI.ImGuiContext_FontSize_get(swigCPtr, this);
  }

  public void setFontBaseSize(float value) {
    CImGuiJNI.ImGuiContext_FontBaseSize_set(swigCPtr, this, value);
  }

  public float getFontBaseSize() {
    return CImGuiJNI.ImGuiContext_FontBaseSize_get(swigCPtr, this);
  }

  public void setDrawListSharedData(ImDrawListSharedData value) {
    CImGuiJNI.ImGuiContext_DrawListSharedData_set(swigCPtr, this, ImDrawListSharedData.getCPtr(value), value);
  }

  public ImDrawListSharedData getDrawListSharedData() {
    long cPtr = CImGuiJNI.ImGuiContext_DrawListSharedData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawListSharedData(cPtr, false);
  }

  public void setTime(double value) {
    CImGuiJNI.ImGuiContext_Time_set(swigCPtr, this, value);
  }

  public double getTime() {
    return CImGuiJNI.ImGuiContext_Time_get(swigCPtr, this);
  }

  public void setFrameCount(int value) {
    CImGuiJNI.ImGuiContext_FrameCount_set(swigCPtr, this, value);
  }

  public int getFrameCount() {
    return CImGuiJNI.ImGuiContext_FrameCount_get(swigCPtr, this);
  }

  public void setFrameCountEnded(int value) {
    CImGuiJNI.ImGuiContext_FrameCountEnded_set(swigCPtr, this, value);
  }

  public int getFrameCountEnded() {
    return CImGuiJNI.ImGuiContext_FrameCountEnded_get(swigCPtr, this);
  }

  public void setFrameCountRendered(int value) {
    CImGuiJNI.ImGuiContext_FrameCountRendered_set(swigCPtr, this, value);
  }

  public int getFrameCountRendered() {
    return CImGuiJNI.ImGuiContext_FrameCountRendered_get(swigCPtr, this);
  }

  public void setWithinFrameScope(boolean value) {
    CImGuiJNI.ImGuiContext_WithinFrameScope_set(swigCPtr, this, value);
  }

  public boolean getWithinFrameScope() {
    return CImGuiJNI.ImGuiContext_WithinFrameScope_get(swigCPtr, this);
  }

  public void setWithinFrameScopeWithImplicitWindow(boolean value) {
    CImGuiJNI.ImGuiContext_WithinFrameScopeWithImplicitWindow_set(swigCPtr, this, value);
  }

  public boolean getWithinFrameScopeWithImplicitWindow() {
    return CImGuiJNI.ImGuiContext_WithinFrameScopeWithImplicitWindow_get(swigCPtr, this);
  }

  public void setWithinEndChild(boolean value) {
    CImGuiJNI.ImGuiContext_WithinEndChild_set(swigCPtr, this, value);
  }

  public boolean getWithinEndChild() {
    return CImGuiJNI.ImGuiContext_WithinEndChild_get(swigCPtr, this);
  }

  public void setTestEngineHookItems(boolean value) {
    CImGuiJNI.ImGuiContext_TestEngineHookItems_set(swigCPtr, this, value);
  }

  public boolean getTestEngineHookItems() {
    return CImGuiJNI.ImGuiContext_TestEngineHookItems_get(swigCPtr, this);
  }

  public void setTestEngineHookIdInfo(long value) {
    CImGuiJNI.ImGuiContext_TestEngineHookIdInfo_set(swigCPtr, this, value);
  }

  public long getTestEngineHookIdInfo() {
    return CImGuiJNI.ImGuiContext_TestEngineHookIdInfo_get(swigCPtr, this);
  }

  public void setTestEngine(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiContext_TestEngine_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getTestEngine() {
    long cPtr = CImGuiJNI.ImGuiContext_TestEngine_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setWindows(ImVector_ImGuiWindowPtr value) {
    CImGuiJNI.ImGuiContext_Windows_set(swigCPtr, this, ImVector_ImGuiWindowPtr.getCPtr(value), value);
  }

  public ImVector_ImGuiWindowPtr getWindows() {
    long cPtr = CImGuiJNI.ImGuiContext_Windows_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiWindowPtr(cPtr, false);
  }

  public void setWindowsFocusOrder(ImVector_ImGuiWindowPtr value) {
    CImGuiJNI.ImGuiContext_WindowsFocusOrder_set(swigCPtr, this, ImVector_ImGuiWindowPtr.getCPtr(value), value);
  }

  public ImVector_ImGuiWindowPtr getWindowsFocusOrder() {
    long cPtr = CImGuiJNI.ImGuiContext_WindowsFocusOrder_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiWindowPtr(cPtr, false);
  }

  public void setWindowsTempSortBuffer(ImVector_ImGuiWindowPtr value) {
    CImGuiJNI.ImGuiContext_WindowsTempSortBuffer_set(swigCPtr, this, ImVector_ImGuiWindowPtr.getCPtr(value), value);
  }

  public ImVector_ImGuiWindowPtr getWindowsTempSortBuffer() {
    long cPtr = CImGuiJNI.ImGuiContext_WindowsTempSortBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiWindowPtr(cPtr, false);
  }

  public void setCurrentWindowStack(ImVector_ImGuiWindowPtr value) {
    CImGuiJNI.ImGuiContext_CurrentWindowStack_set(swigCPtr, this, ImVector_ImGuiWindowPtr.getCPtr(value), value);
  }

  public ImVector_ImGuiWindowPtr getCurrentWindowStack() {
    long cPtr = CImGuiJNI.ImGuiContext_CurrentWindowStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiWindowPtr(cPtr, false);
  }

  public void setWindowsById(ImGuiStorage value) {
    CImGuiJNI.ImGuiContext_WindowsById_set(swigCPtr, this, ImGuiStorage.getCPtr(value), value);
  }

  public ImGuiStorage getWindowsById() {
    long cPtr = CImGuiJNI.ImGuiContext_WindowsById_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiStorage(cPtr, false);
  }

  public void setWindowsActiveCount(int value) {
    CImGuiJNI.ImGuiContext_WindowsActiveCount_set(swigCPtr, this, value);
  }

  public int getWindowsActiveCount() {
    return CImGuiJNI.ImGuiContext_WindowsActiveCount_get(swigCPtr, this);
  }

  public void setCurrentWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_CurrentWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getCurrentWindow() {
    long cPtr = CImGuiJNI.ImGuiContext_CurrentWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setHoveredWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_HoveredWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getHoveredWindow() {
    long cPtr = CImGuiJNI.ImGuiContext_HoveredWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setHoveredRootWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_HoveredRootWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getHoveredRootWindow() {
    long cPtr = CImGuiJNI.ImGuiContext_HoveredRootWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setMovingWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_MovingWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getMovingWindow() {
    long cPtr = CImGuiJNI.ImGuiContext_MovingWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setWheelingWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_WheelingWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getWheelingWindow() {
    long cPtr = CImGuiJNI.ImGuiContext_WheelingWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setWheelingWindowRefMousePos(ImVec2 value) {
    CImGuiJNI.ImGuiContext_WheelingWindowRefMousePos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getWheelingWindowRefMousePos() {
    long cPtr = CImGuiJNI.ImGuiContext_WheelingWindowRefMousePos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setWheelingWindowTimer(float value) {
    CImGuiJNI.ImGuiContext_WheelingWindowTimer_set(swigCPtr, this, value);
  }

  public float getWheelingWindowTimer() {
    return CImGuiJNI.ImGuiContext_WheelingWindowTimer_get(swigCPtr, this);
  }

  public void setHoveredId(long value) {
    CImGuiJNI.ImGuiContext_HoveredId_set(swigCPtr, this, value);
  }

  public long getHoveredId() {
    return CImGuiJNI.ImGuiContext_HoveredId_get(swigCPtr, this);
  }

  public void setHoveredIdAllowOverlap(boolean value) {
    CImGuiJNI.ImGuiContext_HoveredIdAllowOverlap_set(swigCPtr, this, value);
  }

  public boolean getHoveredIdAllowOverlap() {
    return CImGuiJNI.ImGuiContext_HoveredIdAllowOverlap_get(swigCPtr, this);
  }

  public void setHoveredIdPreviousFrame(long value) {
    CImGuiJNI.ImGuiContext_HoveredIdPreviousFrame_set(swigCPtr, this, value);
  }

  public long getHoveredIdPreviousFrame() {
    return CImGuiJNI.ImGuiContext_HoveredIdPreviousFrame_get(swigCPtr, this);
  }

  public void setHoveredIdTimer(float value) {
    CImGuiJNI.ImGuiContext_HoveredIdTimer_set(swigCPtr, this, value);
  }

  public float getHoveredIdTimer() {
    return CImGuiJNI.ImGuiContext_HoveredIdTimer_get(swigCPtr, this);
  }

  public void setHoveredIdNotActiveTimer(float value) {
    CImGuiJNI.ImGuiContext_HoveredIdNotActiveTimer_set(swigCPtr, this, value);
  }

  public float getHoveredIdNotActiveTimer() {
    return CImGuiJNI.ImGuiContext_HoveredIdNotActiveTimer_get(swigCPtr, this);
  }

  public void setActiveId(long value) {
    CImGuiJNI.ImGuiContext_ActiveId_set(swigCPtr, this, value);
  }

  public long getActiveId() {
    return CImGuiJNI.ImGuiContext_ActiveId_get(swigCPtr, this);
  }

  public void setActiveIdIsAlive(long value) {
    CImGuiJNI.ImGuiContext_ActiveIdIsAlive_set(swigCPtr, this, value);
  }

  public long getActiveIdIsAlive() {
    return CImGuiJNI.ImGuiContext_ActiveIdIsAlive_get(swigCPtr, this);
  }

  public void setActiveIdTimer(float value) {
    CImGuiJNI.ImGuiContext_ActiveIdTimer_set(swigCPtr, this, value);
  }

  public float getActiveIdTimer() {
    return CImGuiJNI.ImGuiContext_ActiveIdTimer_get(swigCPtr, this);
  }

  public void setActiveIdIsJustActivated(boolean value) {
    CImGuiJNI.ImGuiContext_ActiveIdIsJustActivated_set(swigCPtr, this, value);
  }

  public boolean getActiveIdIsJustActivated() {
    return CImGuiJNI.ImGuiContext_ActiveIdIsJustActivated_get(swigCPtr, this);
  }

  public void setActiveIdAllowOverlap(boolean value) {
    CImGuiJNI.ImGuiContext_ActiveIdAllowOverlap_set(swigCPtr, this, value);
  }

  public boolean getActiveIdAllowOverlap() {
    return CImGuiJNI.ImGuiContext_ActiveIdAllowOverlap_get(swigCPtr, this);
  }

  public void setActiveIdHasBeenPressedBefore(boolean value) {
    CImGuiJNI.ImGuiContext_ActiveIdHasBeenPressedBefore_set(swigCPtr, this, value);
  }

  public boolean getActiveIdHasBeenPressedBefore() {
    return CImGuiJNI.ImGuiContext_ActiveIdHasBeenPressedBefore_get(swigCPtr, this);
  }

  public void setActiveIdHasBeenEditedBefore(boolean value) {
    CImGuiJNI.ImGuiContext_ActiveIdHasBeenEditedBefore_set(swigCPtr, this, value);
  }

  public boolean getActiveIdHasBeenEditedBefore() {
    return CImGuiJNI.ImGuiContext_ActiveIdHasBeenEditedBefore_get(swigCPtr, this);
  }

  public void setActiveIdHasBeenEditedThisFrame(boolean value) {
    CImGuiJNI.ImGuiContext_ActiveIdHasBeenEditedThisFrame_set(swigCPtr, this, value);
  }

  public boolean getActiveIdHasBeenEditedThisFrame() {
    return CImGuiJNI.ImGuiContext_ActiveIdHasBeenEditedThisFrame_get(swigCPtr, this);
  }

  public void setActiveIdUsingNavDirMask(long value) {
    CImGuiJNI.ImGuiContext_ActiveIdUsingNavDirMask_set(swigCPtr, this, value);
  }

  public long getActiveIdUsingNavDirMask() {
    return CImGuiJNI.ImGuiContext_ActiveIdUsingNavDirMask_get(swigCPtr, this);
  }

  public void setActiveIdUsingNavInputMask(long value) {
    CImGuiJNI.ImGuiContext_ActiveIdUsingNavInputMask_set(swigCPtr, this, value);
  }

  public long getActiveIdUsingNavInputMask() {
    return CImGuiJNI.ImGuiContext_ActiveIdUsingNavInputMask_get(swigCPtr, this);
  }

  public void setActiveIdUsingKeyInputMask(SWIGTYPE_p_uint64_t value) {
    CImGuiJNI.ImGuiContext_ActiveIdUsingKeyInputMask_set(swigCPtr, this, SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint64_t getActiveIdUsingKeyInputMask() {
    return new SWIGTYPE_p_uint64_t(CImGuiJNI.ImGuiContext_ActiveIdUsingKeyInputMask_get(swigCPtr, this), true);
  }

  public void setActiveIdClickOffset(ImVec2 value) {
    CImGuiJNI.ImGuiContext_ActiveIdClickOffset_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getActiveIdClickOffset() {
    long cPtr = CImGuiJNI.ImGuiContext_ActiveIdClickOffset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setActiveIdWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_ActiveIdWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getActiveIdWindow() {
    long cPtr = CImGuiJNI.ImGuiContext_ActiveIdWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setActiveIdSource(int value) {
    CImGuiJNI.ImGuiContext_ActiveIdSource_set(swigCPtr, this, value);
  }

  public int getActiveIdSource() {
    return CImGuiJNI.ImGuiContext_ActiveIdSource_get(swigCPtr, this);
  }

  public void setActiveIdMouseButton(int value) {
    CImGuiJNI.ImGuiContext_ActiveIdMouseButton_set(swigCPtr, this, value);
  }

  public int getActiveIdMouseButton() {
    return CImGuiJNI.ImGuiContext_ActiveIdMouseButton_get(swigCPtr, this);
  }

  public void setActiveIdPreviousFrame(long value) {
    CImGuiJNI.ImGuiContext_ActiveIdPreviousFrame_set(swigCPtr, this, value);
  }

  public long getActiveIdPreviousFrame() {
    return CImGuiJNI.ImGuiContext_ActiveIdPreviousFrame_get(swigCPtr, this);
  }

  public void setActiveIdPreviousFrameIsAlive(boolean value) {
    CImGuiJNI.ImGuiContext_ActiveIdPreviousFrameIsAlive_set(swigCPtr, this, value);
  }

  public boolean getActiveIdPreviousFrameIsAlive() {
    return CImGuiJNI.ImGuiContext_ActiveIdPreviousFrameIsAlive_get(swigCPtr, this);
  }

  public void setActiveIdPreviousFrameHasBeenEditedBefore(boolean value) {
    CImGuiJNI.ImGuiContext_ActiveIdPreviousFrameHasBeenEditedBefore_set(swigCPtr, this, value);
  }

  public boolean getActiveIdPreviousFrameHasBeenEditedBefore() {
    return CImGuiJNI.ImGuiContext_ActiveIdPreviousFrameHasBeenEditedBefore_get(swigCPtr, this);
  }

  public void setActiveIdPreviousFrameWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_ActiveIdPreviousFrameWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getActiveIdPreviousFrameWindow() {
    long cPtr = CImGuiJNI.ImGuiContext_ActiveIdPreviousFrameWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setLastActiveId(long value) {
    CImGuiJNI.ImGuiContext_LastActiveId_set(swigCPtr, this, value);
  }

  public long getLastActiveId() {
    return CImGuiJNI.ImGuiContext_LastActiveId_get(swigCPtr, this);
  }

  public void setLastActiveIdTimer(float value) {
    CImGuiJNI.ImGuiContext_LastActiveIdTimer_set(swigCPtr, this, value);
  }

  public float getLastActiveIdTimer() {
    return CImGuiJNI.ImGuiContext_LastActiveIdTimer_get(swigCPtr, this);
  }

  public void setNextWindowData(ImGuiNextWindowData value) {
    CImGuiJNI.ImGuiContext_NextWindowData_set(swigCPtr, this, ImGuiNextWindowData.getCPtr(value), value);
  }

  public ImGuiNextWindowData getNextWindowData() {
    long cPtr = CImGuiJNI.ImGuiContext_NextWindowData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiNextWindowData(cPtr, false);
  }

  public void setNextItemData(ImGuiNextItemData value) {
    CImGuiJNI.ImGuiContext_NextItemData_set(swigCPtr, this, ImGuiNextItemData.getCPtr(value), value);
  }

  public ImGuiNextItemData getNextItemData() {
    long cPtr = CImGuiJNI.ImGuiContext_NextItemData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiNextItemData(cPtr, false);
  }

  public void setColorModifiers(ImVector_ImGuiColorMod value) {
    CImGuiJNI.ImGuiContext_ColorModifiers_set(swigCPtr, this, ImVector_ImGuiColorMod.getCPtr(value), value);
  }

  public ImVector_ImGuiColorMod getColorModifiers() {
    long cPtr = CImGuiJNI.ImGuiContext_ColorModifiers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiColorMod(cPtr, false);
  }

  public void setStyleModifiers(ImVector_ImGuiStyleMod value) {
    CImGuiJNI.ImGuiContext_StyleModifiers_set(swigCPtr, this, ImVector_ImGuiStyleMod.getCPtr(value), value);
  }

  public ImVector_ImGuiStyleMod getStyleModifiers() {
    long cPtr = CImGuiJNI.ImGuiContext_StyleModifiers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiStyleMod(cPtr, false);
  }

  public void setFontStack(ImVector_ImFontPtr value) {
    CImGuiJNI.ImGuiContext_FontStack_set(swigCPtr, this, ImVector_ImFontPtr.getCPtr(value), value);
  }

  public ImVector_ImFontPtr getFontStack() {
    long cPtr = CImGuiJNI.ImGuiContext_FontStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImFontPtr(cPtr, false);
  }

  public void setOpenPopupStack(ImVector_ImGuiPopupData value) {
    CImGuiJNI.ImGuiContext_OpenPopupStack_set(swigCPtr, this, ImVector_ImGuiPopupData.getCPtr(value), value);
  }

  public ImVector_ImGuiPopupData getOpenPopupStack() {
    long cPtr = CImGuiJNI.ImGuiContext_OpenPopupStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiPopupData(cPtr, false);
  }

  public void setBeginPopupStack(ImVector_ImGuiPopupData value) {
    CImGuiJNI.ImGuiContext_BeginPopupStack_set(swigCPtr, this, ImVector_ImGuiPopupData.getCPtr(value), value);
  }

  public ImVector_ImGuiPopupData getBeginPopupStack() {
    long cPtr = CImGuiJNI.ImGuiContext_BeginPopupStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiPopupData(cPtr, false);
  }

  public void setNavWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_NavWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getNavWindow() {
    long cPtr = CImGuiJNI.ImGuiContext_NavWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setNavId(long value) {
    CImGuiJNI.ImGuiContext_NavId_set(swigCPtr, this, value);
  }

  public long getNavId() {
    return CImGuiJNI.ImGuiContext_NavId_get(swigCPtr, this);
  }

  public void setNavFocusScopeId(long value) {
    CImGuiJNI.ImGuiContext_NavFocusScopeId_set(swigCPtr, this, value);
  }

  public long getNavFocusScopeId() {
    return CImGuiJNI.ImGuiContext_NavFocusScopeId_get(swigCPtr, this);
  }

  public void setNavActivateId(long value) {
    CImGuiJNI.ImGuiContext_NavActivateId_set(swigCPtr, this, value);
  }

  public long getNavActivateId() {
    return CImGuiJNI.ImGuiContext_NavActivateId_get(swigCPtr, this);
  }

  public void setNavActivateDownId(long value) {
    CImGuiJNI.ImGuiContext_NavActivateDownId_set(swigCPtr, this, value);
  }

  public long getNavActivateDownId() {
    return CImGuiJNI.ImGuiContext_NavActivateDownId_get(swigCPtr, this);
  }

  public void setNavActivatePressedId(long value) {
    CImGuiJNI.ImGuiContext_NavActivatePressedId_set(swigCPtr, this, value);
  }

  public long getNavActivatePressedId() {
    return CImGuiJNI.ImGuiContext_NavActivatePressedId_get(swigCPtr, this);
  }

  public void setNavInputId(long value) {
    CImGuiJNI.ImGuiContext_NavInputId_set(swigCPtr, this, value);
  }

  public long getNavInputId() {
    return CImGuiJNI.ImGuiContext_NavInputId_get(swigCPtr, this);
  }

  public void setNavJustTabbedId(long value) {
    CImGuiJNI.ImGuiContext_NavJustTabbedId_set(swigCPtr, this, value);
  }

  public long getNavJustTabbedId() {
    return CImGuiJNI.ImGuiContext_NavJustTabbedId_get(swigCPtr, this);
  }

  public void setNavJustMovedToId(long value) {
    CImGuiJNI.ImGuiContext_NavJustMovedToId_set(swigCPtr, this, value);
  }

  public long getNavJustMovedToId() {
    return CImGuiJNI.ImGuiContext_NavJustMovedToId_get(swigCPtr, this);
  }

  public void setNavJustMovedToFocusScopeId(long value) {
    CImGuiJNI.ImGuiContext_NavJustMovedToFocusScopeId_set(swigCPtr, this, value);
  }

  public long getNavJustMovedToFocusScopeId() {
    return CImGuiJNI.ImGuiContext_NavJustMovedToFocusScopeId_get(swigCPtr, this);
  }

  public void setNavJustMovedToKeyMods(int value) {
    CImGuiJNI.ImGuiContext_NavJustMovedToKeyMods_set(swigCPtr, this, value);
  }

  public int getNavJustMovedToKeyMods() {
    return CImGuiJNI.ImGuiContext_NavJustMovedToKeyMods_get(swigCPtr, this);
  }

  public void setNavNextActivateId(long value) {
    CImGuiJNI.ImGuiContext_NavNextActivateId_set(swigCPtr, this, value);
  }

  public long getNavNextActivateId() {
    return CImGuiJNI.ImGuiContext_NavNextActivateId_get(swigCPtr, this);
  }

  public void setNavInputSource(int value) {
    CImGuiJNI.ImGuiContext_NavInputSource_set(swigCPtr, this, value);
  }

  public int getNavInputSource() {
    return CImGuiJNI.ImGuiContext_NavInputSource_get(swigCPtr, this);
  }

  public void setNavScoringRect(ImRect value) {
    CImGuiJNI.ImGuiContext_NavScoringRect_set(swigCPtr, this, ImRect.getCPtr(value), value);
  }

  public ImRect getNavScoringRect() {
    long cPtr = CImGuiJNI.ImGuiContext_NavScoringRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImRect(cPtr, false);
  }

  public void setNavScoringCount(int value) {
    CImGuiJNI.ImGuiContext_NavScoringCount_set(swigCPtr, this, value);
  }

  public int getNavScoringCount() {
    return CImGuiJNI.ImGuiContext_NavScoringCount_get(swigCPtr, this);
  }

  public void setNavLayer(int value) {
    CImGuiJNI.ImGuiContext_NavLayer_set(swigCPtr, this, value);
  }

  public int getNavLayer() {
    return CImGuiJNI.ImGuiContext_NavLayer_get(swigCPtr, this);
  }

  public void setNavIdTabCounter(int value) {
    CImGuiJNI.ImGuiContext_NavIdTabCounter_set(swigCPtr, this, value);
  }

  public int getNavIdTabCounter() {
    return CImGuiJNI.ImGuiContext_NavIdTabCounter_get(swigCPtr, this);
  }

  public void setNavIdIsAlive(boolean value) {
    CImGuiJNI.ImGuiContext_NavIdIsAlive_set(swigCPtr, this, value);
  }

  public boolean getNavIdIsAlive() {
    return CImGuiJNI.ImGuiContext_NavIdIsAlive_get(swigCPtr, this);
  }

  public void setNavMousePosDirty(boolean value) {
    CImGuiJNI.ImGuiContext_NavMousePosDirty_set(swigCPtr, this, value);
  }

  public boolean getNavMousePosDirty() {
    return CImGuiJNI.ImGuiContext_NavMousePosDirty_get(swigCPtr, this);
  }

  public void setNavDisableHighlight(boolean value) {
    CImGuiJNI.ImGuiContext_NavDisableHighlight_set(swigCPtr, this, value);
  }

  public boolean getNavDisableHighlight() {
    return CImGuiJNI.ImGuiContext_NavDisableHighlight_get(swigCPtr, this);
  }

  public void setNavDisableMouseHover(boolean value) {
    CImGuiJNI.ImGuiContext_NavDisableMouseHover_set(swigCPtr, this, value);
  }

  public boolean getNavDisableMouseHover() {
    return CImGuiJNI.ImGuiContext_NavDisableMouseHover_get(swigCPtr, this);
  }

  public void setNavAnyRequest(boolean value) {
    CImGuiJNI.ImGuiContext_NavAnyRequest_set(swigCPtr, this, value);
  }

  public boolean getNavAnyRequest() {
    return CImGuiJNI.ImGuiContext_NavAnyRequest_get(swigCPtr, this);
  }

  public void setNavInitRequest(boolean value) {
    CImGuiJNI.ImGuiContext_NavInitRequest_set(swigCPtr, this, value);
  }

  public boolean getNavInitRequest() {
    return CImGuiJNI.ImGuiContext_NavInitRequest_get(swigCPtr, this);
  }

  public void setNavInitRequestFromMove(boolean value) {
    CImGuiJNI.ImGuiContext_NavInitRequestFromMove_set(swigCPtr, this, value);
  }

  public boolean getNavInitRequestFromMove() {
    return CImGuiJNI.ImGuiContext_NavInitRequestFromMove_get(swigCPtr, this);
  }

  public void setNavInitResultId(long value) {
    CImGuiJNI.ImGuiContext_NavInitResultId_set(swigCPtr, this, value);
  }

  public long getNavInitResultId() {
    return CImGuiJNI.ImGuiContext_NavInitResultId_get(swigCPtr, this);
  }

  public void setNavInitResultRectRel(ImRect value) {
    CImGuiJNI.ImGuiContext_NavInitResultRectRel_set(swigCPtr, this, ImRect.getCPtr(value), value);
  }

  public ImRect getNavInitResultRectRel() {
    long cPtr = CImGuiJNI.ImGuiContext_NavInitResultRectRel_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImRect(cPtr, false);
  }

  public void setNavMoveFromClampedRefRect(boolean value) {
    CImGuiJNI.ImGuiContext_NavMoveFromClampedRefRect_set(swigCPtr, this, value);
  }

  public boolean getNavMoveFromClampedRefRect() {
    return CImGuiJNI.ImGuiContext_NavMoveFromClampedRefRect_get(swigCPtr, this);
  }

  public void setNavMoveRequest(boolean value) {
    CImGuiJNI.ImGuiContext_NavMoveRequest_set(swigCPtr, this, value);
  }

  public boolean getNavMoveRequest() {
    return CImGuiJNI.ImGuiContext_NavMoveRequest_get(swigCPtr, this);
  }

  public void setNavMoveRequestFlags(int value) {
    CImGuiJNI.ImGuiContext_NavMoveRequestFlags_set(swigCPtr, this, value);
  }

  public int getNavMoveRequestFlags() {
    return CImGuiJNI.ImGuiContext_NavMoveRequestFlags_get(swigCPtr, this);
  }

  public void setNavMoveRequestForward(int value) {
    CImGuiJNI.ImGuiContext_NavMoveRequestForward_set(swigCPtr, this, value);
  }

  public int getNavMoveRequestForward() {
    return CImGuiJNI.ImGuiContext_NavMoveRequestForward_get(swigCPtr, this);
  }

  public void setNavMoveRequestKeyMods(int value) {
    CImGuiJNI.ImGuiContext_NavMoveRequestKeyMods_set(swigCPtr, this, value);
  }

  public int getNavMoveRequestKeyMods() {
    return CImGuiJNI.ImGuiContext_NavMoveRequestKeyMods_get(swigCPtr, this);
  }

  public void setNavMoveDir(int value) {
    CImGuiJNI.ImGuiContext_NavMoveDir_set(swigCPtr, this, value);
  }

  public int getNavMoveDir() {
    return CImGuiJNI.ImGuiContext_NavMoveDir_get(swigCPtr, this);
  }

  public void setNavMoveDirLast(int value) {
    CImGuiJNI.ImGuiContext_NavMoveDirLast_set(swigCPtr, this, value);
  }

  public int getNavMoveDirLast() {
    return CImGuiJNI.ImGuiContext_NavMoveDirLast_get(swigCPtr, this);
  }

  public void setNavMoveClipDir(int value) {
    CImGuiJNI.ImGuiContext_NavMoveClipDir_set(swigCPtr, this, value);
  }

  public int getNavMoveClipDir() {
    return CImGuiJNI.ImGuiContext_NavMoveClipDir_get(swigCPtr, this);
  }

  public void setNavMoveResultLocal(ImGuiNavMoveResult value) {
    CImGuiJNI.ImGuiContext_NavMoveResultLocal_set(swigCPtr, this, ImGuiNavMoveResult.getCPtr(value), value);
  }

  public ImGuiNavMoveResult getNavMoveResultLocal() {
    long cPtr = CImGuiJNI.ImGuiContext_NavMoveResultLocal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiNavMoveResult(cPtr, false);
  }

  public void setNavMoveResultLocalVisibleSet(ImGuiNavMoveResult value) {
    CImGuiJNI.ImGuiContext_NavMoveResultLocalVisibleSet_set(swigCPtr, this, ImGuiNavMoveResult.getCPtr(value), value);
  }

  public ImGuiNavMoveResult getNavMoveResultLocalVisibleSet() {
    long cPtr = CImGuiJNI.ImGuiContext_NavMoveResultLocalVisibleSet_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiNavMoveResult(cPtr, false);
  }

  public void setNavMoveResultOther(ImGuiNavMoveResult value) {
    CImGuiJNI.ImGuiContext_NavMoveResultOther_set(swigCPtr, this, ImGuiNavMoveResult.getCPtr(value), value);
  }

  public ImGuiNavMoveResult getNavMoveResultOther() {
    long cPtr = CImGuiJNI.ImGuiContext_NavMoveResultOther_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiNavMoveResult(cPtr, false);
  }

  public void setNavWrapRequestWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_NavWrapRequestWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getNavWrapRequestWindow() {
    long cPtr = CImGuiJNI.ImGuiContext_NavWrapRequestWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setNavWrapRequestFlags(int value) {
    CImGuiJNI.ImGuiContext_NavWrapRequestFlags_set(swigCPtr, this, value);
  }

  public int getNavWrapRequestFlags() {
    return CImGuiJNI.ImGuiContext_NavWrapRequestFlags_get(swigCPtr, this);
  }

  public void setNavWindowingTarget(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_NavWindowingTarget_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getNavWindowingTarget() {
    long cPtr = CImGuiJNI.ImGuiContext_NavWindowingTarget_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setNavWindowingTargetAnim(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_NavWindowingTargetAnim_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getNavWindowingTargetAnim() {
    long cPtr = CImGuiJNI.ImGuiContext_NavWindowingTargetAnim_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setNavWindowingListWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_NavWindowingListWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getNavWindowingListWindow() {
    long cPtr = CImGuiJNI.ImGuiContext_NavWindowingListWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setNavWindowingTimer(float value) {
    CImGuiJNI.ImGuiContext_NavWindowingTimer_set(swigCPtr, this, value);
  }

  public float getNavWindowingTimer() {
    return CImGuiJNI.ImGuiContext_NavWindowingTimer_get(swigCPtr, this);
  }

  public void setNavWindowingHighlightAlpha(float value) {
    CImGuiJNI.ImGuiContext_NavWindowingHighlightAlpha_set(swigCPtr, this, value);
  }

  public float getNavWindowingHighlightAlpha() {
    return CImGuiJNI.ImGuiContext_NavWindowingHighlightAlpha_get(swigCPtr, this);
  }

  public void setNavWindowingToggleLayer(boolean value) {
    CImGuiJNI.ImGuiContext_NavWindowingToggleLayer_set(swigCPtr, this, value);
  }

  public boolean getNavWindowingToggleLayer() {
    return CImGuiJNI.ImGuiContext_NavWindowingToggleLayer_get(swigCPtr, this);
  }

  public void setFocusRequestCurrWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_FocusRequestCurrWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getFocusRequestCurrWindow() {
    long cPtr = CImGuiJNI.ImGuiContext_FocusRequestCurrWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setFocusRequestNextWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiContext_FocusRequestNextWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getFocusRequestNextWindow() {
    long cPtr = CImGuiJNI.ImGuiContext_FocusRequestNextWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setFocusRequestCurrCounterRegular(int value) {
    CImGuiJNI.ImGuiContext_FocusRequestCurrCounterRegular_set(swigCPtr, this, value);
  }

  public int getFocusRequestCurrCounterRegular() {
    return CImGuiJNI.ImGuiContext_FocusRequestCurrCounterRegular_get(swigCPtr, this);
  }

  public void setFocusRequestCurrCounterTabStop(int value) {
    CImGuiJNI.ImGuiContext_FocusRequestCurrCounterTabStop_set(swigCPtr, this, value);
  }

  public int getFocusRequestCurrCounterTabStop() {
    return CImGuiJNI.ImGuiContext_FocusRequestCurrCounterTabStop_get(swigCPtr, this);
  }

  public void setFocusRequestNextCounterRegular(int value) {
    CImGuiJNI.ImGuiContext_FocusRequestNextCounterRegular_set(swigCPtr, this, value);
  }

  public int getFocusRequestNextCounterRegular() {
    return CImGuiJNI.ImGuiContext_FocusRequestNextCounterRegular_get(swigCPtr, this);
  }

  public void setFocusRequestNextCounterTabStop(int value) {
    CImGuiJNI.ImGuiContext_FocusRequestNextCounterTabStop_set(swigCPtr, this, value);
  }

  public int getFocusRequestNextCounterTabStop() {
    return CImGuiJNI.ImGuiContext_FocusRequestNextCounterTabStop_get(swigCPtr, this);
  }

  public void setFocusTabPressed(boolean value) {
    CImGuiJNI.ImGuiContext_FocusTabPressed_set(swigCPtr, this, value);
  }

  public boolean getFocusTabPressed() {
    return CImGuiJNI.ImGuiContext_FocusTabPressed_get(swigCPtr, this);
  }

  public void setDrawData(ImDrawData value) {
    CImGuiJNI.ImGuiContext_DrawData_set(swigCPtr, this, ImDrawData.getCPtr(value), value);
  }

  public ImDrawData getDrawData() {
    long cPtr = CImGuiJNI.ImGuiContext_DrawData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawData(cPtr, false);
  }

  public void setDrawDataBuilder(ImDrawDataBuilder value) {
    CImGuiJNI.ImGuiContext_DrawDataBuilder_set(swigCPtr, this, ImDrawDataBuilder.getCPtr(value), value);
  }

  public ImDrawDataBuilder getDrawDataBuilder() {
    long cPtr = CImGuiJNI.ImGuiContext_DrawDataBuilder_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawDataBuilder(cPtr, false);
  }

  public void setDimBgRatio(float value) {
    CImGuiJNI.ImGuiContext_DimBgRatio_set(swigCPtr, this, value);
  }

  public float getDimBgRatio() {
    return CImGuiJNI.ImGuiContext_DimBgRatio_get(swigCPtr, this);
  }

  public void setBackgroundDrawList(ImDrawList value) {
    CImGuiJNI.ImGuiContext_BackgroundDrawList_set(swigCPtr, this, ImDrawList.getCPtr(value), value);
  }

  public ImDrawList getBackgroundDrawList() {
    long cPtr = CImGuiJNI.ImGuiContext_BackgroundDrawList_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawList(cPtr, false);
  }

  public void setForegroundDrawList(ImDrawList value) {
    CImGuiJNI.ImGuiContext_ForegroundDrawList_set(swigCPtr, this, ImDrawList.getCPtr(value), value);
  }

  public ImDrawList getForegroundDrawList() {
    long cPtr = CImGuiJNI.ImGuiContext_ForegroundDrawList_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawList(cPtr, false);
  }

  public void setMouseCursor(int value) {
    CImGuiJNI.ImGuiContext_MouseCursor_set(swigCPtr, this, value);
  }

  public int getMouseCursor() {
    return CImGuiJNI.ImGuiContext_MouseCursor_get(swigCPtr, this);
  }

  public void setDragDropActive(boolean value) {
    CImGuiJNI.ImGuiContext_DragDropActive_set(swigCPtr, this, value);
  }

  public boolean getDragDropActive() {
    return CImGuiJNI.ImGuiContext_DragDropActive_get(swigCPtr, this);
  }

  public void setDragDropWithinSource(boolean value) {
    CImGuiJNI.ImGuiContext_DragDropWithinSource_set(swigCPtr, this, value);
  }

  public boolean getDragDropWithinSource() {
    return CImGuiJNI.ImGuiContext_DragDropWithinSource_get(swigCPtr, this);
  }

  public void setDragDropWithinTarget(boolean value) {
    CImGuiJNI.ImGuiContext_DragDropWithinTarget_set(swigCPtr, this, value);
  }

  public boolean getDragDropWithinTarget() {
    return CImGuiJNI.ImGuiContext_DragDropWithinTarget_get(swigCPtr, this);
  }

  public void setDragDropSourceFlags(int value) {
    CImGuiJNI.ImGuiContext_DragDropSourceFlags_set(swigCPtr, this, value);
  }

  public int getDragDropSourceFlags() {
    return CImGuiJNI.ImGuiContext_DragDropSourceFlags_get(swigCPtr, this);
  }

  public void setDragDropSourceFrameCount(int value) {
    CImGuiJNI.ImGuiContext_DragDropSourceFrameCount_set(swigCPtr, this, value);
  }

  public int getDragDropSourceFrameCount() {
    return CImGuiJNI.ImGuiContext_DragDropSourceFrameCount_get(swigCPtr, this);
  }

  public void setDragDropMouseButton(int value) {
    CImGuiJNI.ImGuiContext_DragDropMouseButton_set(swigCPtr, this, value);
  }

  public int getDragDropMouseButton() {
    return CImGuiJNI.ImGuiContext_DragDropMouseButton_get(swigCPtr, this);
  }

  public void setDragDropPayload(ImGuiPayload value) {
    CImGuiJNI.ImGuiContext_DragDropPayload_set(swigCPtr, this, ImGuiPayload.getCPtr(value), value);
  }

  public ImGuiPayload getDragDropPayload() {
    long cPtr = CImGuiJNI.ImGuiContext_DragDropPayload_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiPayload(cPtr, false);
  }

  public void setDragDropTargetRect(ImRect value) {
    CImGuiJNI.ImGuiContext_DragDropTargetRect_set(swigCPtr, this, ImRect.getCPtr(value), value);
  }

  public ImRect getDragDropTargetRect() {
    long cPtr = CImGuiJNI.ImGuiContext_DragDropTargetRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImRect(cPtr, false);
  }

  public void setDragDropTargetId(long value) {
    CImGuiJNI.ImGuiContext_DragDropTargetId_set(swigCPtr, this, value);
  }

  public long getDragDropTargetId() {
    return CImGuiJNI.ImGuiContext_DragDropTargetId_get(swigCPtr, this);
  }

  public void setDragDropAcceptFlags(int value) {
    CImGuiJNI.ImGuiContext_DragDropAcceptFlags_set(swigCPtr, this, value);
  }

  public int getDragDropAcceptFlags() {
    return CImGuiJNI.ImGuiContext_DragDropAcceptFlags_get(swigCPtr, this);
  }

  public void setDragDropAcceptIdCurrRectSurface(float value) {
    CImGuiJNI.ImGuiContext_DragDropAcceptIdCurrRectSurface_set(swigCPtr, this, value);
  }

  public float getDragDropAcceptIdCurrRectSurface() {
    return CImGuiJNI.ImGuiContext_DragDropAcceptIdCurrRectSurface_get(swigCPtr, this);
  }

  public void setDragDropAcceptIdCurr(long value) {
    CImGuiJNI.ImGuiContext_DragDropAcceptIdCurr_set(swigCPtr, this, value);
  }

  public long getDragDropAcceptIdCurr() {
    return CImGuiJNI.ImGuiContext_DragDropAcceptIdCurr_get(swigCPtr, this);
  }

  public void setDragDropAcceptIdPrev(long value) {
    CImGuiJNI.ImGuiContext_DragDropAcceptIdPrev_set(swigCPtr, this, value);
  }

  public long getDragDropAcceptIdPrev() {
    return CImGuiJNI.ImGuiContext_DragDropAcceptIdPrev_get(swigCPtr, this);
  }

  public void setDragDropAcceptFrameCount(int value) {
    CImGuiJNI.ImGuiContext_DragDropAcceptFrameCount_set(swigCPtr, this, value);
  }

  public int getDragDropAcceptFrameCount() {
    return CImGuiJNI.ImGuiContext_DragDropAcceptFrameCount_get(swigCPtr, this);
  }

  public void setDragDropHoldJustPressedId(long value) {
    CImGuiJNI.ImGuiContext_DragDropHoldJustPressedId_set(swigCPtr, this, value);
  }

  public long getDragDropHoldJustPressedId() {
    return CImGuiJNI.ImGuiContext_DragDropHoldJustPressedId_get(swigCPtr, this);
  }

  public void setDragDropPayloadBufHeap(ImVector_unsigned_char value) {
    CImGuiJNI.ImGuiContext_DragDropPayloadBufHeap_set(swigCPtr, this, ImVector_unsigned_char.getCPtr(value), value);
  }

  public ImVector_unsigned_char getDragDropPayloadBufHeap() {
    long cPtr = CImGuiJNI.ImGuiContext_DragDropPayloadBufHeap_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_unsigned_char(cPtr, false);
  }

  public void setDragDropPayloadBufLocal(SWIGTYPE_p_unsigned_char value) {
    CImGuiJNI.ImGuiContext_DragDropPayloadBufLocal_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getDragDropPayloadBufLocal() {
    long cPtr = CImGuiJNI.ImGuiContext_DragDropPayloadBufLocal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setCurrentTabBar(ImGuiTabBar value) {
    CImGuiJNI.ImGuiContext_CurrentTabBar_set(swigCPtr, this, ImGuiTabBar.getCPtr(value), value);
  }

  public ImGuiTabBar getCurrentTabBar() {
    long cPtr = CImGuiJNI.ImGuiContext_CurrentTabBar_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiTabBar(cPtr, false);
  }

  public void setTabBars(ImPool_ImGuiTabBar value) {
    CImGuiJNI.ImGuiContext_TabBars_set(swigCPtr, this, ImPool_ImGuiTabBar.getCPtr(value), value);
  }

  public ImPool_ImGuiTabBar getTabBars() {
    long cPtr = CImGuiJNI.ImGuiContext_TabBars_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImPool_ImGuiTabBar(cPtr, false);
  }

  public void setCurrentTabBarStack(ImVector_ImGuiPtrOrIndex value) {
    CImGuiJNI.ImGuiContext_CurrentTabBarStack_set(swigCPtr, this, ImVector_ImGuiPtrOrIndex.getCPtr(value), value);
  }

  public ImVector_ImGuiPtrOrIndex getCurrentTabBarStack() {
    long cPtr = CImGuiJNI.ImGuiContext_CurrentTabBarStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiPtrOrIndex(cPtr, false);
  }

  public void setShrinkWidthBuffer(ImVector_ImGuiShrinkWidthItem value) {
    CImGuiJNI.ImGuiContext_ShrinkWidthBuffer_set(swigCPtr, this, ImVector_ImGuiShrinkWidthItem.getCPtr(value), value);
  }

  public ImVector_ImGuiShrinkWidthItem getShrinkWidthBuffer() {
    long cPtr = CImGuiJNI.ImGuiContext_ShrinkWidthBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiShrinkWidthItem(cPtr, false);
  }

  public void setLastValidMousePos(ImVec2 value) {
    CImGuiJNI.ImGuiContext_LastValidMousePos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getLastValidMousePos() {
    long cPtr = CImGuiJNI.ImGuiContext_LastValidMousePos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setInputTextState(ImGuiInputTextState value) {
    CImGuiJNI.ImGuiContext_InputTextState_set(swigCPtr, this, ImGuiInputTextState.getCPtr(value), value);
  }

  public ImGuiInputTextState getInputTextState() {
    long cPtr = CImGuiJNI.ImGuiContext_InputTextState_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiInputTextState(cPtr, false);
  }

  public void setInputTextPasswordFont(ImFont value) {
    CImGuiJNI.ImGuiContext_InputTextPasswordFont_set(swigCPtr, this, ImFont.getCPtr(value), value);
  }

  public ImFont getInputTextPasswordFont() {
    long cPtr = CImGuiJNI.ImGuiContext_InputTextPasswordFont_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImFont(cPtr, false);
  }

  public void setTempInputId(long value) {
    CImGuiJNI.ImGuiContext_TempInputId_set(swigCPtr, this, value);
  }

  public long getTempInputId() {
    return CImGuiJNI.ImGuiContext_TempInputId_get(swigCPtr, this);
  }

  public void setColorEditOptions(int value) {
    CImGuiJNI.ImGuiContext_ColorEditOptions_set(swigCPtr, this, value);
  }

  public int getColorEditOptions() {
    return CImGuiJNI.ImGuiContext_ColorEditOptions_get(swigCPtr, this);
  }

  public void setColorEditLastHue(float value) {
    CImGuiJNI.ImGuiContext_ColorEditLastHue_set(swigCPtr, this, value);
  }

  public float getColorEditLastHue() {
    return CImGuiJNI.ImGuiContext_ColorEditLastHue_get(swigCPtr, this);
  }

  public void setColorEditLastSat(float value) {
    CImGuiJNI.ImGuiContext_ColorEditLastSat_set(swigCPtr, this, value);
  }

  public float getColorEditLastSat() {
    return CImGuiJNI.ImGuiContext_ColorEditLastSat_get(swigCPtr, this);
  }

  public void setColorEditLastColor(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiContext_ColorEditLastColor_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getColorEditLastColor() {
    long cPtr = CImGuiJNI.ImGuiContext_ColorEditLastColor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setColorPickerRef(ImVec4 value) {
    CImGuiJNI.ImGuiContext_ColorPickerRef_set(swigCPtr, this, ImVec4.getCPtr(value), value);
  }

  public ImVec4 getColorPickerRef() {
    long cPtr = CImGuiJNI.ImGuiContext_ColorPickerRef_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec4(cPtr, false);
  }

  public void setDragCurrentAccumDirty(boolean value) {
    CImGuiJNI.ImGuiContext_DragCurrentAccumDirty_set(swigCPtr, this, value);
  }

  public boolean getDragCurrentAccumDirty() {
    return CImGuiJNI.ImGuiContext_DragCurrentAccumDirty_get(swigCPtr, this);
  }

  public void setDragCurrentAccum(float value) {
    CImGuiJNI.ImGuiContext_DragCurrentAccum_set(swigCPtr, this, value);
  }

  public float getDragCurrentAccum() {
    return CImGuiJNI.ImGuiContext_DragCurrentAccum_get(swigCPtr, this);
  }

  public void setDragSpeedDefaultRatio(float value) {
    CImGuiJNI.ImGuiContext_DragSpeedDefaultRatio_set(swigCPtr, this, value);
  }

  public float getDragSpeedDefaultRatio() {
    return CImGuiJNI.ImGuiContext_DragSpeedDefaultRatio_get(swigCPtr, this);
  }

  public void setScrollbarClickDeltaToGrabCenter(float value) {
    CImGuiJNI.ImGuiContext_ScrollbarClickDeltaToGrabCenter_set(swigCPtr, this, value);
  }

  public float getScrollbarClickDeltaToGrabCenter() {
    return CImGuiJNI.ImGuiContext_ScrollbarClickDeltaToGrabCenter_get(swigCPtr, this);
  }

  public void setTooltipOverrideCount(int value) {
    CImGuiJNI.ImGuiContext_TooltipOverrideCount_set(swigCPtr, this, value);
  }

  public int getTooltipOverrideCount() {
    return CImGuiJNI.ImGuiContext_TooltipOverrideCount_get(swigCPtr, this);
  }

  public void setClipboardHandlerData(ImVector_char value) {
    CImGuiJNI.ImGuiContext_ClipboardHandlerData_set(swigCPtr, this, ImVector_char.getCPtr(value), value);
  }

  public ImVector_char getClipboardHandlerData() {
    long cPtr = CImGuiJNI.ImGuiContext_ClipboardHandlerData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_char(cPtr, false);
  }

  public void setMenusIdSubmittedThisFrame(ImVector_ImGuiID value) {
    CImGuiJNI.ImGuiContext_MenusIdSubmittedThisFrame_set(swigCPtr, this, ImVector_ImGuiID.getCPtr(value), value);
  }

  public ImVector_ImGuiID getMenusIdSubmittedThisFrame() {
    long cPtr = CImGuiJNI.ImGuiContext_MenusIdSubmittedThisFrame_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiID(cPtr, false);
  }

  public void setPlatformImePos(ImVec2 value) {
    CImGuiJNI.ImGuiContext_PlatformImePos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getPlatformImePos() {
    long cPtr = CImGuiJNI.ImGuiContext_PlatformImePos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setPlatformImeLastPos(ImVec2 value) {
    CImGuiJNI.ImGuiContext_PlatformImeLastPos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getPlatformImeLastPos() {
    long cPtr = CImGuiJNI.ImGuiContext_PlatformImeLastPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setSettingsLoaded(boolean value) {
    CImGuiJNI.ImGuiContext_SettingsLoaded_set(swigCPtr, this, value);
  }

  public boolean getSettingsLoaded() {
    return CImGuiJNI.ImGuiContext_SettingsLoaded_get(swigCPtr, this);
  }

  public void setSettingsDirtyTimer(float value) {
    CImGuiJNI.ImGuiContext_SettingsDirtyTimer_set(swigCPtr, this, value);
  }

  public float getSettingsDirtyTimer() {
    return CImGuiJNI.ImGuiContext_SettingsDirtyTimer_get(swigCPtr, this);
  }

  public void setSettingsIniData(ImGuiTextBuffer value) {
    CImGuiJNI.ImGuiContext_SettingsIniData_set(swigCPtr, this, ImGuiTextBuffer.getCPtr(value), value);
  }

  public ImGuiTextBuffer getSettingsIniData() {
    long cPtr = CImGuiJNI.ImGuiContext_SettingsIniData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiTextBuffer(cPtr, false);
  }

  public void setSettingsHandlers(ImVector_ImGuiSettingsHandler value) {
    CImGuiJNI.ImGuiContext_SettingsHandlers_set(swigCPtr, this, ImVector_ImGuiSettingsHandler.getCPtr(value), value);
  }

  public ImVector_ImGuiSettingsHandler getSettingsHandlers() {
    long cPtr = CImGuiJNI.ImGuiContext_SettingsHandlers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiSettingsHandler(cPtr, false);
  }

  public void setSettingsWindows(ImChunkStream_ImGuiWindowSettings value) {
    CImGuiJNI.ImGuiContext_SettingsWindows_set(swigCPtr, this, ImChunkStream_ImGuiWindowSettings.getCPtr(value), value);
  }

  public ImChunkStream_ImGuiWindowSettings getSettingsWindows() {
    long cPtr = CImGuiJNI.ImGuiContext_SettingsWindows_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImChunkStream_ImGuiWindowSettings(cPtr, false);
  }

  public void setLogEnabled(boolean value) {
    CImGuiJNI.ImGuiContext_LogEnabled_set(swigCPtr, this, value);
  }

  public boolean getLogEnabled() {
    return CImGuiJNI.ImGuiContext_LogEnabled_get(swigCPtr, this);
  }

  public void setLogType(int value) {
    CImGuiJNI.ImGuiContext_LogType_set(swigCPtr, this, value);
  }

  public int getLogType() {
    return CImGuiJNI.ImGuiContext_LogType_get(swigCPtr, this);
  }

  public void setLogFile(SWIGTYPE_p_FILE value) {
    CImGuiJNI.ImGuiContext_LogFile_set(swigCPtr, this, SWIGTYPE_p_FILE.getCPtr(value));
  }

  public SWIGTYPE_p_FILE getLogFile() {
    long cPtr = CImGuiJNI.ImGuiContext_LogFile_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public void setLogBuffer(ImGuiTextBuffer value) {
    CImGuiJNI.ImGuiContext_LogBuffer_set(swigCPtr, this, ImGuiTextBuffer.getCPtr(value), value);
  }

  public ImGuiTextBuffer getLogBuffer() {
    long cPtr = CImGuiJNI.ImGuiContext_LogBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiTextBuffer(cPtr, false);
  }

  public void setLogLinePosY(float value) {
    CImGuiJNI.ImGuiContext_LogLinePosY_set(swigCPtr, this, value);
  }

  public float getLogLinePosY() {
    return CImGuiJNI.ImGuiContext_LogLinePosY_get(swigCPtr, this);
  }

  public void setLogLineFirstItem(boolean value) {
    CImGuiJNI.ImGuiContext_LogLineFirstItem_set(swigCPtr, this, value);
  }

  public boolean getLogLineFirstItem() {
    return CImGuiJNI.ImGuiContext_LogLineFirstItem_get(swigCPtr, this);
  }

  public void setLogDepthRef(int value) {
    CImGuiJNI.ImGuiContext_LogDepthRef_set(swigCPtr, this, value);
  }

  public int getLogDepthRef() {
    return CImGuiJNI.ImGuiContext_LogDepthRef_get(swigCPtr, this);
  }

  public void setLogDepthToExpand(int value) {
    CImGuiJNI.ImGuiContext_LogDepthToExpand_set(swigCPtr, this, value);
  }

  public int getLogDepthToExpand() {
    return CImGuiJNI.ImGuiContext_LogDepthToExpand_get(swigCPtr, this);
  }

  public void setLogDepthToExpandDefault(int value) {
    CImGuiJNI.ImGuiContext_LogDepthToExpandDefault_set(swigCPtr, this, value);
  }

  public int getLogDepthToExpandDefault() {
    return CImGuiJNI.ImGuiContext_LogDepthToExpandDefault_get(swigCPtr, this);
  }

  public void setDebugItemPickerActive(boolean value) {
    CImGuiJNI.ImGuiContext_DebugItemPickerActive_set(swigCPtr, this, value);
  }

  public boolean getDebugItemPickerActive() {
    return CImGuiJNI.ImGuiContext_DebugItemPickerActive_get(swigCPtr, this);
  }

  public void setDebugItemPickerBreakId(long value) {
    CImGuiJNI.ImGuiContext_DebugItemPickerBreakId_set(swigCPtr, this, value);
  }

  public long getDebugItemPickerBreakId() {
    return CImGuiJNI.ImGuiContext_DebugItemPickerBreakId_get(swigCPtr, this);
  }

  public void setFramerateSecPerFrame(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiContext_FramerateSecPerFrame_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getFramerateSecPerFrame() {
    long cPtr = CImGuiJNI.ImGuiContext_FramerateSecPerFrame_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setFramerateSecPerFrameIdx(int value) {
    CImGuiJNI.ImGuiContext_FramerateSecPerFrameIdx_set(swigCPtr, this, value);
  }

  public int getFramerateSecPerFrameIdx() {
    return CImGuiJNI.ImGuiContext_FramerateSecPerFrameIdx_get(swigCPtr, this);
  }

  public void setFramerateSecPerFrameAccum(float value) {
    CImGuiJNI.ImGuiContext_FramerateSecPerFrameAccum_set(swigCPtr, this, value);
  }

  public float getFramerateSecPerFrameAccum() {
    return CImGuiJNI.ImGuiContext_FramerateSecPerFrameAccum_get(swigCPtr, this);
  }

  public void setWantCaptureMouseNextFrame(int value) {
    CImGuiJNI.ImGuiContext_WantCaptureMouseNextFrame_set(swigCPtr, this, value);
  }

  public int getWantCaptureMouseNextFrame() {
    return CImGuiJNI.ImGuiContext_WantCaptureMouseNextFrame_get(swigCPtr, this);
  }

  public void setWantCaptureKeyboardNextFrame(int value) {
    CImGuiJNI.ImGuiContext_WantCaptureKeyboardNextFrame_set(swigCPtr, this, value);
  }

  public int getWantCaptureKeyboardNextFrame() {
    return CImGuiJNI.ImGuiContext_WantCaptureKeyboardNextFrame_get(swigCPtr, this);
  }

  public void setWantTextInputNextFrame(int value) {
    CImGuiJNI.ImGuiContext_WantTextInputNextFrame_set(swigCPtr, this, value);
  }

  public int getWantTextInputNextFrame() {
    return CImGuiJNI.ImGuiContext_WantTextInputNextFrame_get(swigCPtr, this);
  }

  public void setTempBuffer(String value) {
    CImGuiJNI.ImGuiContext_TempBuffer_set(swigCPtr, this, value);
  }

  public String getTempBuffer() {
    return CImGuiJNI.ImGuiContext_TempBuffer_get(swigCPtr, this);
  }

  public ImGuiContext() {
    this(CImGuiJNI.new_ImGuiContext(), true);
  }

}
