/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiCol_ {
  public final static int ImGuiCol_Text = 0;
  public final static int ImGuiCol_TextDisabled = ImGuiCol_Text + 1;
  public final static int ImGuiCol_WindowBg = ImGuiCol_TextDisabled + 1;
  public final static int ImGuiCol_ChildBg = ImGuiCol_WindowBg + 1;
  public final static int ImGuiCol_PopupBg = ImGuiCol_ChildBg + 1;
  public final static int ImGuiCol_Border = ImGuiCol_PopupBg + 1;
  public final static int ImGuiCol_BorderShadow = ImGuiCol_Border + 1;
  public final static int ImGuiCol_FrameBg = ImGuiCol_BorderShadow + 1;
  public final static int ImGuiCol_FrameBgHovered = ImGuiCol_FrameBg + 1;
  public final static int ImGuiCol_FrameBgActive = ImGuiCol_FrameBgHovered + 1;
  public final static int ImGuiCol_TitleBg = ImGuiCol_FrameBgActive + 1;
  public final static int ImGuiCol_TitleBgActive = ImGuiCol_TitleBg + 1;
  public final static int ImGuiCol_TitleBgCollapsed = ImGuiCol_TitleBgActive + 1;
  public final static int ImGuiCol_MenuBarBg = ImGuiCol_TitleBgCollapsed + 1;
  public final static int ImGuiCol_ScrollbarBg = ImGuiCol_MenuBarBg + 1;
  public final static int ImGuiCol_ScrollbarGrab = ImGuiCol_ScrollbarBg + 1;
  public final static int ImGuiCol_ScrollbarGrabHovered = ImGuiCol_ScrollbarGrab + 1;
  public final static int ImGuiCol_ScrollbarGrabActive = ImGuiCol_ScrollbarGrabHovered + 1;
  public final static int ImGuiCol_CheckMark = ImGuiCol_ScrollbarGrabActive + 1;
  public final static int ImGuiCol_SliderGrab = ImGuiCol_CheckMark + 1;
  public final static int ImGuiCol_SliderGrabActive = ImGuiCol_SliderGrab + 1;
  public final static int ImGuiCol_Button = ImGuiCol_SliderGrabActive + 1;
  public final static int ImGuiCol_ButtonHovered = ImGuiCol_Button + 1;
  public final static int ImGuiCol_ButtonActive = ImGuiCol_ButtonHovered + 1;
  public final static int ImGuiCol_Header = ImGuiCol_ButtonActive + 1;
  public final static int ImGuiCol_HeaderHovered = ImGuiCol_Header + 1;
  public final static int ImGuiCol_HeaderActive = ImGuiCol_HeaderHovered + 1;
  public final static int ImGuiCol_Separator = ImGuiCol_HeaderActive + 1;
  public final static int ImGuiCol_SeparatorHovered = ImGuiCol_Separator + 1;
  public final static int ImGuiCol_SeparatorActive = ImGuiCol_SeparatorHovered + 1;
  public final static int ImGuiCol_ResizeGrip = ImGuiCol_SeparatorActive + 1;
  public final static int ImGuiCol_ResizeGripHovered = ImGuiCol_ResizeGrip + 1;
  public final static int ImGuiCol_ResizeGripActive = ImGuiCol_ResizeGripHovered + 1;
  public final static int ImGuiCol_Tab = ImGuiCol_ResizeGripActive + 1;
  public final static int ImGuiCol_TabHovered = ImGuiCol_Tab + 1;
  public final static int ImGuiCol_TabActive = ImGuiCol_TabHovered + 1;
  public final static int ImGuiCol_TabUnfocused = ImGuiCol_TabActive + 1;
  public final static int ImGuiCol_TabUnfocusedActive = ImGuiCol_TabUnfocused + 1;
  public final static int ImGuiCol_PlotLines = ImGuiCol_TabUnfocusedActive + 1;
  public final static int ImGuiCol_PlotLinesHovered = ImGuiCol_PlotLines + 1;
  public final static int ImGuiCol_PlotHistogram = ImGuiCol_PlotLinesHovered + 1;
  public final static int ImGuiCol_PlotHistogramHovered = ImGuiCol_PlotHistogram + 1;
  public final static int ImGuiCol_TextSelectedBg = ImGuiCol_PlotHistogramHovered + 1;
  public final static int ImGuiCol_DragDropTarget = ImGuiCol_TextSelectedBg + 1;
  public final static int ImGuiCol_NavHighlight = ImGuiCol_DragDropTarget + 1;
  public final static int ImGuiCol_NavWindowingHighlight = ImGuiCol_NavHighlight + 1;
  public final static int ImGuiCol_NavWindowingDimBg = ImGuiCol_NavWindowingHighlight + 1;
  public final static int ImGuiCol_ModalWindowDimBg = ImGuiCol_NavWindowingDimBg + 1;
  public final static int ImGuiCol_COUNT = ImGuiCol_ModalWindowDimBg + 1;
}

