/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiMenuColumns {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiMenuColumns(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiMenuColumns obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiMenuColumns(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSpacing(float value) {
    CImGuiJNI.ImGuiMenuColumns_Spacing_set(swigCPtr, this, value);
  }

  public float getSpacing() {
    return CImGuiJNI.ImGuiMenuColumns_Spacing_get(swigCPtr, this);
  }

  public void setWidth(float value) {
    CImGuiJNI.ImGuiMenuColumns_Width_set(swigCPtr, this, value);
  }

  public float getWidth() {
    return CImGuiJNI.ImGuiMenuColumns_Width_get(swigCPtr, this);
  }

  public void setNextWidth(float value) {
    CImGuiJNI.ImGuiMenuColumns_NextWidth_set(swigCPtr, this, value);
  }

  public float getNextWidth() {
    return CImGuiJNI.ImGuiMenuColumns_NextWidth_get(swigCPtr, this);
  }

  public void setPos(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiMenuColumns_Pos_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getPos() {
    long cPtr = CImGuiJNI.ImGuiMenuColumns_Pos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setNextWidths(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiMenuColumns_NextWidths_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getNextWidths() {
    long cPtr = CImGuiJNI.ImGuiMenuColumns_NextWidths_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public ImGuiMenuColumns() {
    this(CImGuiJNI.new_ImGuiMenuColumns(), true);
  }

}
