/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiConfigFlags_ {
  public final static int ImGuiConfigFlags_None = 0;
  public final static int ImGuiConfigFlags_NavEnableKeyboard = 1 << 0;
  public final static int ImGuiConfigFlags_NavEnableGamepad = 1 << 1;
  public final static int ImGuiConfigFlags_NavEnableSetMousePos = 1 << 2;
  public final static int ImGuiConfigFlags_NavNoCaptureKeyboard = 1 << 3;
  public final static int ImGuiConfigFlags_NoMouse = 1 << 4;
  public final static int ImGuiConfigFlags_NoMouseCursorChange = 1 << 5;
  public final static int ImGuiConfigFlags_DockingEnable = 1 << 6;
  public final static int ImGuiConfigFlags_ViewportsEnable = 1 << 10;
  public final static int ImGuiConfigFlags_DpiEnableScaleViewports = 1 << 14;
  public final static int ImGuiConfigFlags_DpiEnableScaleFonts = 1 << 15;
  public final static int ImGuiConfigFlags_IsSRGB = 1 << 20;
  public final static int ImGuiConfigFlags_IsTouchScreen = 1 << 21;
}

