/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiWindowTempData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiWindowTempData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiWindowTempData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiWindowTempData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCursorPos(ImVec2 value) {
    CImGuiJNI.ImGuiWindowTempData_CursorPos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getCursorPos() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_CursorPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setCursorPosPrevLine(ImVec2 value) {
    CImGuiJNI.ImGuiWindowTempData_CursorPosPrevLine_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getCursorPosPrevLine() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_CursorPosPrevLine_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setCursorStartPos(ImVec2 value) {
    CImGuiJNI.ImGuiWindowTempData_CursorStartPos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getCursorStartPos() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_CursorStartPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setCursorMaxPos(ImVec2 value) {
    CImGuiJNI.ImGuiWindowTempData_CursorMaxPos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getCursorMaxPos() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_CursorMaxPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setCurrLineSize(ImVec2 value) {
    CImGuiJNI.ImGuiWindowTempData_CurrLineSize_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getCurrLineSize() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_CurrLineSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setPrevLineSize(ImVec2 value) {
    CImGuiJNI.ImGuiWindowTempData_PrevLineSize_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getPrevLineSize() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_PrevLineSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setCurrLineTextBaseOffset(float value) {
    CImGuiJNI.ImGuiWindowTempData_CurrLineTextBaseOffset_set(swigCPtr, this, value);
  }

  public float getCurrLineTextBaseOffset() {
    return CImGuiJNI.ImGuiWindowTempData_CurrLineTextBaseOffset_get(swigCPtr, this);
  }

  public void setPrevLineTextBaseOffset(float value) {
    CImGuiJNI.ImGuiWindowTempData_PrevLineTextBaseOffset_set(swigCPtr, this, value);
  }

  public float getPrevLineTextBaseOffset() {
    return CImGuiJNI.ImGuiWindowTempData_PrevLineTextBaseOffset_get(swigCPtr, this);
  }

  public void setIndent(ImVec1 value) {
    CImGuiJNI.ImGuiWindowTempData_Indent_set(swigCPtr, this, ImVec1.getCPtr(value), value);
  }

  public ImVec1 getIndent() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_Indent_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec1(cPtr, false);
  }

  public void setColumnsOffset(ImVec1 value) {
    CImGuiJNI.ImGuiWindowTempData_ColumnsOffset_set(swigCPtr, this, ImVec1.getCPtr(value), value);
  }

  public ImVec1 getColumnsOffset() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_ColumnsOffset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec1(cPtr, false);
  }

  public void setGroupOffset(ImVec1 value) {
    CImGuiJNI.ImGuiWindowTempData_GroupOffset_set(swigCPtr, this, ImVec1.getCPtr(value), value);
  }

  public ImVec1 getGroupOffset() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_GroupOffset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec1(cPtr, false);
  }

  public void setLastItemId(long value) {
    CImGuiJNI.ImGuiWindowTempData_LastItemId_set(swigCPtr, this, value);
  }

  public long getLastItemId() {
    return CImGuiJNI.ImGuiWindowTempData_LastItemId_get(swigCPtr, this);
  }

  public void setLastItemStatusFlags(int value) {
    CImGuiJNI.ImGuiWindowTempData_LastItemStatusFlags_set(swigCPtr, this, value);
  }

  public int getLastItemStatusFlags() {
    return CImGuiJNI.ImGuiWindowTempData_LastItemStatusFlags_get(swigCPtr, this);
  }

  public void setLastItemRect(ImRect value) {
    CImGuiJNI.ImGuiWindowTempData_LastItemRect_set(swigCPtr, this, ImRect.getCPtr(value), value);
  }

  public ImRect getLastItemRect() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_LastItemRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImRect(cPtr, false);
  }

  public void setLastItemDisplayRect(ImRect value) {
    CImGuiJNI.ImGuiWindowTempData_LastItemDisplayRect_set(swigCPtr, this, ImRect.getCPtr(value), value);
  }

  public ImRect getLastItemDisplayRect() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_LastItemDisplayRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImRect(cPtr, false);
  }

  public void setNavLayerCurrent(int value) {
    CImGuiJNI.ImGuiWindowTempData_NavLayerCurrent_set(swigCPtr, this, value);
  }

  public int getNavLayerCurrent() {
    return CImGuiJNI.ImGuiWindowTempData_NavLayerCurrent_get(swigCPtr, this);
  }

  public void setNavLayerCurrentMask(int value) {
    CImGuiJNI.ImGuiWindowTempData_NavLayerCurrentMask_set(swigCPtr, this, value);
  }

  public int getNavLayerCurrentMask() {
    return CImGuiJNI.ImGuiWindowTempData_NavLayerCurrentMask_get(swigCPtr, this);
  }

  public void setNavLayerActiveMask(int value) {
    CImGuiJNI.ImGuiWindowTempData_NavLayerActiveMask_set(swigCPtr, this, value);
  }

  public int getNavLayerActiveMask() {
    return CImGuiJNI.ImGuiWindowTempData_NavLayerActiveMask_get(swigCPtr, this);
  }

  public void setNavLayerActiveMaskNext(int value) {
    CImGuiJNI.ImGuiWindowTempData_NavLayerActiveMaskNext_set(swigCPtr, this, value);
  }

  public int getNavLayerActiveMaskNext() {
    return CImGuiJNI.ImGuiWindowTempData_NavLayerActiveMaskNext_get(swigCPtr, this);
  }

  public void setNavFocusScopeIdCurrent(long value) {
    CImGuiJNI.ImGuiWindowTempData_NavFocusScopeIdCurrent_set(swigCPtr, this, value);
  }

  public long getNavFocusScopeIdCurrent() {
    return CImGuiJNI.ImGuiWindowTempData_NavFocusScopeIdCurrent_get(swigCPtr, this);
  }

  public void setNavHideHighlightOneFrame(boolean value) {
    CImGuiJNI.ImGuiWindowTempData_NavHideHighlightOneFrame_set(swigCPtr, this, value);
  }

  public boolean getNavHideHighlightOneFrame() {
    return CImGuiJNI.ImGuiWindowTempData_NavHideHighlightOneFrame_get(swigCPtr, this);
  }

  public void setNavHasScroll(boolean value) {
    CImGuiJNI.ImGuiWindowTempData_NavHasScroll_set(swigCPtr, this, value);
  }

  public boolean getNavHasScroll() {
    return CImGuiJNI.ImGuiWindowTempData_NavHasScroll_get(swigCPtr, this);
  }

  public void setMenuBarAppending(boolean value) {
    CImGuiJNI.ImGuiWindowTempData_MenuBarAppending_set(swigCPtr, this, value);
  }

  public boolean getMenuBarAppending() {
    return CImGuiJNI.ImGuiWindowTempData_MenuBarAppending_get(swigCPtr, this);
  }

  public void setMenuBarOffset(ImVec2 value) {
    CImGuiJNI.ImGuiWindowTempData_MenuBarOffset_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getMenuBarOffset() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_MenuBarOffset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setMenuColumns(ImGuiMenuColumns value) {
    CImGuiJNI.ImGuiWindowTempData_MenuColumns_set(swigCPtr, this, ImGuiMenuColumns.getCPtr(value), value);
  }

  public ImGuiMenuColumns getMenuColumns() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_MenuColumns_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiMenuColumns(cPtr, false);
  }

  public void setTreeDepth(int value) {
    CImGuiJNI.ImGuiWindowTempData_TreeDepth_set(swigCPtr, this, value);
  }

  public int getTreeDepth() {
    return CImGuiJNI.ImGuiWindowTempData_TreeDepth_get(swigCPtr, this);
  }

  public void setTreeJumpToParentOnPopMask(long value) {
    CImGuiJNI.ImGuiWindowTempData_TreeJumpToParentOnPopMask_set(swigCPtr, this, value);
  }

  public long getTreeJumpToParentOnPopMask() {
    return CImGuiJNI.ImGuiWindowTempData_TreeJumpToParentOnPopMask_get(swigCPtr, this);
  }

  public void setChildWindows(ImVector_ImGuiWindowPtr value) {
    CImGuiJNI.ImGuiWindowTempData_ChildWindows_set(swigCPtr, this, ImVector_ImGuiWindowPtr.getCPtr(value), value);
  }

  public ImVector_ImGuiWindowPtr getChildWindows() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_ChildWindows_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiWindowPtr(cPtr, false);
  }

  public void setStateStorage(ImGuiStorage value) {
    CImGuiJNI.ImGuiWindowTempData_StateStorage_set(swigCPtr, this, ImGuiStorage.getCPtr(value), value);
  }

  public ImGuiStorage getStateStorage() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_StateStorage_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiStorage(cPtr, false);
  }

  public void setCurrentColumns(ImGuiColumns value) {
    CImGuiJNI.ImGuiWindowTempData_CurrentColumns_set(swigCPtr, this, ImGuiColumns.getCPtr(value), value);
  }

  public ImGuiColumns getCurrentColumns() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_CurrentColumns_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiColumns(cPtr, false);
  }

  public void setLayoutType(int value) {
    CImGuiJNI.ImGuiWindowTempData_LayoutType_set(swigCPtr, this, value);
  }

  public int getLayoutType() {
    return CImGuiJNI.ImGuiWindowTempData_LayoutType_get(swigCPtr, this);
  }

  public void setParentLayoutType(int value) {
    CImGuiJNI.ImGuiWindowTempData_ParentLayoutType_set(swigCPtr, this, value);
  }

  public int getParentLayoutType() {
    return CImGuiJNI.ImGuiWindowTempData_ParentLayoutType_get(swigCPtr, this);
  }

  public void setFocusCounterRegular(int value) {
    CImGuiJNI.ImGuiWindowTempData_FocusCounterRegular_set(swigCPtr, this, value);
  }

  public int getFocusCounterRegular() {
    return CImGuiJNI.ImGuiWindowTempData_FocusCounterRegular_get(swigCPtr, this);
  }

  public void setFocusCounterTabStop(int value) {
    CImGuiJNI.ImGuiWindowTempData_FocusCounterTabStop_set(swigCPtr, this, value);
  }

  public int getFocusCounterTabStop() {
    return CImGuiJNI.ImGuiWindowTempData_FocusCounterTabStop_get(swigCPtr, this);
  }

  public void setItemFlags(int value) {
    CImGuiJNI.ImGuiWindowTempData_ItemFlags_set(swigCPtr, this, value);
  }

  public int getItemFlags() {
    return CImGuiJNI.ImGuiWindowTempData_ItemFlags_get(swigCPtr, this);
  }

  public void setItemWidth(float value) {
    CImGuiJNI.ImGuiWindowTempData_ItemWidth_set(swigCPtr, this, value);
  }

  public float getItemWidth() {
    return CImGuiJNI.ImGuiWindowTempData_ItemWidth_get(swigCPtr, this);
  }

  public void setTextWrapPos(float value) {
    CImGuiJNI.ImGuiWindowTempData_TextWrapPos_set(swigCPtr, this, value);
  }

  public float getTextWrapPos() {
    return CImGuiJNI.ImGuiWindowTempData_TextWrapPos_get(swigCPtr, this);
  }

  public void setItemFlagsStack(ImVector_ImGuiItemFlags value) {
    CImGuiJNI.ImGuiWindowTempData_ItemFlagsStack_set(swigCPtr, this, ImVector_ImGuiItemFlags.getCPtr(value), value);
  }

  public ImVector_ImGuiItemFlags getItemFlagsStack() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_ItemFlagsStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiItemFlags(cPtr, false);
  }

  public void setItemWidthStack(ImVector_float value) {
    CImGuiJNI.ImGuiWindowTempData_ItemWidthStack_set(swigCPtr, this, ImVector_float.getCPtr(value), value);
  }

  public ImVector_float getItemWidthStack() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_ItemWidthStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_float(cPtr, false);
  }

  public void setTextWrapPosStack(ImVector_float value) {
    CImGuiJNI.ImGuiWindowTempData_TextWrapPosStack_set(swigCPtr, this, ImVector_float.getCPtr(value), value);
  }

  public ImVector_float getTextWrapPosStack() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_TextWrapPosStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_float(cPtr, false);
  }

  public void setGroupStack(ImVector_ImGuiGroupData value) {
    CImGuiJNI.ImGuiWindowTempData_GroupStack_set(swigCPtr, this, ImVector_ImGuiGroupData.getCPtr(value), value);
  }

  public ImVector_ImGuiGroupData getGroupStack() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_GroupStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiGroupData(cPtr, false);
  }

  public void setStackSizesBackup(SWIGTYPE_p_short value) {
    CImGuiJNI.ImGuiWindowTempData_StackSizesBackup_set(swigCPtr, this, SWIGTYPE_p_short.getCPtr(value));
  }

  public SWIGTYPE_p_short getStackSizesBackup() {
    long cPtr = CImGuiJNI.ImGuiWindowTempData_StackSizesBackup_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_short(cPtr, false);
  }

  public ImGuiWindowTempData() {
    this(CImGuiJNI.new_ImGuiWindowTempData(), true);
  }

}
