/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiWindowFlags_ {
  public final static int ImGuiWindowFlags_None = 0;
  public final static int ImGuiWindowFlags_NoTitleBar = 1 << 0;
  public final static int ImGuiWindowFlags_NoResize = 1 << 1;
  public final static int ImGuiWindowFlags_NoMove = 1 << 2;
  public final static int ImGuiWindowFlags_NoScrollbar = 1 << 3;
  public final static int ImGuiWindowFlags_NoScrollWithMouse = 1 << 4;
  public final static int ImGuiWindowFlags_NoCollapse = 1 << 5;
  public final static int ImGuiWindowFlags_AlwaysAutoResize = 1 << 6;
  public final static int ImGuiWindowFlags_NoBackground = 1 << 7;
  public final static int ImGuiWindowFlags_NoSavedSettings = 1 << 8;
  public final static int ImGuiWindowFlags_NoMouseInputs = 1 << 9;
  public final static int ImGuiWindowFlags_MenuBar = 1 << 10;
  public final static int ImGuiWindowFlags_HorizontalScrollbar = 1 << 11;
  public final static int ImGuiWindowFlags_NoFocusOnAppearing = 1 << 12;
  public final static int ImGuiWindowFlags_NoBringToFrontOnFocus = 1 << 13;
  public final static int ImGuiWindowFlags_AlwaysVerticalScrollbar = 1 << 14;
  public final static int ImGuiWindowFlags_AlwaysHorizontalScrollbar = 1 << 15;
  public final static int ImGuiWindowFlags_AlwaysUseWindowPadding = 1 << 16;
  public final static int ImGuiWindowFlags_NoNavInputs = 1 << 18;
  public final static int ImGuiWindowFlags_NoNavFocus = 1 << 19;
  public final static int ImGuiWindowFlags_UnsavedDocument = 1 << 20;
  public final static int ImGuiWindowFlags_NoDocking = 1 << 21;
  public final static int ImGuiWindowFlags_NoNav = ImGuiWindowFlags_NoNavInputs|ImGuiWindowFlags_NoNavFocus;
  public final static int ImGuiWindowFlags_NoDecoration = ImGuiWindowFlags_NoTitleBar|ImGuiWindowFlags_NoResize|ImGuiWindowFlags_NoScrollbar|ImGuiWindowFlags_NoCollapse;
  public final static int ImGuiWindowFlags_NoInputs = ImGuiWindowFlags_NoMouseInputs|ImGuiWindowFlags_NoNavInputs|ImGuiWindowFlags_NoNavFocus;
  public final static int ImGuiWindowFlags_NavFlattened = 1 << 23;
  public final static int ImGuiWindowFlags_ChildWindow = 1 << 24;
  public final static int ImGuiWindowFlags_Tooltip = 1 << 25;
  public final static int ImGuiWindowFlags_Popup = 1 << 26;
  public final static int ImGuiWindowFlags_Modal = 1 << 27;
  public final static int ImGuiWindowFlags_ChildMenu = 1 << 28;
  public final static int ImGuiWindowFlags_DockNodeHost = 1 << 29;
}

