/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiViewportP {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiViewportP(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiViewportP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiViewportP(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_ImGuiViewport(ImGuiViewport value) {
    CImGuiJNI.ImGuiViewportP__ImGuiViewport_set(swigCPtr, this, ImGuiViewport.getCPtr(value), value);
  }

  public ImGuiViewport get_ImGuiViewport() {
    long cPtr = CImGuiJNI.ImGuiViewportP__ImGuiViewport_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiViewport(cPtr, false);
  }

  public void setIdx(int value) {
    CImGuiJNI.ImGuiViewportP_Idx_set(swigCPtr, this, value);
  }

  public int getIdx() {
    return CImGuiJNI.ImGuiViewportP_Idx_get(swigCPtr, this);
  }

  public void setLastFrameActive(int value) {
    CImGuiJNI.ImGuiViewportP_LastFrameActive_set(swigCPtr, this, value);
  }

  public int getLastFrameActive() {
    return CImGuiJNI.ImGuiViewportP_LastFrameActive_get(swigCPtr, this);
  }

  public void setLastFrameDrawLists(SWIGTYPE_p_int value) {
    CImGuiJNI.ImGuiViewportP_LastFrameDrawLists_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getLastFrameDrawLists() {
    long cPtr = CImGuiJNI.ImGuiViewportP_LastFrameDrawLists_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setLastFrontMostStampCount(int value) {
    CImGuiJNI.ImGuiViewportP_LastFrontMostStampCount_set(swigCPtr, this, value);
  }

  public int getLastFrontMostStampCount() {
    return CImGuiJNI.ImGuiViewportP_LastFrontMostStampCount_get(swigCPtr, this);
  }

  public void setLastNameHash(long value) {
    CImGuiJNI.ImGuiViewportP_LastNameHash_set(swigCPtr, this, value);
  }

  public long getLastNameHash() {
    return CImGuiJNI.ImGuiViewportP_LastNameHash_get(swigCPtr, this);
  }

  public void setLastPos(ImVec2 value) {
    CImGuiJNI.ImGuiViewportP_LastPos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getLastPos() {
    long cPtr = CImGuiJNI.ImGuiViewportP_LastPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setAlpha(float value) {
    CImGuiJNI.ImGuiViewportP_Alpha_set(swigCPtr, this, value);
  }

  public float getAlpha() {
    return CImGuiJNI.ImGuiViewportP_Alpha_get(swigCPtr, this);
  }

  public void setLastAlpha(float value) {
    CImGuiJNI.ImGuiViewportP_LastAlpha_set(swigCPtr, this, value);
  }

  public float getLastAlpha() {
    return CImGuiJNI.ImGuiViewportP_LastAlpha_get(swigCPtr, this);
  }

  public void setPlatformMonitor(short value) {
    CImGuiJNI.ImGuiViewportP_PlatformMonitor_set(swigCPtr, this, value);
  }

  public short getPlatformMonitor() {
    return CImGuiJNI.ImGuiViewportP_PlatformMonitor_get(swigCPtr, this);
  }

  public void setPlatformWindowCreated(boolean value) {
    CImGuiJNI.ImGuiViewportP_PlatformWindowCreated_set(swigCPtr, this, value);
  }

  public boolean getPlatformWindowCreated() {
    return CImGuiJNI.ImGuiViewportP_PlatformWindowCreated_get(swigCPtr, this);
  }

  public void setWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiViewportP_Window_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getWindow() {
    long cPtr = CImGuiJNI.ImGuiViewportP_Window_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setDrawLists(SWIGTYPE_p_p_ImDrawList value) {
    CImGuiJNI.ImGuiViewportP_DrawLists_set(swigCPtr, this, SWIGTYPE_p_p_ImDrawList.getCPtr(value));
  }

  public SWIGTYPE_p_p_ImDrawList getDrawLists() {
    long cPtr = CImGuiJNI.ImGuiViewportP_DrawLists_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_ImDrawList(cPtr, false);
  }

  public void setDrawDataP(ImDrawData value) {
    CImGuiJNI.ImGuiViewportP_DrawDataP_set(swigCPtr, this, ImDrawData.getCPtr(value), value);
  }

  public ImDrawData getDrawDataP() {
    long cPtr = CImGuiJNI.ImGuiViewportP_DrawDataP_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawData(cPtr, false);
  }

  public void setDrawDataBuilder(ImDrawDataBuilder value) {
    CImGuiJNI.ImGuiViewportP_DrawDataBuilder_set(swigCPtr, this, ImDrawDataBuilder.getCPtr(value), value);
  }

  public ImDrawDataBuilder getDrawDataBuilder() {
    long cPtr = CImGuiJNI.ImGuiViewportP_DrawDataBuilder_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawDataBuilder(cPtr, false);
  }

  public void setLastPlatformPos(ImVec2 value) {
    CImGuiJNI.ImGuiViewportP_LastPlatformPos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getLastPlatformPos() {
    long cPtr = CImGuiJNI.ImGuiViewportP_LastPlatformPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setLastPlatformSize(ImVec2 value) {
    CImGuiJNI.ImGuiViewportP_LastPlatformSize_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getLastPlatformSize() {
    long cPtr = CImGuiJNI.ImGuiViewportP_LastPlatformSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setLastRendererSize(ImVec2 value) {
    CImGuiJNI.ImGuiViewportP_LastRendererSize_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getLastRendererSize() {
    long cPtr = CImGuiJNI.ImGuiViewportP_LastRendererSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setCurrWorkOffsetMin(ImVec2 value) {
    CImGuiJNI.ImGuiViewportP_CurrWorkOffsetMin_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getCurrWorkOffsetMin() {
    long cPtr = CImGuiJNI.ImGuiViewportP_CurrWorkOffsetMin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setCurrWorkOffsetMax(ImVec2 value) {
    CImGuiJNI.ImGuiViewportP_CurrWorkOffsetMax_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getCurrWorkOffsetMax() {
    long cPtr = CImGuiJNI.ImGuiViewportP_CurrWorkOffsetMax_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public ImGuiViewportP() {
    this(CImGuiJNI.new_ImGuiViewportP(), true);
  }

}
