/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiDataType_ {
  public final static int ImGuiDataType_S8 = 0;
  public final static int ImGuiDataType_U8 = ImGuiDataType_S8 + 1;
  public final static int ImGuiDataType_S16 = ImGuiDataType_U8 + 1;
  public final static int ImGuiDataType_U16 = ImGuiDataType_S16 + 1;
  public final static int ImGuiDataType_S32 = ImGuiDataType_U16 + 1;
  public final static int ImGuiDataType_U32 = ImGuiDataType_S32 + 1;
  public final static int ImGuiDataType_S64 = ImGuiDataType_U32 + 1;
  public final static int ImGuiDataType_U64 = ImGuiDataType_S64 + 1;
  public final static int ImGuiDataType_Float = ImGuiDataType_U64 + 1;
  public final static int ImGuiDataType_Double = ImGuiDataType_Float + 1;
  public final static int ImGuiDataType_COUNT = ImGuiDataType_Double + 1;
}

