/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiPtrOrIndex {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiPtrOrIndex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiPtrOrIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiPtrOrIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPtr(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiPtrOrIndex_Ptr_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPtr() {
    long cPtr = CImGuiJNI.ImGuiPtrOrIndex_Ptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setIndex(int value) {
    CImGuiJNI.ImGuiPtrOrIndex_Index_set(swigCPtr, this, value);
  }

  public int getIndex() {
    return CImGuiJNI.ImGuiPtrOrIndex_Index_get(swigCPtr, this);
  }

  public ImGuiPtrOrIndex() {
    this(CImGuiJNI.new_ImGuiPtrOrIndex(), true);
  }

}
