/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiStyle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiStyle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiStyle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiStyle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAlpha(float value) {
    CImGuiJNI.ImGuiStyle_Alpha_set(swigCPtr, this, value);
  }

  public float getAlpha() {
    return CImGuiJNI.ImGuiStyle_Alpha_get(swigCPtr, this);
  }

  public void setWindowPadding(ImVec2 value) {
    CImGuiJNI.ImGuiStyle_WindowPadding_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getWindowPadding() {
    long cPtr = CImGuiJNI.ImGuiStyle_WindowPadding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setWindowRounding(float value) {
    CImGuiJNI.ImGuiStyle_WindowRounding_set(swigCPtr, this, value);
  }

  public float getWindowRounding() {
    return CImGuiJNI.ImGuiStyle_WindowRounding_get(swigCPtr, this);
  }

  public void setWindowBorderSize(float value) {
    CImGuiJNI.ImGuiStyle_WindowBorderSize_set(swigCPtr, this, value);
  }

  public float getWindowBorderSize() {
    return CImGuiJNI.ImGuiStyle_WindowBorderSize_get(swigCPtr, this);
  }

  public void setWindowMinSize(ImVec2 value) {
    CImGuiJNI.ImGuiStyle_WindowMinSize_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getWindowMinSize() {
    long cPtr = CImGuiJNI.ImGuiStyle_WindowMinSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setWindowTitleAlign(ImVec2 value) {
    CImGuiJNI.ImGuiStyle_WindowTitleAlign_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getWindowTitleAlign() {
    long cPtr = CImGuiJNI.ImGuiStyle_WindowTitleAlign_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setWindowMenuButtonPosition(int value) {
    CImGuiJNI.ImGuiStyle_WindowMenuButtonPosition_set(swigCPtr, this, value);
  }

  public int getWindowMenuButtonPosition() {
    return CImGuiJNI.ImGuiStyle_WindowMenuButtonPosition_get(swigCPtr, this);
  }

  public void setChildRounding(float value) {
    CImGuiJNI.ImGuiStyle_ChildRounding_set(swigCPtr, this, value);
  }

  public float getChildRounding() {
    return CImGuiJNI.ImGuiStyle_ChildRounding_get(swigCPtr, this);
  }

  public void setChildBorderSize(float value) {
    CImGuiJNI.ImGuiStyle_ChildBorderSize_set(swigCPtr, this, value);
  }

  public float getChildBorderSize() {
    return CImGuiJNI.ImGuiStyle_ChildBorderSize_get(swigCPtr, this);
  }

  public void setPopupRounding(float value) {
    CImGuiJNI.ImGuiStyle_PopupRounding_set(swigCPtr, this, value);
  }

  public float getPopupRounding() {
    return CImGuiJNI.ImGuiStyle_PopupRounding_get(swigCPtr, this);
  }

  public void setPopupBorderSize(float value) {
    CImGuiJNI.ImGuiStyle_PopupBorderSize_set(swigCPtr, this, value);
  }

  public float getPopupBorderSize() {
    return CImGuiJNI.ImGuiStyle_PopupBorderSize_get(swigCPtr, this);
  }

  public void setFramePadding(ImVec2 value) {
    CImGuiJNI.ImGuiStyle_FramePadding_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getFramePadding() {
    long cPtr = CImGuiJNI.ImGuiStyle_FramePadding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setFrameRounding(float value) {
    CImGuiJNI.ImGuiStyle_FrameRounding_set(swigCPtr, this, value);
  }

  public float getFrameRounding() {
    return CImGuiJNI.ImGuiStyle_FrameRounding_get(swigCPtr, this);
  }

  public void setFrameBorderSize(float value) {
    CImGuiJNI.ImGuiStyle_FrameBorderSize_set(swigCPtr, this, value);
  }

  public float getFrameBorderSize() {
    return CImGuiJNI.ImGuiStyle_FrameBorderSize_get(swigCPtr, this);
  }

  public void setItemSpacing(ImVec2 value) {
    CImGuiJNI.ImGuiStyle_ItemSpacing_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getItemSpacing() {
    long cPtr = CImGuiJNI.ImGuiStyle_ItemSpacing_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setItemInnerSpacing(ImVec2 value) {
    CImGuiJNI.ImGuiStyle_ItemInnerSpacing_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getItemInnerSpacing() {
    long cPtr = CImGuiJNI.ImGuiStyle_ItemInnerSpacing_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setTouchExtraPadding(ImVec2 value) {
    CImGuiJNI.ImGuiStyle_TouchExtraPadding_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getTouchExtraPadding() {
    long cPtr = CImGuiJNI.ImGuiStyle_TouchExtraPadding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setIndentSpacing(float value) {
    CImGuiJNI.ImGuiStyle_IndentSpacing_set(swigCPtr, this, value);
  }

  public float getIndentSpacing() {
    return CImGuiJNI.ImGuiStyle_IndentSpacing_get(swigCPtr, this);
  }

  public void setColumnsMinSpacing(float value) {
    CImGuiJNI.ImGuiStyle_ColumnsMinSpacing_set(swigCPtr, this, value);
  }

  public float getColumnsMinSpacing() {
    return CImGuiJNI.ImGuiStyle_ColumnsMinSpacing_get(swigCPtr, this);
  }

  public void setScrollbarSize(float value) {
    CImGuiJNI.ImGuiStyle_ScrollbarSize_set(swigCPtr, this, value);
  }

  public float getScrollbarSize() {
    return CImGuiJNI.ImGuiStyle_ScrollbarSize_get(swigCPtr, this);
  }

  public void setScrollbarRounding(float value) {
    CImGuiJNI.ImGuiStyle_ScrollbarRounding_set(swigCPtr, this, value);
  }

  public float getScrollbarRounding() {
    return CImGuiJNI.ImGuiStyle_ScrollbarRounding_get(swigCPtr, this);
  }

  public void setGrabMinSize(float value) {
    CImGuiJNI.ImGuiStyle_GrabMinSize_set(swigCPtr, this, value);
  }

  public float getGrabMinSize() {
    return CImGuiJNI.ImGuiStyle_GrabMinSize_get(swigCPtr, this);
  }

  public void setGrabRounding(float value) {
    CImGuiJNI.ImGuiStyle_GrabRounding_set(swigCPtr, this, value);
  }

  public float getGrabRounding() {
    return CImGuiJNI.ImGuiStyle_GrabRounding_get(swigCPtr, this);
  }

  public void setTabRounding(float value) {
    CImGuiJNI.ImGuiStyle_TabRounding_set(swigCPtr, this, value);
  }

  public float getTabRounding() {
    return CImGuiJNI.ImGuiStyle_TabRounding_get(swigCPtr, this);
  }

  public void setTabBorderSize(float value) {
    CImGuiJNI.ImGuiStyle_TabBorderSize_set(swigCPtr, this, value);
  }

  public float getTabBorderSize() {
    return CImGuiJNI.ImGuiStyle_TabBorderSize_get(swigCPtr, this);
  }

  public void setTabMinWidthForUnselectedCloseButton(float value) {
    CImGuiJNI.ImGuiStyle_TabMinWidthForUnselectedCloseButton_set(swigCPtr, this, value);
  }

  public float getTabMinWidthForUnselectedCloseButton() {
    return CImGuiJNI.ImGuiStyle_TabMinWidthForUnselectedCloseButton_get(swigCPtr, this);
  }

  public void setColorButtonPosition(int value) {
    CImGuiJNI.ImGuiStyle_ColorButtonPosition_set(swigCPtr, this, value);
  }

  public int getColorButtonPosition() {
    return CImGuiJNI.ImGuiStyle_ColorButtonPosition_get(swigCPtr, this);
  }

  public void setButtonTextAlign(ImVec2 value) {
    CImGuiJNI.ImGuiStyle_ButtonTextAlign_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getButtonTextAlign() {
    long cPtr = CImGuiJNI.ImGuiStyle_ButtonTextAlign_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setSelectableTextAlign(ImVec2 value) {
    CImGuiJNI.ImGuiStyle_SelectableTextAlign_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getSelectableTextAlign() {
    long cPtr = CImGuiJNI.ImGuiStyle_SelectableTextAlign_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setDisplayWindowPadding(ImVec2 value) {
    CImGuiJNI.ImGuiStyle_DisplayWindowPadding_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getDisplayWindowPadding() {
    long cPtr = CImGuiJNI.ImGuiStyle_DisplayWindowPadding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setDisplaySafeAreaPadding(ImVec2 value) {
    CImGuiJNI.ImGuiStyle_DisplaySafeAreaPadding_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getDisplaySafeAreaPadding() {
    long cPtr = CImGuiJNI.ImGuiStyle_DisplaySafeAreaPadding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setMouseCursorScale(float value) {
    CImGuiJNI.ImGuiStyle_MouseCursorScale_set(swigCPtr, this, value);
  }

  public float getMouseCursorScale() {
    return CImGuiJNI.ImGuiStyle_MouseCursorScale_get(swigCPtr, this);
  }

  public void setAntiAliasedLines(boolean value) {
    CImGuiJNI.ImGuiStyle_AntiAliasedLines_set(swigCPtr, this, value);
  }

  public boolean getAntiAliasedLines() {
    return CImGuiJNI.ImGuiStyle_AntiAliasedLines_get(swigCPtr, this);
  }

  public void setAntiAliasedFill(boolean value) {
    CImGuiJNI.ImGuiStyle_AntiAliasedFill_set(swigCPtr, this, value);
  }

  public boolean getAntiAliasedFill() {
    return CImGuiJNI.ImGuiStyle_AntiAliasedFill_get(swigCPtr, this);
  }

  public void setCurveTessellationTol(float value) {
    CImGuiJNI.ImGuiStyle_CurveTessellationTol_set(swigCPtr, this, value);
  }

  public float getCurveTessellationTol() {
    return CImGuiJNI.ImGuiStyle_CurveTessellationTol_get(swigCPtr, this);
  }

  public void setCircleSegmentMaxError(float value) {
    CImGuiJNI.ImGuiStyle_CircleSegmentMaxError_set(swigCPtr, this, value);
  }

  public float getCircleSegmentMaxError() {
    return CImGuiJNI.ImGuiStyle_CircleSegmentMaxError_get(swigCPtr, this);
  }

  public void setColors(ImVec4 value) {
    CImGuiJNI.ImGuiStyle_Colors_set(swigCPtr, this, ImVec4.getCPtr(value), value);
  }

  public ImVec4 getColors() {
    long cPtr = CImGuiJNI.ImGuiStyle_Colors_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec4(cPtr, false);
  }

  public ImGuiStyle() {
    this(CImGuiJNI.new_ImGuiStyle(), true);
  }

}
