/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiTabItemFlags_ {
  public final static int ImGuiTabItemFlags_None = 0;
  public final static int ImGuiTabItemFlags_UnsavedDocument = 1 << 0;
  public final static int ImGuiTabItemFlags_SetSelected = 1 << 1;
  public final static int ImGuiTabItemFlags_NoCloseWithMiddleMouseButton = 1 << 2;
  public final static int ImGuiTabItemFlags_NoPushId = 1 << 3;
}

