/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiDataTypeInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiDataTypeInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiDataTypeInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiDataTypeInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(long value) {
    CImGuiJNI.ImGuiDataTypeInfo_Size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return CImGuiJNI.ImGuiDataTypeInfo_Size_get(swigCPtr, this);
  }

  public void setPrintFmt(String value) {
    CImGuiJNI.ImGuiDataTypeInfo_PrintFmt_set(swigCPtr, this, value);
  }

  public String getPrintFmt() {
    return CImGuiJNI.ImGuiDataTypeInfo_PrintFmt_get(swigCPtr, this);
  }

  public void setScanFmt(String value) {
    CImGuiJNI.ImGuiDataTypeInfo_ScanFmt_set(swigCPtr, this, value);
  }

  public String getScanFmt() {
    return CImGuiJNI.ImGuiDataTypeInfo_ScanFmt_get(swigCPtr, this);
  }

  public ImGuiDataTypeInfo() {
    this(CImGuiJNI.new_ImGuiDataTypeInfo(), true);
  }

}
