/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiNavMoveFlags_ {
  public final static int ImGuiNavMoveFlags_None = 0;
  public final static int ImGuiNavMoveFlags_LoopX = 1 << 0;
  public final static int ImGuiNavMoveFlags_LoopY = 1 << 1;
  public final static int ImGuiNavMoveFlags_WrapX = 1 << 2;
  public final static int ImGuiNavMoveFlags_WrapY = 1 << 3;
  public final static int ImGuiNavMoveFlags_AllowCurrentNavId = 1 << 4;
  public final static int ImGuiNavMoveFlags_AlsoScoreVisibleSet = 1 << 5;
  public final static int ImGuiNavMoveFlags_ScrollToEdge = 1 << 6;
}

