/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiItemFlags_ {
  public final static int ImGuiItemFlags_None = 0;
  public final static int ImGuiItemFlags_NoTabStop = 1 << 0;
  public final static int ImGuiItemFlags_ButtonRepeat = 1 << 1;
  public final static int ImGuiItemFlags_Disabled = 1 << 2;
  public final static int ImGuiItemFlags_NoNav = 1 << 3;
  public final static int ImGuiItemFlags_NoNavDefaultFocus = 1 << 4;
  public final static int ImGuiItemFlags_SelectableDontClosePopup = 1 << 5;
  public final static int ImGuiItemFlags_MixedValue = 1 << 6;
  public final static int ImGuiItemFlags_Default_ = 0;
}

