/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiInputTextFlags_ {
  public final static int ImGuiInputTextFlags_None = 0;
  public final static int ImGuiInputTextFlags_CharsDecimal = 1 << 0;
  public final static int ImGuiInputTextFlags_CharsHexadecimal = 1 << 1;
  public final static int ImGuiInputTextFlags_CharsUppercase = 1 << 2;
  public final static int ImGuiInputTextFlags_CharsNoBlank = 1 << 3;
  public final static int ImGuiInputTextFlags_AutoSelectAll = 1 << 4;
  public final static int ImGuiInputTextFlags_EnterReturnsTrue = 1 << 5;
  public final static int ImGuiInputTextFlags_CallbackCompletion = 1 << 6;
  public final static int ImGuiInputTextFlags_CallbackHistory = 1 << 7;
  public final static int ImGuiInputTextFlags_CallbackAlways = 1 << 8;
  public final static int ImGuiInputTextFlags_CallbackCharFilter = 1 << 9;
  public final static int ImGuiInputTextFlags_AllowTabInput = 1 << 10;
  public final static int ImGuiInputTextFlags_CtrlEnterForNewLine = 1 << 11;
  public final static int ImGuiInputTextFlags_NoHorizontalScroll = 1 << 12;
  public final static int ImGuiInputTextFlags_AlwaysInsertMode = 1 << 13;
  public final static int ImGuiInputTextFlags_ReadOnly = 1 << 14;
  public final static int ImGuiInputTextFlags_Password = 1 << 15;
  public final static int ImGuiInputTextFlags_NoUndoRedo = 1 << 16;
  public final static int ImGuiInputTextFlags_CharsScientific = 1 << 17;
  public final static int ImGuiInputTextFlags_CallbackResize = 1 << 18;
  public final static int ImGuiInputTextFlags_Multiline = 1 << 20;
  public final static int ImGuiInputTextFlags_NoMarkEdited = 1 << 21;
}

