/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiViewportFlags_ {
  public final static int ImGuiViewportFlags_None = 0;
  public final static int ImGuiViewportFlags_NoDecoration = 1 << 0;
  public final static int ImGuiViewportFlags_NoTaskBarIcon = 1 << 1;
  public final static int ImGuiViewportFlags_NoFocusOnAppearing = 1 << 2;
  public final static int ImGuiViewportFlags_NoFocusOnClick = 1 << 3;
  public final static int ImGuiViewportFlags_NoInputs = 1 << 4;
  public final static int ImGuiViewportFlags_NoRendererClear = 1 << 5;
  public final static int ImGuiViewportFlags_TopMost = 1 << 6;
  public final static int ImGuiViewportFlags_Minimized = 1 << 7;
  public final static int ImGuiViewportFlags_NoAutoMerge = 1 << 8;
  public final static int ImGuiViewportFlags_CanHostOtherWindows = 1 << 9;
}

