/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiNavDirSourceFlags_ {
  public final static int ImGuiNavDirSourceFlags_None = 0;
  public final static int ImGuiNavDirSourceFlags_Keyboard = 1 << 0;
  public final static int ImGuiNavDirSourceFlags_PadDPad = 1 << 1;
  public final static int ImGuiNavDirSourceFlags_PadLStick = 1 << 2;
}

