/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiOnceUponAFrame {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiOnceUponAFrame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiOnceUponAFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiOnceUponAFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRefFrame(int value) {
    CImGuiJNI.ImGuiOnceUponAFrame_RefFrame_set(swigCPtr, this, value);
  }

  public int getRefFrame() {
    return CImGuiJNI.ImGuiOnceUponAFrame_RefFrame_get(swigCPtr, this);
  }

  public ImGuiOnceUponAFrame() {
    this(CImGuiJNI.new_ImGuiOnceUponAFrame(), true);
  }

}
