/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiNextWindowData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiNextWindowData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiNextWindowData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiNextWindowData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFlags(int value) {
    CImGuiJNI.ImGuiNextWindowData_Flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return CImGuiJNI.ImGuiNextWindowData_Flags_get(swigCPtr, this);
  }

  public void setPosCond(int value) {
    CImGuiJNI.ImGuiNextWindowData_PosCond_set(swigCPtr, this, value);
  }

  public int getPosCond() {
    return CImGuiJNI.ImGuiNextWindowData_PosCond_get(swigCPtr, this);
  }

  public void setSizeCond(int value) {
    CImGuiJNI.ImGuiNextWindowData_SizeCond_set(swigCPtr, this, value);
  }

  public int getSizeCond() {
    return CImGuiJNI.ImGuiNextWindowData_SizeCond_get(swigCPtr, this);
  }

  public void setCollapsedCond(int value) {
    CImGuiJNI.ImGuiNextWindowData_CollapsedCond_set(swigCPtr, this, value);
  }

  public int getCollapsedCond() {
    return CImGuiJNI.ImGuiNextWindowData_CollapsedCond_get(swigCPtr, this);
  }

  public void setPosVal(ImVec2 value) {
    CImGuiJNI.ImGuiNextWindowData_PosVal_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getPosVal() {
    long cPtr = CImGuiJNI.ImGuiNextWindowData_PosVal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setPosPivotVal(ImVec2 value) {
    CImGuiJNI.ImGuiNextWindowData_PosPivotVal_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getPosPivotVal() {
    long cPtr = CImGuiJNI.ImGuiNextWindowData_PosPivotVal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setSizeVal(ImVec2 value) {
    CImGuiJNI.ImGuiNextWindowData_SizeVal_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getSizeVal() {
    long cPtr = CImGuiJNI.ImGuiNextWindowData_SizeVal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setContentSizeVal(ImVec2 value) {
    CImGuiJNI.ImGuiNextWindowData_ContentSizeVal_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getContentSizeVal() {
    long cPtr = CImGuiJNI.ImGuiNextWindowData_ContentSizeVal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setCollapsedVal(boolean value) {
    CImGuiJNI.ImGuiNextWindowData_CollapsedVal_set(swigCPtr, this, value);
  }

  public boolean getCollapsedVal() {
    return CImGuiJNI.ImGuiNextWindowData_CollapsedVal_get(swigCPtr, this);
  }

  public void setSizeConstraintRect(ImRect value) {
    CImGuiJNI.ImGuiNextWindowData_SizeConstraintRect_set(swigCPtr, this, ImRect.getCPtr(value), value);
  }

  public ImRect getSizeConstraintRect() {
    long cPtr = CImGuiJNI.ImGuiNextWindowData_SizeConstraintRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImRect(cPtr, false);
  }

  public void setSizeCallback(SWIGTYPE_p_f_p_ImGuiSizeCallbackData__void value) {
    CImGuiJNI.ImGuiNextWindowData_SizeCallback_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiSizeCallbackData__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiSizeCallbackData__void getSizeCallback() {
    long cPtr = CImGuiJNI.ImGuiNextWindowData_SizeCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiSizeCallbackData__void(cPtr, false);
  }

  public void setSizeCallbackUserData(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiNextWindowData_SizeCallbackUserData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getSizeCallbackUserData() {
    long cPtr = CImGuiJNI.ImGuiNextWindowData_SizeCallbackUserData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setBgAlphaVal(float value) {
    CImGuiJNI.ImGuiNextWindowData_BgAlphaVal_set(swigCPtr, this, value);
  }

  public float getBgAlphaVal() {
    return CImGuiJNI.ImGuiNextWindowData_BgAlphaVal_get(swigCPtr, this);
  }

  public void setMenuBarOffsetMinVal(ImVec2 value) {
    CImGuiJNI.ImGuiNextWindowData_MenuBarOffsetMinVal_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getMenuBarOffsetMinVal() {
    long cPtr = CImGuiJNI.ImGuiNextWindowData_MenuBarOffsetMinVal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public ImGuiNextWindowData() {
    this(CImGuiJNI.new_ImGuiNextWindowData(), true);
  }

}
