/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiCond_ {
  public final static int ImGuiCond_Always = 1 << 0;
  public final static int ImGuiCond_Once = 1 << 1;
  public final static int ImGuiCond_FirstUseEver = 1 << 2;
  public final static int ImGuiCond_Appearing = 1 << 3;
}

