/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiItemHoveredDataBackup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiItemHoveredDataBackup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiItemHoveredDataBackup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiItemHoveredDataBackup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLastItemId(long value) {
    CImGuiJNI.ImGuiItemHoveredDataBackup_LastItemId_set(swigCPtr, this, value);
  }

  public long getLastItemId() {
    return CImGuiJNI.ImGuiItemHoveredDataBackup_LastItemId_get(swigCPtr, this);
  }

  public void setLastItemStatusFlags(int value) {
    CImGuiJNI.ImGuiItemHoveredDataBackup_LastItemStatusFlags_set(swigCPtr, this, value);
  }

  public int getLastItemStatusFlags() {
    return CImGuiJNI.ImGuiItemHoveredDataBackup_LastItemStatusFlags_get(swigCPtr, this);
  }

  public void setLastItemRect(ImRect value) {
    CImGuiJNI.ImGuiItemHoveredDataBackup_LastItemRect_set(swigCPtr, this, ImRect.getCPtr(value), value);
  }

  public ImRect getLastItemRect() {
    long cPtr = CImGuiJNI.ImGuiItemHoveredDataBackup_LastItemRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImRect(cPtr, false);
  }

  public void setLastItemDisplayRect(ImRect value) {
    CImGuiJNI.ImGuiItemHoveredDataBackup_LastItemDisplayRect_set(swigCPtr, this, ImRect.getCPtr(value), value);
  }

  public ImRect getLastItemDisplayRect() {
    long cPtr = CImGuiJNI.ImGuiItemHoveredDataBackup_LastItemDisplayRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImRect(cPtr, false);
  }

  public ImGuiItemHoveredDataBackup() {
    this(CImGuiJNI.new_ImGuiItemHoveredDataBackup(), true);
  }

}
