/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiBackendFlags_ {
  public final static int ImGuiBackendFlags_None = 0;
  public final static int ImGuiBackendFlags_HasGamepad = 1 << 0;
  public final static int ImGuiBackendFlags_HasMouseCursors = 1 << 1;
  public final static int ImGuiBackendFlags_HasSetMousePos = 1 << 2;
  public final static int ImGuiBackendFlags_RendererHasVtxOffset = 1 << 3;
  public final static int ImGuiBackendFlags_PlatformHasViewports = 1 << 10;
  public final static int ImGuiBackendFlags_HasMouseHoveredViewport = 1 << 11;
  public final static int ImGuiBackendFlags_RendererHasViewports = 1 << 12;
}

