/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiTabBarFlagsPrivate_ {
  public final static int ImGuiTabBarFlags_DockNode = 1 << 20;
  public final static int ImGuiTabBarFlags_IsFocused = 1 << 21;
  public final static int ImGuiTabBarFlags_SaveSettings = 1 << 22;
}

