/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiStyleVar_ {
  public final static int ImGuiStyleVar_Alpha = 0;
  public final static int ImGuiStyleVar_WindowPadding = ImGuiStyleVar_Alpha + 1;
  public final static int ImGuiStyleVar_WindowRounding = ImGuiStyleVar_WindowPadding + 1;
  public final static int ImGuiStyleVar_WindowBorderSize = ImGuiStyleVar_WindowRounding + 1;
  public final static int ImGuiStyleVar_WindowMinSize = ImGuiStyleVar_WindowBorderSize + 1;
  public final static int ImGuiStyleVar_WindowTitleAlign = ImGuiStyleVar_WindowMinSize + 1;
  public final static int ImGuiStyleVar_ChildRounding = ImGuiStyleVar_WindowTitleAlign + 1;
  public final static int ImGuiStyleVar_ChildBorderSize = ImGuiStyleVar_ChildRounding + 1;
  public final static int ImGuiStyleVar_PopupRounding = ImGuiStyleVar_ChildBorderSize + 1;
  public final static int ImGuiStyleVar_PopupBorderSize = ImGuiStyleVar_PopupRounding + 1;
  public final static int ImGuiStyleVar_FramePadding = ImGuiStyleVar_PopupBorderSize + 1;
  public final static int ImGuiStyleVar_FrameRounding = ImGuiStyleVar_FramePadding + 1;
  public final static int ImGuiStyleVar_FrameBorderSize = ImGuiStyleVar_FrameRounding + 1;
  public final static int ImGuiStyleVar_ItemSpacing = ImGuiStyleVar_FrameBorderSize + 1;
  public final static int ImGuiStyleVar_ItemInnerSpacing = ImGuiStyleVar_ItemSpacing + 1;
  public final static int ImGuiStyleVar_IndentSpacing = ImGuiStyleVar_ItemInnerSpacing + 1;
  public final static int ImGuiStyleVar_ScrollbarSize = ImGuiStyleVar_IndentSpacing + 1;
  public final static int ImGuiStyleVar_ScrollbarRounding = ImGuiStyleVar_ScrollbarSize + 1;
  public final static int ImGuiStyleVar_GrabMinSize = ImGuiStyleVar_ScrollbarRounding + 1;
  public final static int ImGuiStyleVar_GrabRounding = ImGuiStyleVar_GrabMinSize + 1;
  public final static int ImGuiStyleVar_TabRounding = ImGuiStyleVar_GrabRounding + 1;
  public final static int ImGuiStyleVar_ButtonTextAlign = ImGuiStyleVar_TabRounding + 1;
  public final static int ImGuiStyleVar_SelectableTextAlign = ImGuiStyleVar_ButtonTextAlign + 1;
  public final static int ImGuiStyleVar_COUNT = ImGuiStyleVar_SelectableTextAlign + 1;
}

