/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiShrinkWidthItem {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiShrinkWidthItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiShrinkWidthItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiShrinkWidthItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIndex(int value) {
    CImGuiJNI.ImGuiShrinkWidthItem_Index_set(swigCPtr, this, value);
  }

  public int getIndex() {
    return CImGuiJNI.ImGuiShrinkWidthItem_Index_get(swigCPtr, this);
  }

  public void setWidth(float value) {
    CImGuiJNI.ImGuiShrinkWidthItem_Width_set(swigCPtr, this, value);
  }

  public float getWidth() {
    return CImGuiJNI.ImGuiShrinkWidthItem_Width_get(swigCPtr, this);
  }

  public ImGuiShrinkWidthItem() {
    this(CImGuiJNI.new_ImGuiShrinkWidthItem(), true);
  }

}
