/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiTabBar {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiTabBar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiTabBar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiTabBar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTabs(ImVector_ImGuiTabItem value) {
    CImGuiJNI.ImGuiTabBar_Tabs_set(swigCPtr, this, ImVector_ImGuiTabItem.getCPtr(value), value);
  }

  public ImVector_ImGuiTabItem getTabs() {
    long cPtr = CImGuiJNI.ImGuiTabBar_Tabs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiTabItem(cPtr, false);
  }

  public void setID(long value) {
    CImGuiJNI.ImGuiTabBar_ID_set(swigCPtr, this, value);
  }

  public long getID() {
    return CImGuiJNI.ImGuiTabBar_ID_get(swigCPtr, this);
  }

  public void setSelectedTabId(long value) {
    CImGuiJNI.ImGuiTabBar_SelectedTabId_set(swigCPtr, this, value);
  }

  public long getSelectedTabId() {
    return CImGuiJNI.ImGuiTabBar_SelectedTabId_get(swigCPtr, this);
  }

  public void setNextSelectedTabId(long value) {
    CImGuiJNI.ImGuiTabBar_NextSelectedTabId_set(swigCPtr, this, value);
  }

  public long getNextSelectedTabId() {
    return CImGuiJNI.ImGuiTabBar_NextSelectedTabId_get(swigCPtr, this);
  }

  public void setVisibleTabId(long value) {
    CImGuiJNI.ImGuiTabBar_VisibleTabId_set(swigCPtr, this, value);
  }

  public long getVisibleTabId() {
    return CImGuiJNI.ImGuiTabBar_VisibleTabId_get(swigCPtr, this);
  }

  public void setCurrFrameVisible(int value) {
    CImGuiJNI.ImGuiTabBar_CurrFrameVisible_set(swigCPtr, this, value);
  }

  public int getCurrFrameVisible() {
    return CImGuiJNI.ImGuiTabBar_CurrFrameVisible_get(swigCPtr, this);
  }

  public void setPrevFrameVisible(int value) {
    CImGuiJNI.ImGuiTabBar_PrevFrameVisible_set(swigCPtr, this, value);
  }

  public int getPrevFrameVisible() {
    return CImGuiJNI.ImGuiTabBar_PrevFrameVisible_get(swigCPtr, this);
  }

  public void setBarRect(ImRect value) {
    CImGuiJNI.ImGuiTabBar_BarRect_set(swigCPtr, this, ImRect.getCPtr(value), value);
  }

  public ImRect getBarRect() {
    long cPtr = CImGuiJNI.ImGuiTabBar_BarRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImRect(cPtr, false);
  }

  public void setLastTabContentHeight(float value) {
    CImGuiJNI.ImGuiTabBar_LastTabContentHeight_set(swigCPtr, this, value);
  }

  public float getLastTabContentHeight() {
    return CImGuiJNI.ImGuiTabBar_LastTabContentHeight_get(swigCPtr, this);
  }

  public void setOffsetMax(float value) {
    CImGuiJNI.ImGuiTabBar_OffsetMax_set(swigCPtr, this, value);
  }

  public float getOffsetMax() {
    return CImGuiJNI.ImGuiTabBar_OffsetMax_get(swigCPtr, this);
  }

  public void setOffsetMaxIdeal(float value) {
    CImGuiJNI.ImGuiTabBar_OffsetMaxIdeal_set(swigCPtr, this, value);
  }

  public float getOffsetMaxIdeal() {
    return CImGuiJNI.ImGuiTabBar_OffsetMaxIdeal_get(swigCPtr, this);
  }

  public void setOffsetNextTab(float value) {
    CImGuiJNI.ImGuiTabBar_OffsetNextTab_set(swigCPtr, this, value);
  }

  public float getOffsetNextTab() {
    return CImGuiJNI.ImGuiTabBar_OffsetNextTab_get(swigCPtr, this);
  }

  public void setScrollingAnim(float value) {
    CImGuiJNI.ImGuiTabBar_ScrollingAnim_set(swigCPtr, this, value);
  }

  public float getScrollingAnim() {
    return CImGuiJNI.ImGuiTabBar_ScrollingAnim_get(swigCPtr, this);
  }

  public void setScrollingTarget(float value) {
    CImGuiJNI.ImGuiTabBar_ScrollingTarget_set(swigCPtr, this, value);
  }

  public float getScrollingTarget() {
    return CImGuiJNI.ImGuiTabBar_ScrollingTarget_get(swigCPtr, this);
  }

  public void setScrollingTargetDistToVisibility(float value) {
    CImGuiJNI.ImGuiTabBar_ScrollingTargetDistToVisibility_set(swigCPtr, this, value);
  }

  public float getScrollingTargetDistToVisibility() {
    return CImGuiJNI.ImGuiTabBar_ScrollingTargetDistToVisibility_get(swigCPtr, this);
  }

  public void setScrollingSpeed(float value) {
    CImGuiJNI.ImGuiTabBar_ScrollingSpeed_set(swigCPtr, this, value);
  }

  public float getScrollingSpeed() {
    return CImGuiJNI.ImGuiTabBar_ScrollingSpeed_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    CImGuiJNI.ImGuiTabBar_Flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return CImGuiJNI.ImGuiTabBar_Flags_get(swigCPtr, this);
  }

  public void setReorderRequestTabId(long value) {
    CImGuiJNI.ImGuiTabBar_ReorderRequestTabId_set(swigCPtr, this, value);
  }

  public long getReorderRequestTabId() {
    return CImGuiJNI.ImGuiTabBar_ReorderRequestTabId_get(swigCPtr, this);
  }

  public void setReorderRequestDir(byte value) {
    CImGuiJNI.ImGuiTabBar_ReorderRequestDir_set(swigCPtr, this, value);
  }

  public byte getReorderRequestDir() {
    return CImGuiJNI.ImGuiTabBar_ReorderRequestDir_get(swigCPtr, this);
  }

  public void setWantLayout(boolean value) {
    CImGuiJNI.ImGuiTabBar_WantLayout_set(swigCPtr, this, value);
  }

  public boolean getWantLayout() {
    return CImGuiJNI.ImGuiTabBar_WantLayout_get(swigCPtr, this);
  }

  public void setVisibleTabWasSubmitted(boolean value) {
    CImGuiJNI.ImGuiTabBar_VisibleTabWasSubmitted_set(swigCPtr, this, value);
  }

  public boolean getVisibleTabWasSubmitted() {
    return CImGuiJNI.ImGuiTabBar_VisibleTabWasSubmitted_get(swigCPtr, this);
  }

  public void setLastTabItemIdx(short value) {
    CImGuiJNI.ImGuiTabBar_LastTabItemIdx_set(swigCPtr, this, value);
  }

  public short getLastTabItemIdx() {
    return CImGuiJNI.ImGuiTabBar_LastTabItemIdx_get(swigCPtr, this);
  }

  public void setFramePadding(ImVec2 value) {
    CImGuiJNI.ImGuiTabBar_FramePadding_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getFramePadding() {
    long cPtr = CImGuiJNI.ImGuiTabBar_FramePadding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setTabsNames(ImGuiTextBuffer value) {
    CImGuiJNI.ImGuiTabBar_TabsNames_set(swigCPtr, this, ImGuiTextBuffer.getCPtr(value), value);
  }

  public ImGuiTextBuffer getTabsNames() {
    long cPtr = CImGuiJNI.ImGuiTabBar_TabsNames_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiTextBuffer(cPtr, false);
  }

  public ImGuiTabBar() {
    this(CImGuiJNI.new_ImGuiTabBar(), true);
  }

}
