/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiNavForward {
  public final static int ImGuiNavForward_None = 0;
  public final static int ImGuiNavForward_ForwardQueued = ImGuiNavForward_None + 1;
  public final static int ImGuiNavForward_ForwardActive = ImGuiNavForward_ForwardQueued + 1;
}

