/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiInputTextCallbackData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiInputTextCallbackData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiInputTextCallbackData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiInputTextCallbackData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEventFlag(int value) {
    CImGuiJNI.ImGuiInputTextCallbackData_EventFlag_set(swigCPtr, this, value);
  }

  public int getEventFlag() {
    return CImGuiJNI.ImGuiInputTextCallbackData_EventFlag_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    CImGuiJNI.ImGuiInputTextCallbackData_Flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return CImGuiJNI.ImGuiInputTextCallbackData_Flags_get(swigCPtr, this);
  }

  public void setUserData(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiInputTextCallbackData_UserData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = CImGuiJNI.ImGuiInputTextCallbackData_UserData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setEventChar(int value) {
    CImGuiJNI.ImGuiInputTextCallbackData_EventChar_set(swigCPtr, this, value);
  }

  public int getEventChar() {
    return CImGuiJNI.ImGuiInputTextCallbackData_EventChar_get(swigCPtr, this);
  }

  public void setEventKey(int value) {
    CImGuiJNI.ImGuiInputTextCallbackData_EventKey_set(swigCPtr, this, value);
  }

  public int getEventKey() {
    return CImGuiJNI.ImGuiInputTextCallbackData_EventKey_get(swigCPtr, this);
  }

  public void setBuf(String value) {
    CImGuiJNI.ImGuiInputTextCallbackData_Buf_set(swigCPtr, this, value);
  }

  public String getBuf() {
    return CImGuiJNI.ImGuiInputTextCallbackData_Buf_get(swigCPtr, this);
  }

  public void setBufTextLen(int value) {
    CImGuiJNI.ImGuiInputTextCallbackData_BufTextLen_set(swigCPtr, this, value);
  }

  public int getBufTextLen() {
    return CImGuiJNI.ImGuiInputTextCallbackData_BufTextLen_get(swigCPtr, this);
  }

  public void setBufSize(int value) {
    CImGuiJNI.ImGuiInputTextCallbackData_BufSize_set(swigCPtr, this, value);
  }

  public int getBufSize() {
    return CImGuiJNI.ImGuiInputTextCallbackData_BufSize_get(swigCPtr, this);
  }

  public void setBufDirty(boolean value) {
    CImGuiJNI.ImGuiInputTextCallbackData_BufDirty_set(swigCPtr, this, value);
  }

  public boolean getBufDirty() {
    return CImGuiJNI.ImGuiInputTextCallbackData_BufDirty_get(swigCPtr, this);
  }

  public void setCursorPos(int value) {
    CImGuiJNI.ImGuiInputTextCallbackData_CursorPos_set(swigCPtr, this, value);
  }

  public int getCursorPos() {
    return CImGuiJNI.ImGuiInputTextCallbackData_CursorPos_get(swigCPtr, this);
  }

  public void setSelectionStart(int value) {
    CImGuiJNI.ImGuiInputTextCallbackData_SelectionStart_set(swigCPtr, this, value);
  }

  public int getSelectionStart() {
    return CImGuiJNI.ImGuiInputTextCallbackData_SelectionStart_get(swigCPtr, this);
  }

  public void setSelectionEnd(int value) {
    CImGuiJNI.ImGuiInputTextCallbackData_SelectionEnd_set(swigCPtr, this, value);
  }

  public int getSelectionEnd() {
    return CImGuiJNI.ImGuiInputTextCallbackData_SelectionEnd_get(swigCPtr, this);
  }

  public ImGuiInputTextCallbackData() {
    this(CImGuiJNI.new_ImGuiInputTextCallbackData(), true);
  }

}
