/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiDockNode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiDockNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiDockNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiDockNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setID(long value) {
    CImGuiJNI.ImGuiDockNode_ID_set(swigCPtr, this, value);
  }

  public long getID() {
    return CImGuiJNI.ImGuiDockNode_ID_get(swigCPtr, this);
  }

  public void setSharedFlags(int value) {
    CImGuiJNI.ImGuiDockNode_SharedFlags_set(swigCPtr, this, value);
  }

  public int getSharedFlags() {
    return CImGuiJNI.ImGuiDockNode_SharedFlags_get(swigCPtr, this);
  }

  public void setLocalFlags(int value) {
    CImGuiJNI.ImGuiDockNode_LocalFlags_set(swigCPtr, this, value);
  }

  public int getLocalFlags() {
    return CImGuiJNI.ImGuiDockNode_LocalFlags_get(swigCPtr, this);
  }

  public void setParentNode(ImGuiDockNode value) {
    CImGuiJNI.ImGuiDockNode_ParentNode_set(swigCPtr, this, ImGuiDockNode.getCPtr(value), value);
  }

  public ImGuiDockNode getParentNode() {
    long cPtr = CImGuiJNI.ImGuiDockNode_ParentNode_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiDockNode(cPtr, false);
  }

  public void setChildNodes(SWIGTYPE_p_p_ImGuiDockNode value) {
    CImGuiJNI.ImGuiDockNode_ChildNodes_set(swigCPtr, this, SWIGTYPE_p_p_ImGuiDockNode.getCPtr(value));
  }

  public SWIGTYPE_p_p_ImGuiDockNode getChildNodes() {
    long cPtr = CImGuiJNI.ImGuiDockNode_ChildNodes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_ImGuiDockNode(cPtr, false);
  }

  public void setWindows(ImVector_ImGuiWindowPtr value) {
    CImGuiJNI.ImGuiDockNode_Windows_set(swigCPtr, this, ImVector_ImGuiWindowPtr.getCPtr(value), value);
  }

  public ImVector_ImGuiWindowPtr getWindows() {
    long cPtr = CImGuiJNI.ImGuiDockNode_Windows_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiWindowPtr(cPtr, false);
  }

  public void setTabBar(ImGuiTabBar value) {
    CImGuiJNI.ImGuiDockNode_TabBar_set(swigCPtr, this, ImGuiTabBar.getCPtr(value), value);
  }

  public ImGuiTabBar getTabBar() {
    long cPtr = CImGuiJNI.ImGuiDockNode_TabBar_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiTabBar(cPtr, false);
  }

  public void setPos(ImVec2 value) {
    CImGuiJNI.ImGuiDockNode_Pos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getPos() {
    long cPtr = CImGuiJNI.ImGuiDockNode_Pos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setSize(ImVec2 value) {
    CImGuiJNI.ImGuiDockNode_Size_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getSize() {
    long cPtr = CImGuiJNI.ImGuiDockNode_Size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setSizeRef(ImVec2 value) {
    CImGuiJNI.ImGuiDockNode_SizeRef_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getSizeRef() {
    long cPtr = CImGuiJNI.ImGuiDockNode_SizeRef_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setSplitAxis(int value) {
    CImGuiJNI.ImGuiDockNode_SplitAxis_set(swigCPtr, this, value);
  }

  public int getSplitAxis() {
    return CImGuiJNI.ImGuiDockNode_SplitAxis_get(swigCPtr, this);
  }

  public void setWindowClass(ImGuiWindowClass value) {
    CImGuiJNI.ImGuiDockNode_WindowClass_set(swigCPtr, this, ImGuiWindowClass.getCPtr(value), value);
  }

  public ImGuiWindowClass getWindowClass() {
    long cPtr = CImGuiJNI.ImGuiDockNode_WindowClass_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindowClass(cPtr, false);
  }

  public void setState(int value) {
    CImGuiJNI.ImGuiDockNode_State_set(swigCPtr, this, value);
  }

  public int getState() {
    return CImGuiJNI.ImGuiDockNode_State_get(swigCPtr, this);
  }

  public void setHostWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiDockNode_HostWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getHostWindow() {
    long cPtr = CImGuiJNI.ImGuiDockNode_HostWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setVisibleWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiDockNode_VisibleWindow_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getVisibleWindow() {
    long cPtr = CImGuiJNI.ImGuiDockNode_VisibleWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setCentralNode(ImGuiDockNode value) {
    CImGuiJNI.ImGuiDockNode_CentralNode_set(swigCPtr, this, ImGuiDockNode.getCPtr(value), value);
  }

  public ImGuiDockNode getCentralNode() {
    long cPtr = CImGuiJNI.ImGuiDockNode_CentralNode_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiDockNode(cPtr, false);
  }

  public void setOnlyNodeWithWindows(ImGuiDockNode value) {
    CImGuiJNI.ImGuiDockNode_OnlyNodeWithWindows_set(swigCPtr, this, ImGuiDockNode.getCPtr(value), value);
  }

  public ImGuiDockNode getOnlyNodeWithWindows() {
    long cPtr = CImGuiJNI.ImGuiDockNode_OnlyNodeWithWindows_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiDockNode(cPtr, false);
  }

  public void setLastFrameAlive(int value) {
    CImGuiJNI.ImGuiDockNode_LastFrameAlive_set(swigCPtr, this, value);
  }

  public int getLastFrameAlive() {
    return CImGuiJNI.ImGuiDockNode_LastFrameAlive_get(swigCPtr, this);
  }

  public void setLastFrameActive(int value) {
    CImGuiJNI.ImGuiDockNode_LastFrameActive_set(swigCPtr, this, value);
  }

  public int getLastFrameActive() {
    return CImGuiJNI.ImGuiDockNode_LastFrameActive_get(swigCPtr, this);
  }

  public void setLastFrameFocused(int value) {
    CImGuiJNI.ImGuiDockNode_LastFrameFocused_set(swigCPtr, this, value);
  }

  public int getLastFrameFocused() {
    return CImGuiJNI.ImGuiDockNode_LastFrameFocused_get(swigCPtr, this);
  }

  public void setLastFocusedNodeId(long value) {
    CImGuiJNI.ImGuiDockNode_LastFocusedNodeId_set(swigCPtr, this, value);
  }

  public long getLastFocusedNodeId() {
    return CImGuiJNI.ImGuiDockNode_LastFocusedNodeId_get(swigCPtr, this);
  }

  public void setSelectedTabId(long value) {
    CImGuiJNI.ImGuiDockNode_SelectedTabId_set(swigCPtr, this, value);
  }

  public long getSelectedTabId() {
    return CImGuiJNI.ImGuiDockNode_SelectedTabId_get(swigCPtr, this);
  }

  public void setWantCloseTabId(long value) {
    CImGuiJNI.ImGuiDockNode_WantCloseTabId_set(swigCPtr, this, value);
  }

  public long getWantCloseTabId() {
    return CImGuiJNI.ImGuiDockNode_WantCloseTabId_get(swigCPtr, this);
  }

  public void setAuthorityForPos(int value) {
    CImGuiJNI.ImGuiDockNode_AuthorityForPos_set(swigCPtr, this, value);
  }

  public int getAuthorityForPos() {
    return CImGuiJNI.ImGuiDockNode_AuthorityForPos_get(swigCPtr, this);
  }

  public void setAuthorityForSize(int value) {
    CImGuiJNI.ImGuiDockNode_AuthorityForSize_set(swigCPtr, this, value);
  }

  public int getAuthorityForSize() {
    return CImGuiJNI.ImGuiDockNode_AuthorityForSize_get(swigCPtr, this);
  }

  public void setAuthorityForViewport(int value) {
    CImGuiJNI.ImGuiDockNode_AuthorityForViewport_set(swigCPtr, this, value);
  }

  public int getAuthorityForViewport() {
    return CImGuiJNI.ImGuiDockNode_AuthorityForViewport_get(swigCPtr, this);
  }

  public void setIsVisible(boolean value) {
    CImGuiJNI.ImGuiDockNode_IsVisible_set(swigCPtr, this, value);
  }

  public boolean getIsVisible() {
    return CImGuiJNI.ImGuiDockNode_IsVisible_get(swigCPtr, this);
  }

  public void setIsFocused(boolean value) {
    CImGuiJNI.ImGuiDockNode_IsFocused_set(swigCPtr, this, value);
  }

  public boolean getIsFocused() {
    return CImGuiJNI.ImGuiDockNode_IsFocused_get(swigCPtr, this);
  }

  public void setHasCloseButton(boolean value) {
    CImGuiJNI.ImGuiDockNode_HasCloseButton_set(swigCPtr, this, value);
  }

  public boolean getHasCloseButton() {
    return CImGuiJNI.ImGuiDockNode_HasCloseButton_get(swigCPtr, this);
  }

  public void setHasWindowMenuButton(boolean value) {
    CImGuiJNI.ImGuiDockNode_HasWindowMenuButton_set(swigCPtr, this, value);
  }

  public boolean getHasWindowMenuButton() {
    return CImGuiJNI.ImGuiDockNode_HasWindowMenuButton_get(swigCPtr, this);
  }

  public void setEnableCloseButton(boolean value) {
    CImGuiJNI.ImGuiDockNode_EnableCloseButton_set(swigCPtr, this, value);
  }

  public boolean getEnableCloseButton() {
    return CImGuiJNI.ImGuiDockNode_EnableCloseButton_get(swigCPtr, this);
  }

  public void setWantCloseAll(boolean value) {
    CImGuiJNI.ImGuiDockNode_WantCloseAll_set(swigCPtr, this, value);
  }

  public boolean getWantCloseAll() {
    return CImGuiJNI.ImGuiDockNode_WantCloseAll_get(swigCPtr, this);
  }

  public void setWantLockSizeOnce(boolean value) {
    CImGuiJNI.ImGuiDockNode_WantLockSizeOnce_set(swigCPtr, this, value);
  }

  public boolean getWantLockSizeOnce() {
    return CImGuiJNI.ImGuiDockNode_WantLockSizeOnce_get(swigCPtr, this);
  }

  public void setWantMouseMove(boolean value) {
    CImGuiJNI.ImGuiDockNode_WantMouseMove_set(swigCPtr, this, value);
  }

  public boolean getWantMouseMove() {
    return CImGuiJNI.ImGuiDockNode_WantMouseMove_get(swigCPtr, this);
  }

  public void setWantHiddenTabBarUpdate(boolean value) {
    CImGuiJNI.ImGuiDockNode_WantHiddenTabBarUpdate_set(swigCPtr, this, value);
  }

  public boolean getWantHiddenTabBarUpdate() {
    return CImGuiJNI.ImGuiDockNode_WantHiddenTabBarUpdate_get(swigCPtr, this);
  }

  public void setWantHiddenTabBarToggle(boolean value) {
    CImGuiJNI.ImGuiDockNode_WantHiddenTabBarToggle_set(swigCPtr, this, value);
  }

  public boolean getWantHiddenTabBarToggle() {
    return CImGuiJNI.ImGuiDockNode_WantHiddenTabBarToggle_get(swigCPtr, this);
  }

  public void setMarkedForPosSizeWrite(boolean value) {
    CImGuiJNI.ImGuiDockNode_MarkedForPosSizeWrite_set(swigCPtr, this, value);
  }

  public boolean getMarkedForPosSizeWrite() {
    return CImGuiJNI.ImGuiDockNode_MarkedForPosSizeWrite_get(swigCPtr, this);
  }

  public ImGuiDockNode() {
    this(CImGuiJNI.new_ImGuiDockNode(), true);
  }

}
