/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiNavMoveResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiNavMoveResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiNavMoveResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiNavMoveResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiNavMoveResult_Window_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getWindow() {
    long cPtr = CImGuiJNI.ImGuiNavMoveResult_Window_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setID(long value) {
    CImGuiJNI.ImGuiNavMoveResult_ID_set(swigCPtr, this, value);
  }

  public long getID() {
    return CImGuiJNI.ImGuiNavMoveResult_ID_get(swigCPtr, this);
  }

  public void setFocusScopeId(long value) {
    CImGuiJNI.ImGuiNavMoveResult_FocusScopeId_set(swigCPtr, this, value);
  }

  public long getFocusScopeId() {
    return CImGuiJNI.ImGuiNavMoveResult_FocusScopeId_get(swigCPtr, this);
  }

  public void setDistBox(float value) {
    CImGuiJNI.ImGuiNavMoveResult_DistBox_set(swigCPtr, this, value);
  }

  public float getDistBox() {
    return CImGuiJNI.ImGuiNavMoveResult_DistBox_get(swigCPtr, this);
  }

  public void setDistCenter(float value) {
    CImGuiJNI.ImGuiNavMoveResult_DistCenter_set(swigCPtr, this, value);
  }

  public float getDistCenter() {
    return CImGuiJNI.ImGuiNavMoveResult_DistCenter_get(swigCPtr, this);
  }

  public void setDistAxial(float value) {
    CImGuiJNI.ImGuiNavMoveResult_DistAxial_set(swigCPtr, this, value);
  }

  public float getDistAxial() {
    return CImGuiJNI.ImGuiNavMoveResult_DistAxial_get(swigCPtr, this);
  }

  public void setRectRel(ImRect value) {
    CImGuiJNI.ImGuiNavMoveResult_RectRel_set(swigCPtr, this, ImRect.getCPtr(value), value);
  }

  public ImRect getRectRel() {
    long cPtr = CImGuiJNI.ImGuiNavMoveResult_RectRel_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImRect(cPtr, false);
  }

  public ImGuiNavMoveResult() {
    this(CImGuiJNI.new_ImGuiNavMoveResult(), true);
  }

}
