/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiTabItem {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiTabItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiTabItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiTabItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setID(long value) {
    CImGuiJNI.ImGuiTabItem_ID_set(swigCPtr, this, value);
  }

  public long getID() {
    return CImGuiJNI.ImGuiTabItem_ID_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    CImGuiJNI.ImGuiTabItem_Flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return CImGuiJNI.ImGuiTabItem_Flags_get(swigCPtr, this);
  }

  public void setWindow(ImGuiWindow value) {
    CImGuiJNI.ImGuiTabItem_Window_set(swigCPtr, this, ImGuiWindow.getCPtr(value), value);
  }

  public ImGuiWindow getWindow() {
    long cPtr = CImGuiJNI.ImGuiTabItem_Window_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiWindow(cPtr, false);
  }

  public void setLastFrameVisible(int value) {
    CImGuiJNI.ImGuiTabItem_LastFrameVisible_set(swigCPtr, this, value);
  }

  public int getLastFrameVisible() {
    return CImGuiJNI.ImGuiTabItem_LastFrameVisible_get(swigCPtr, this);
  }

  public void setLastFrameSelected(int value) {
    CImGuiJNI.ImGuiTabItem_LastFrameSelected_set(swigCPtr, this, value);
  }

  public int getLastFrameSelected() {
    return CImGuiJNI.ImGuiTabItem_LastFrameSelected_get(swigCPtr, this);
  }

  public void setNameOffset(int value) {
    CImGuiJNI.ImGuiTabItem_NameOffset_set(swigCPtr, this, value);
  }

  public int getNameOffset() {
    return CImGuiJNI.ImGuiTabItem_NameOffset_get(swigCPtr, this);
  }

  public void setOffset(float value) {
    CImGuiJNI.ImGuiTabItem_Offset_set(swigCPtr, this, value);
  }

  public float getOffset() {
    return CImGuiJNI.ImGuiTabItem_Offset_get(swigCPtr, this);
  }

  public void setWidth(float value) {
    CImGuiJNI.ImGuiTabItem_Width_set(swigCPtr, this, value);
  }

  public float getWidth() {
    return CImGuiJNI.ImGuiTabItem_Width_get(swigCPtr, this);
  }

  public void setContentWidth(float value) {
    CImGuiJNI.ImGuiTabItem_ContentWidth_set(swigCPtr, this, value);
  }

  public float getContentWidth() {
    return CImGuiJNI.ImGuiTabItem_ContentWidth_get(swigCPtr, this);
  }

  public ImGuiTabItem() {
    this(CImGuiJNI.new_ImGuiTabItem(), true);
  }

}
