/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiKey_ {
  public final static int ImGuiKey_Tab = 0;
  public final static int ImGuiKey_LeftArrow = ImGuiKey_Tab + 1;
  public final static int ImGuiKey_RightArrow = ImGuiKey_LeftArrow + 1;
  public final static int ImGuiKey_UpArrow = ImGuiKey_RightArrow + 1;
  public final static int ImGuiKey_DownArrow = ImGuiKey_UpArrow + 1;
  public final static int ImGuiKey_PageUp = ImGuiKey_DownArrow + 1;
  public final static int ImGuiKey_PageDown = ImGuiKey_PageUp + 1;
  public final static int ImGuiKey_Home = ImGuiKey_PageDown + 1;
  public final static int ImGuiKey_End = ImGuiKey_Home + 1;
  public final static int ImGuiKey_Insert = ImGuiKey_End + 1;
  public final static int ImGuiKey_Delete = ImGuiKey_Insert + 1;
  public final static int ImGuiKey_Backspace = ImGuiKey_Delete + 1;
  public final static int ImGuiKey_Space = ImGuiKey_Backspace + 1;
  public final static int ImGuiKey_Enter = ImGuiKey_Space + 1;
  public final static int ImGuiKey_Escape = ImGuiKey_Enter + 1;
  public final static int ImGuiKey_KeyPadEnter = ImGuiKey_Escape + 1;
  public final static int ImGuiKey_A = ImGuiKey_KeyPadEnter + 1;
  public final static int ImGuiKey_C = ImGuiKey_A + 1;
  public final static int ImGuiKey_V = ImGuiKey_C + 1;
  public final static int ImGuiKey_X = ImGuiKey_V + 1;
  public final static int ImGuiKey_Y = ImGuiKey_X + 1;
  public final static int ImGuiKey_Z = ImGuiKey_Y + 1;
  public final static int ImGuiKey_COUNT = ImGuiKey_Z + 1;
}

