/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiViewport {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiViewport(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiViewport obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiViewport(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setID(long value) {
    CImGuiJNI.ImGuiViewport_ID_set(swigCPtr, this, value);
  }

  public long getID() {
    return CImGuiJNI.ImGuiViewport_ID_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    CImGuiJNI.ImGuiViewport_Flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return CImGuiJNI.ImGuiViewport_Flags_get(swigCPtr, this);
  }

  public void setPos(ImVec2 value) {
    CImGuiJNI.ImGuiViewport_Pos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getPos() {
    long cPtr = CImGuiJNI.ImGuiViewport_Pos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setSize(ImVec2 value) {
    CImGuiJNI.ImGuiViewport_Size_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getSize() {
    long cPtr = CImGuiJNI.ImGuiViewport_Size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setWorkOffsetMin(ImVec2 value) {
    CImGuiJNI.ImGuiViewport_WorkOffsetMin_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getWorkOffsetMin() {
    long cPtr = CImGuiJNI.ImGuiViewport_WorkOffsetMin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setWorkOffsetMax(ImVec2 value) {
    CImGuiJNI.ImGuiViewport_WorkOffsetMax_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getWorkOffsetMax() {
    long cPtr = CImGuiJNI.ImGuiViewport_WorkOffsetMax_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setDpiScale(float value) {
    CImGuiJNI.ImGuiViewport_DpiScale_set(swigCPtr, this, value);
  }

  public float getDpiScale() {
    return CImGuiJNI.ImGuiViewport_DpiScale_get(swigCPtr, this);
  }

  public void setDrawData(ImDrawData value) {
    CImGuiJNI.ImGuiViewport_DrawData_set(swigCPtr, this, ImDrawData.getCPtr(value), value);
  }

  public ImDrawData getDrawData() {
    long cPtr = CImGuiJNI.ImGuiViewport_DrawData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawData(cPtr, false);
  }

  public void setParentViewportId(long value) {
    CImGuiJNI.ImGuiViewport_ParentViewportId_set(swigCPtr, this, value);
  }

  public long getParentViewportId() {
    return CImGuiJNI.ImGuiViewport_ParentViewportId_get(swigCPtr, this);
  }

  public void setRendererUserData(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiViewport_RendererUserData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getRendererUserData() {
    long cPtr = CImGuiJNI.ImGuiViewport_RendererUserData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setPlatformUserData(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiViewport_PlatformUserData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPlatformUserData() {
    long cPtr = CImGuiJNI.ImGuiViewport_PlatformUserData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setPlatformHandle(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiViewport_PlatformHandle_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPlatformHandle() {
    long cPtr = CImGuiJNI.ImGuiViewport_PlatformHandle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setPlatformHandleRaw(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiViewport_PlatformHandleRaw_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPlatformHandleRaw() {
    long cPtr = CImGuiJNI.ImGuiViewport_PlatformHandleRaw_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setPlatformRequestMove(boolean value) {
    CImGuiJNI.ImGuiViewport_PlatformRequestMove_set(swigCPtr, this, value);
  }

  public boolean getPlatformRequestMove() {
    return CImGuiJNI.ImGuiViewport_PlatformRequestMove_get(swigCPtr, this);
  }

  public void setPlatformRequestResize(boolean value) {
    CImGuiJNI.ImGuiViewport_PlatformRequestResize_set(swigCPtr, this, value);
  }

  public boolean getPlatformRequestResize() {
    return CImGuiJNI.ImGuiViewport_PlatformRequestResize_get(swigCPtr, this);
  }

  public void setPlatformRequestClose(boolean value) {
    CImGuiJNI.ImGuiViewport_PlatformRequestClose_set(swigCPtr, this, value);
  }

  public boolean getPlatformRequestClose() {
    return CImGuiJNI.ImGuiViewport_PlatformRequestClose_get(swigCPtr, this);
  }

  public ImGuiViewport() {
    this(CImGuiJNI.new_ImGuiViewport(), true);
  }

}
