/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiSettingsHandler {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiSettingsHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiSettingsHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiSettingsHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTypeName(String value) {
    CImGuiJNI.ImGuiSettingsHandler_TypeName_set(swigCPtr, this, value);
  }

  public String getTypeName() {
    return CImGuiJNI.ImGuiSettingsHandler_TypeName_get(swigCPtr, this);
  }

  public void setTypeHash(long value) {
    CImGuiJNI.ImGuiSettingsHandler_TypeHash_set(swigCPtr, this, value);
  }

  public long getTypeHash() {
    return CImGuiJNI.ImGuiSettingsHandler_TypeHash_get(swigCPtr, this);
  }

  public void setClearAllFn(SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler__void value) {
    CImGuiJNI.ImGuiSettingsHandler_ClearAllFn_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler__void getClearAllFn() {
    long cPtr = CImGuiJNI.ImGuiSettingsHandler_ClearAllFn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler__void(cPtr, false);
  }

  public void setReadInitFn(SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler__void value) {
    CImGuiJNI.ImGuiSettingsHandler_ReadInitFn_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler__void getReadInitFn() {
    long cPtr = CImGuiJNI.ImGuiSettingsHandler_ReadInitFn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler__void(cPtr, false);
  }

  public void setReadOpenFn(SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler_p_q_const__char__p_void value) {
    CImGuiJNI.ImGuiSettingsHandler_ReadOpenFn_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler_p_q_const__char__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler_p_q_const__char__p_void getReadOpenFn() {
    long cPtr = CImGuiJNI.ImGuiSettingsHandler_ReadOpenFn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler_p_q_const__char__p_void(cPtr, false);
  }

  public void setReadLineFn(SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler_p_void_p_q_const__char__void value) {
    CImGuiJNI.ImGuiSettingsHandler_ReadLineFn_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler_p_void_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler_p_void_p_q_const__char__void getReadLineFn() {
    long cPtr = CImGuiJNI.ImGuiSettingsHandler_ReadLineFn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler_p_void_p_q_const__char__void(cPtr, false);
  }

  public void setApplyAllFn(SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler__void value) {
    CImGuiJNI.ImGuiSettingsHandler_ApplyAllFn_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler__void getApplyAllFn() {
    long cPtr = CImGuiJNI.ImGuiSettingsHandler_ApplyAllFn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler__void(cPtr, false);
  }

  public void setWriteAllFn(SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler_p_ImGuiTextBuffer__void value) {
    CImGuiJNI.ImGuiSettingsHandler_WriteAllFn_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler_p_ImGuiTextBuffer__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler_p_ImGuiTextBuffer__void getWriteAllFn() {
    long cPtr = CImGuiJNI.ImGuiSettingsHandler_WriteAllFn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiContext_p_ImGuiSettingsHandler_p_ImGuiTextBuffer__void(cPtr, false);
  }

  public void setUserData(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiSettingsHandler_UserData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = CImGuiJNI.ImGuiSettingsHandler_UserData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public ImGuiSettingsHandler() {
    this(CImGuiJNI.new_ImGuiSettingsHandler(), true);
  }

}
