/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiTextFilter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiTextFilter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiTextFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiTextFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInputBuf(String value) {
    CImGuiJNI.ImGuiTextFilter_InputBuf_set(swigCPtr, this, value);
  }

  public String getInputBuf() {
    return CImGuiJNI.ImGuiTextFilter_InputBuf_get(swigCPtr, this);
  }

  public void setFilters(ImVector_ImGuiTextRange value) {
    CImGuiJNI.ImGuiTextFilter_Filters_set(swigCPtr, this, ImVector_ImGuiTextRange.getCPtr(value), value);
  }

  public ImVector_ImGuiTextRange getFilters() {
    long cPtr = CImGuiJNI.ImGuiTextFilter_Filters_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiTextRange(cPtr, false);
  }

  public void setCountGrep(int value) {
    CImGuiJNI.ImGuiTextFilter_CountGrep_set(swigCPtr, this, value);
  }

  public int getCountGrep() {
    return CImGuiJNI.ImGuiTextFilter_CountGrep_get(swigCPtr, this);
  }

  public ImGuiTextFilter() {
    this(CImGuiJNI.new_ImGuiTextFilter(), true);
  }

}
