/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public final class ImGuiDockNodeState {
  public final static int ImGuiDockNodeState_Unknown = 0;
  public final static int ImGuiDockNodeState_HostWindowHiddenBecauseSingleWindow = ImGuiDockNodeState_Unknown + 1;
  public final static int ImGuiDockNodeState_HostWindowHiddenBecauseWindowsAreResizing = ImGuiDockNodeState_HostWindowHiddenBecauseSingleWindow + 1;
  public final static int ImGuiDockNodeState_HostWindowVisible = ImGuiDockNodeState_HostWindowHiddenBecauseWindowsAreResizing + 1;
}

