/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiIO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiIO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiIO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiIO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setConfigFlags(int value) {
    CImGuiJNI.ImGuiIO_ConfigFlags_set(swigCPtr, this, value);
  }

  public int getConfigFlags() {
    return CImGuiJNI.ImGuiIO_ConfigFlags_get(swigCPtr, this);
  }

  public void setBackendFlags(int value) {
    CImGuiJNI.ImGuiIO_BackendFlags_set(swigCPtr, this, value);
  }

  public int getBackendFlags() {
    return CImGuiJNI.ImGuiIO_BackendFlags_get(swigCPtr, this);
  }

  public void setDisplaySize(ImVec2 value) {
    CImGuiJNI.ImGuiIO_DisplaySize_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getDisplaySize() {
    long cPtr = CImGuiJNI.ImGuiIO_DisplaySize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setDeltaTime(float value) {
    CImGuiJNI.ImGuiIO_DeltaTime_set(swigCPtr, this, value);
  }

  public float getDeltaTime() {
    return CImGuiJNI.ImGuiIO_DeltaTime_get(swigCPtr, this);
  }

  public void setIniSavingRate(float value) {
    CImGuiJNI.ImGuiIO_IniSavingRate_set(swigCPtr, this, value);
  }

  public float getIniSavingRate() {
    return CImGuiJNI.ImGuiIO_IniSavingRate_get(swigCPtr, this);
  }

  public void setIniFilename(String value) {
    CImGuiJNI.ImGuiIO_IniFilename_set(swigCPtr, this, value);
  }

  public String getIniFilename() {
    return CImGuiJNI.ImGuiIO_IniFilename_get(swigCPtr, this);
  }

  public void setLogFilename(String value) {
    CImGuiJNI.ImGuiIO_LogFilename_set(swigCPtr, this, value);
  }

  public String getLogFilename() {
    return CImGuiJNI.ImGuiIO_LogFilename_get(swigCPtr, this);
  }

  public void setMouseDoubleClickTime(float value) {
    CImGuiJNI.ImGuiIO_MouseDoubleClickTime_set(swigCPtr, this, value);
  }

  public float getMouseDoubleClickTime() {
    return CImGuiJNI.ImGuiIO_MouseDoubleClickTime_get(swigCPtr, this);
  }

  public void setMouseDoubleClickMaxDist(float value) {
    CImGuiJNI.ImGuiIO_MouseDoubleClickMaxDist_set(swigCPtr, this, value);
  }

  public float getMouseDoubleClickMaxDist() {
    return CImGuiJNI.ImGuiIO_MouseDoubleClickMaxDist_get(swigCPtr, this);
  }

  public void setMouseDragThreshold(float value) {
    CImGuiJNI.ImGuiIO_MouseDragThreshold_set(swigCPtr, this, value);
  }

  public float getMouseDragThreshold() {
    return CImGuiJNI.ImGuiIO_MouseDragThreshold_get(swigCPtr, this);
  }

  public void setKeyMap(SWIGTYPE_p_int value) {
    CImGuiJNI.ImGuiIO_KeyMap_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getKeyMap() {
    long cPtr = CImGuiJNI.ImGuiIO_KeyMap_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setKeyRepeatDelay(float value) {
    CImGuiJNI.ImGuiIO_KeyRepeatDelay_set(swigCPtr, this, value);
  }

  public float getKeyRepeatDelay() {
    return CImGuiJNI.ImGuiIO_KeyRepeatDelay_get(swigCPtr, this);
  }

  public void setKeyRepeatRate(float value) {
    CImGuiJNI.ImGuiIO_KeyRepeatRate_set(swigCPtr, this, value);
  }

  public float getKeyRepeatRate() {
    return CImGuiJNI.ImGuiIO_KeyRepeatRate_get(swigCPtr, this);
  }

  public void setUserData(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiIO_UserData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = CImGuiJNI.ImGuiIO_UserData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setFonts(ImFontAtlas value) {
    CImGuiJNI.ImGuiIO_Fonts_set(swigCPtr, this, ImFontAtlas.getCPtr(value), value);
  }

  public ImFontAtlas getFonts() {
    long cPtr = CImGuiJNI.ImGuiIO_Fonts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImFontAtlas(cPtr, false);
  }

  public void setFontGlobalScale(float value) {
    CImGuiJNI.ImGuiIO_FontGlobalScale_set(swigCPtr, this, value);
  }

  public float getFontGlobalScale() {
    return CImGuiJNI.ImGuiIO_FontGlobalScale_get(swigCPtr, this);
  }

  public void setFontAllowUserScaling(boolean value) {
    CImGuiJNI.ImGuiIO_FontAllowUserScaling_set(swigCPtr, this, value);
  }

  public boolean getFontAllowUserScaling() {
    return CImGuiJNI.ImGuiIO_FontAllowUserScaling_get(swigCPtr, this);
  }

  public void setFontDefault(ImFont value) {
    CImGuiJNI.ImGuiIO_FontDefault_set(swigCPtr, this, ImFont.getCPtr(value), value);
  }

  public ImFont getFontDefault() {
    long cPtr = CImGuiJNI.ImGuiIO_FontDefault_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImFont(cPtr, false);
  }

  public void setDisplayFramebufferScale(ImVec2 value) {
    CImGuiJNI.ImGuiIO_DisplayFramebufferScale_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getDisplayFramebufferScale() {
    long cPtr = CImGuiJNI.ImGuiIO_DisplayFramebufferScale_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setMouseDrawCursor(boolean value) {
    CImGuiJNI.ImGuiIO_MouseDrawCursor_set(swigCPtr, this, value);
  }

  public boolean getMouseDrawCursor() {
    return CImGuiJNI.ImGuiIO_MouseDrawCursor_get(swigCPtr, this);
  }

  public void setConfigMacOSXBehaviors(boolean value) {
    CImGuiJNI.ImGuiIO_ConfigMacOSXBehaviors_set(swigCPtr, this, value);
  }

  public boolean getConfigMacOSXBehaviors() {
    return CImGuiJNI.ImGuiIO_ConfigMacOSXBehaviors_get(swigCPtr, this);
  }

  public void setConfigInputTextCursorBlink(boolean value) {
    CImGuiJNI.ImGuiIO_ConfigInputTextCursorBlink_set(swigCPtr, this, value);
  }

  public boolean getConfigInputTextCursorBlink() {
    return CImGuiJNI.ImGuiIO_ConfigInputTextCursorBlink_get(swigCPtr, this);
  }

  public void setConfigWindowsResizeFromEdges(boolean value) {
    CImGuiJNI.ImGuiIO_ConfigWindowsResizeFromEdges_set(swigCPtr, this, value);
  }

  public boolean getConfigWindowsResizeFromEdges() {
    return CImGuiJNI.ImGuiIO_ConfigWindowsResizeFromEdges_get(swigCPtr, this);
  }

  public void setConfigWindowsMoveFromTitleBarOnly(boolean value) {
    CImGuiJNI.ImGuiIO_ConfigWindowsMoveFromTitleBarOnly_set(swigCPtr, this, value);
  }

  public boolean getConfigWindowsMoveFromTitleBarOnly() {
    return CImGuiJNI.ImGuiIO_ConfigWindowsMoveFromTitleBarOnly_get(swigCPtr, this);
  }

  public void setConfigWindowsMemoryCompactTimer(float value) {
    CImGuiJNI.ImGuiIO_ConfigWindowsMemoryCompactTimer_set(swigCPtr, this, value);
  }

  public float getConfigWindowsMemoryCompactTimer() {
    return CImGuiJNI.ImGuiIO_ConfigWindowsMemoryCompactTimer_get(swigCPtr, this);
  }

  public void setBackendPlatformName(String value) {
    CImGuiJNI.ImGuiIO_BackendPlatformName_set(swigCPtr, this, value);
  }

  public String getBackendPlatformName() {
    return CImGuiJNI.ImGuiIO_BackendPlatformName_get(swigCPtr, this);
  }

  public void setBackendRendererName(String value) {
    CImGuiJNI.ImGuiIO_BackendRendererName_set(swigCPtr, this, value);
  }

  public String getBackendRendererName() {
    return CImGuiJNI.ImGuiIO_BackendRendererName_get(swigCPtr, this);
  }

  public void setBackendPlatformUserData(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiIO_BackendPlatformUserData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getBackendPlatformUserData() {
    long cPtr = CImGuiJNI.ImGuiIO_BackendPlatformUserData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setBackendRendererUserData(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiIO_BackendRendererUserData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getBackendRendererUserData() {
    long cPtr = CImGuiJNI.ImGuiIO_BackendRendererUserData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setBackendLanguageUserData(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiIO_BackendLanguageUserData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getBackendLanguageUserData() {
    long cPtr = CImGuiJNI.ImGuiIO_BackendLanguageUserData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setGetClipboardTextFn(SWIGTYPE_p_f_p_void__p_char value) {
    CImGuiJNI.ImGuiIO_GetClipboardTextFn_set(swigCPtr, this, SWIGTYPE_p_f_p_void__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__p_char getGetClipboardTextFn() {
    long cPtr = CImGuiJNI.ImGuiIO_GetClipboardTextFn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__p_char(cPtr, false);
  }

  public void setSetClipboardTextFn(SWIGTYPE_p_f_p_void_p_q_const__char__void value) {
    CImGuiJNI.ImGuiIO_SetClipboardTextFn_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_q_const__char__void getSetClipboardTextFn() {
    long cPtr = CImGuiJNI.ImGuiIO_SetClipboardTextFn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_q_const__char__void(cPtr, false);
  }

  public void setClipboardUserData(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiIO_ClipboardUserData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getClipboardUserData() {
    long cPtr = CImGuiJNI.ImGuiIO_ClipboardUserData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setImeSetInputScreenPosFn(SWIGTYPE_p_f_int_int__void value) {
    CImGuiJNI.ImGuiIO_ImeSetInputScreenPosFn_set(swigCPtr, this, SWIGTYPE_p_f_int_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_int__void getImeSetInputScreenPosFn() {
    long cPtr = CImGuiJNI.ImGuiIO_ImeSetInputScreenPosFn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_int__void(cPtr, false);
  }

  public void setImeWindowHandle(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiIO_ImeWindowHandle_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getImeWindowHandle() {
    long cPtr = CImGuiJNI.ImGuiIO_ImeWindowHandle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setRenderDrawListsFnUnused(SWIGTYPE_p_void value) {
    CImGuiJNI.ImGuiIO_RenderDrawListsFnUnused_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getRenderDrawListsFnUnused() {
    long cPtr = CImGuiJNI.ImGuiIO_RenderDrawListsFnUnused_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setMousePos(ImVec2 value) {
    CImGuiJNI.ImGuiIO_MousePos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getMousePos() {
    long cPtr = CImGuiJNI.ImGuiIO_MousePos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setMouseDown(SWIGTYPE_p_bool value) {
    CImGuiJNI.ImGuiIO_MouseDown_set(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(value));
  }

  public SWIGTYPE_p_bool getMouseDown() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseDown_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bool(cPtr, false);
  }

  public void setMouseWheel(float value) {
    CImGuiJNI.ImGuiIO_MouseWheel_set(swigCPtr, this, value);
  }

  public float getMouseWheel() {
    return CImGuiJNI.ImGuiIO_MouseWheel_get(swigCPtr, this);
  }

  public void setMouseWheelH(float value) {
    CImGuiJNI.ImGuiIO_MouseWheelH_set(swigCPtr, this, value);
  }

  public float getMouseWheelH() {
    return CImGuiJNI.ImGuiIO_MouseWheelH_get(swigCPtr, this);
  }

  public void setKeyCtrl(boolean value) {
    CImGuiJNI.ImGuiIO_KeyCtrl_set(swigCPtr, this, value);
  }

  public boolean getKeyCtrl() {
    return CImGuiJNI.ImGuiIO_KeyCtrl_get(swigCPtr, this);
  }

  public void setKeyShift(boolean value) {
    CImGuiJNI.ImGuiIO_KeyShift_set(swigCPtr, this, value);
  }

  public boolean getKeyShift() {
    return CImGuiJNI.ImGuiIO_KeyShift_get(swigCPtr, this);
  }

  public void setKeyAlt(boolean value) {
    CImGuiJNI.ImGuiIO_KeyAlt_set(swigCPtr, this, value);
  }

  public boolean getKeyAlt() {
    return CImGuiJNI.ImGuiIO_KeyAlt_get(swigCPtr, this);
  }

  public void setKeySuper(boolean value) {
    CImGuiJNI.ImGuiIO_KeySuper_set(swigCPtr, this, value);
  }

  public boolean getKeySuper() {
    return CImGuiJNI.ImGuiIO_KeySuper_get(swigCPtr, this);
  }

  public void setKeysDown(SWIGTYPE_p_bool value) {
    CImGuiJNI.ImGuiIO_KeysDown_set(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(value));
  }

  public SWIGTYPE_p_bool getKeysDown() {
    long cPtr = CImGuiJNI.ImGuiIO_KeysDown_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bool(cPtr, false);
  }

  public void setNavInputs(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiIO_NavInputs_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getNavInputs() {
    long cPtr = CImGuiJNI.ImGuiIO_NavInputs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setWantCaptureMouse(boolean value) {
    CImGuiJNI.ImGuiIO_WantCaptureMouse_set(swigCPtr, this, value);
  }

  public boolean getWantCaptureMouse() {
    return CImGuiJNI.ImGuiIO_WantCaptureMouse_get(swigCPtr, this);
  }

  public void setWantCaptureKeyboard(boolean value) {
    CImGuiJNI.ImGuiIO_WantCaptureKeyboard_set(swigCPtr, this, value);
  }

  public boolean getWantCaptureKeyboard() {
    return CImGuiJNI.ImGuiIO_WantCaptureKeyboard_get(swigCPtr, this);
  }

  public void setWantTextInput(boolean value) {
    CImGuiJNI.ImGuiIO_WantTextInput_set(swigCPtr, this, value);
  }

  public boolean getWantTextInput() {
    return CImGuiJNI.ImGuiIO_WantTextInput_get(swigCPtr, this);
  }

  public void setWantSetMousePos(boolean value) {
    CImGuiJNI.ImGuiIO_WantSetMousePos_set(swigCPtr, this, value);
  }

  public boolean getWantSetMousePos() {
    return CImGuiJNI.ImGuiIO_WantSetMousePos_get(swigCPtr, this);
  }

  public void setWantSaveIniSettings(boolean value) {
    CImGuiJNI.ImGuiIO_WantSaveIniSettings_set(swigCPtr, this, value);
  }

  public boolean getWantSaveIniSettings() {
    return CImGuiJNI.ImGuiIO_WantSaveIniSettings_get(swigCPtr, this);
  }

  public void setNavActive(boolean value) {
    CImGuiJNI.ImGuiIO_NavActive_set(swigCPtr, this, value);
  }

  public boolean getNavActive() {
    return CImGuiJNI.ImGuiIO_NavActive_get(swigCPtr, this);
  }

  public void setNavVisible(boolean value) {
    CImGuiJNI.ImGuiIO_NavVisible_set(swigCPtr, this, value);
  }

  public boolean getNavVisible() {
    return CImGuiJNI.ImGuiIO_NavVisible_get(swigCPtr, this);
  }

  public void setFramerate(float value) {
    CImGuiJNI.ImGuiIO_Framerate_set(swigCPtr, this, value);
  }

  public float getFramerate() {
    return CImGuiJNI.ImGuiIO_Framerate_get(swigCPtr, this);
  }

  public void setMetricsRenderVertices(int value) {
    CImGuiJNI.ImGuiIO_MetricsRenderVertices_set(swigCPtr, this, value);
  }

  public int getMetricsRenderVertices() {
    return CImGuiJNI.ImGuiIO_MetricsRenderVertices_get(swigCPtr, this);
  }

  public void setMetricsRenderIndices(int value) {
    CImGuiJNI.ImGuiIO_MetricsRenderIndices_set(swigCPtr, this, value);
  }

  public int getMetricsRenderIndices() {
    return CImGuiJNI.ImGuiIO_MetricsRenderIndices_get(swigCPtr, this);
  }

  public void setMetricsRenderWindows(int value) {
    CImGuiJNI.ImGuiIO_MetricsRenderWindows_set(swigCPtr, this, value);
  }

  public int getMetricsRenderWindows() {
    return CImGuiJNI.ImGuiIO_MetricsRenderWindows_get(swigCPtr, this);
  }

  public void setMetricsActiveWindows(int value) {
    CImGuiJNI.ImGuiIO_MetricsActiveWindows_set(swigCPtr, this, value);
  }

  public int getMetricsActiveWindows() {
    return CImGuiJNI.ImGuiIO_MetricsActiveWindows_get(swigCPtr, this);
  }

  public void setMetricsActiveAllocations(int value) {
    CImGuiJNI.ImGuiIO_MetricsActiveAllocations_set(swigCPtr, this, value);
  }

  public int getMetricsActiveAllocations() {
    return CImGuiJNI.ImGuiIO_MetricsActiveAllocations_get(swigCPtr, this);
  }

  public void setMouseDelta(ImVec2 value) {
    CImGuiJNI.ImGuiIO_MouseDelta_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getMouseDelta() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseDelta_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setMousePosPrev(ImVec2 value) {
    CImGuiJNI.ImGuiIO_MousePosPrev_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getMousePosPrev() {
    long cPtr = CImGuiJNI.ImGuiIO_MousePosPrev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setMouseClickedPos(ImVec2 value) {
    CImGuiJNI.ImGuiIO_MouseClickedPos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getMouseClickedPos() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseClickedPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setMouseClickedTime(SWIGTYPE_p_double value) {
    CImGuiJNI.ImGuiIO_MouseClickedTime_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getMouseClickedTime() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseClickedTime_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setMouseClicked(SWIGTYPE_p_bool value) {
    CImGuiJNI.ImGuiIO_MouseClicked_set(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(value));
  }

  public SWIGTYPE_p_bool getMouseClicked() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseClicked_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bool(cPtr, false);
  }

  public void setMouseDoubleClicked(SWIGTYPE_p_bool value) {
    CImGuiJNI.ImGuiIO_MouseDoubleClicked_set(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(value));
  }

  public SWIGTYPE_p_bool getMouseDoubleClicked() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseDoubleClicked_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bool(cPtr, false);
  }

  public void setMouseReleased(SWIGTYPE_p_bool value) {
    CImGuiJNI.ImGuiIO_MouseReleased_set(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(value));
  }

  public SWIGTYPE_p_bool getMouseReleased() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseReleased_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bool(cPtr, false);
  }

  public void setMouseDownOwned(SWIGTYPE_p_bool value) {
    CImGuiJNI.ImGuiIO_MouseDownOwned_set(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(value));
  }

  public SWIGTYPE_p_bool getMouseDownOwned() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseDownOwned_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bool(cPtr, false);
  }

  public void setMouseDownWasDoubleClick(SWIGTYPE_p_bool value) {
    CImGuiJNI.ImGuiIO_MouseDownWasDoubleClick_set(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(value));
  }

  public SWIGTYPE_p_bool getMouseDownWasDoubleClick() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseDownWasDoubleClick_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bool(cPtr, false);
  }

  public void setMouseDownDuration(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiIO_MouseDownDuration_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getMouseDownDuration() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseDownDuration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setMouseDownDurationPrev(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiIO_MouseDownDurationPrev_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getMouseDownDurationPrev() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseDownDurationPrev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setMouseDragMaxDistanceAbs(ImVec2 value) {
    CImGuiJNI.ImGuiIO_MouseDragMaxDistanceAbs_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getMouseDragMaxDistanceAbs() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseDragMaxDistanceAbs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setMouseDragMaxDistanceSqr(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiIO_MouseDragMaxDistanceSqr_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getMouseDragMaxDistanceSqr() {
    long cPtr = CImGuiJNI.ImGuiIO_MouseDragMaxDistanceSqr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setKeysDownDuration(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiIO_KeysDownDuration_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getKeysDownDuration() {
    long cPtr = CImGuiJNI.ImGuiIO_KeysDownDuration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setKeysDownDurationPrev(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiIO_KeysDownDurationPrev_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getKeysDownDurationPrev() {
    long cPtr = CImGuiJNI.ImGuiIO_KeysDownDurationPrev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setNavInputsDownDuration(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiIO_NavInputsDownDuration_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getNavInputsDownDuration() {
    long cPtr = CImGuiJNI.ImGuiIO_NavInputsDownDuration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setNavInputsDownDurationPrev(SWIGTYPE_p_float value) {
    CImGuiJNI.ImGuiIO_NavInputsDownDurationPrev_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getNavInputsDownDurationPrev() {
    long cPtr = CImGuiJNI.ImGuiIO_NavInputsDownDurationPrev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setInputQueueCharacters(ImVector_ImWchar value) {
    CImGuiJNI.ImGuiIO_InputQueueCharacters_set(swigCPtr, this, ImVector_ImWchar.getCPtr(value), value);
  }

  public ImVector_ImWchar getInputQueueCharacters() {
    long cPtr = CImGuiJNI.ImGuiIO_InputQueueCharacters_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImWchar(cPtr, false);
  }

  public ImGuiIO() {
    this(CImGuiJNI.new_ImGuiIO(), true);
  }

}
