/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiListClipper {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiListClipper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiListClipper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiListClipper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStartPosY(float value) {
    CImGuiJNI.ImGuiListClipper_StartPosY_set(swigCPtr, this, value);
  }

  public float getStartPosY() {
    return CImGuiJNI.ImGuiListClipper_StartPosY_get(swigCPtr, this);
  }

  public void setItemsHeight(float value) {
    CImGuiJNI.ImGuiListClipper_ItemsHeight_set(swigCPtr, this, value);
  }

  public float getItemsHeight() {
    return CImGuiJNI.ImGuiListClipper_ItemsHeight_get(swigCPtr, this);
  }

  public void setItemsCount(int value) {
    CImGuiJNI.ImGuiListClipper_ItemsCount_set(swigCPtr, this, value);
  }

  public int getItemsCount() {
    return CImGuiJNI.ImGuiListClipper_ItemsCount_get(swigCPtr, this);
  }

  public void setStepNo(int value) {
    CImGuiJNI.ImGuiListClipper_StepNo_set(swigCPtr, this, value);
  }

  public int getStepNo() {
    return CImGuiJNI.ImGuiListClipper_StepNo_get(swigCPtr, this);
  }

  public void setDisplayStart(int value) {
    CImGuiJNI.ImGuiListClipper_DisplayStart_set(swigCPtr, this, value);
  }

  public int getDisplayStart() {
    return CImGuiJNI.ImGuiListClipper_DisplayStart_get(swigCPtr, this);
  }

  public void setDisplayEnd(int value) {
    CImGuiJNI.ImGuiListClipper_DisplayEnd_set(swigCPtr, this, value);
  }

  public int getDisplayEnd() {
    return CImGuiJNI.ImGuiListClipper_DisplayEnd_get(swigCPtr, this);
  }

  public ImGuiListClipper() {
    this(CImGuiJNI.new_ImGuiListClipper(), true);
  }

}
