/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImGuiPlatformIO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImGuiPlatformIO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImGuiPlatformIO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImGuiPlatformIO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPlatform_CreateWindow(SWIGTYPE_p_f_p_ImGuiViewport__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_CreateWindow_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__void getPlatform_CreateWindow() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_CreateWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__void(cPtr, false);
  }

  public void setPlatform_DestroyWindow(SWIGTYPE_p_f_p_ImGuiViewport__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_DestroyWindow_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__void getPlatform_DestroyWindow() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_DestroyWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__void(cPtr, false);
  }

  public void setPlatform_ShowWindow(SWIGTYPE_p_f_p_ImGuiViewport__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_ShowWindow_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__void getPlatform_ShowWindow() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_ShowWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__void(cPtr, false);
  }

  public void setPlatform_SetWindowPos(SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_SetWindowPos_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void getPlatform_SetWindowPos() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_SetWindowPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void(cPtr, false);
  }

  public void setPlatform_GetWindowPos(SWIGTYPE_p_f_p_ImGuiViewport__ImVec2 value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_GetWindowPos_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__ImVec2.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__ImVec2 getPlatform_GetWindowPos() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_GetWindowPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__ImVec2(cPtr, false);
  }

  public void setPlatform_SetWindowSize(SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_SetWindowSize_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void getPlatform_SetWindowSize() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_SetWindowSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void(cPtr, false);
  }

  public void setPlatform_GetWindowSize(SWIGTYPE_p_f_p_ImGuiViewport__ImVec2 value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_GetWindowSize_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__ImVec2.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__ImVec2 getPlatform_GetWindowSize() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_GetWindowSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__ImVec2(cPtr, false);
  }

  public void setPlatform_SetWindowFocus(SWIGTYPE_p_f_p_ImGuiViewport__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_SetWindowFocus_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__void getPlatform_SetWindowFocus() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_SetWindowFocus_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__void(cPtr, false);
  }

  public void setPlatform_GetWindowFocus(SWIGTYPE_p_f_p_ImGuiViewport__bool value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_GetWindowFocus_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__bool.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__bool getPlatform_GetWindowFocus() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_GetWindowFocus_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__bool(cPtr, false);
  }

  public void setPlatform_GetWindowMinimized(SWIGTYPE_p_f_p_ImGuiViewport__bool value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_GetWindowMinimized_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__bool.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__bool getPlatform_GetWindowMinimized() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_GetWindowMinimized_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__bool(cPtr, false);
  }

  public void setPlatform_SetWindowTitle(SWIGTYPE_p_f_p_ImGuiViewport_p_q_const__char__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_SetWindowTitle_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport_p_q_const__char__void getPlatform_SetWindowTitle() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_SetWindowTitle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport_p_q_const__char__void(cPtr, false);
  }

  public void setPlatform_SetWindowAlpha(SWIGTYPE_p_f_p_ImGuiViewport_float__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_SetWindowAlpha_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport_float__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport_float__void getPlatform_SetWindowAlpha() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_SetWindowAlpha_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport_float__void(cPtr, false);
  }

  public void setPlatform_UpdateWindow(SWIGTYPE_p_f_p_ImGuiViewport__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_UpdateWindow_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__void getPlatform_UpdateWindow() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_UpdateWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__void(cPtr, false);
  }

  public void setPlatform_RenderWindow(SWIGTYPE_p_f_p_ImGuiViewport_p_void__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_RenderWindow_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport_p_void__void getPlatform_RenderWindow() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_RenderWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport_p_void__void(cPtr, false);
  }

  public void setPlatform_SwapBuffers(SWIGTYPE_p_f_p_ImGuiViewport_p_void__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_SwapBuffers_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport_p_void__void getPlatform_SwapBuffers() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_SwapBuffers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport_p_void__void(cPtr, false);
  }

  public void setPlatform_GetWindowDpiScale(SWIGTYPE_p_f_p_ImGuiViewport__float value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_GetWindowDpiScale_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__float.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__float getPlatform_GetWindowDpiScale() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_GetWindowDpiScale_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__float(cPtr, false);
  }

  public void setPlatform_OnChangedViewport(SWIGTYPE_p_f_p_ImGuiViewport__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_OnChangedViewport_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__void getPlatform_OnChangedViewport() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_OnChangedViewport_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__void(cPtr, false);
  }

  public void setPlatform_SetImeInputPos(SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_SetImeInputPos_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void getPlatform_SetImeInputPos() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_SetImeInputPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void(cPtr, false);
  }

  public void setPlatform_CreateVkSurface(SWIGTYPE_p_f_p_ImGuiViewport_uint64_t_p_q_const__void_p_uint64_t__int value) {
    CImGuiJNI.ImGuiPlatformIO_Platform_CreateVkSurface_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport_uint64_t_p_q_const__void_p_uint64_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport_uint64_t_p_q_const__void_p_uint64_t__int getPlatform_CreateVkSurface() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Platform_CreateVkSurface_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport_uint64_t_p_q_const__void_p_uint64_t__int(cPtr, false);
  }

  public void setRenderer_CreateWindow(SWIGTYPE_p_f_p_ImGuiViewport__void value) {
    CImGuiJNI.ImGuiPlatformIO_Renderer_CreateWindow_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__void getRenderer_CreateWindow() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Renderer_CreateWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__void(cPtr, false);
  }

  public void setRenderer_DestroyWindow(SWIGTYPE_p_f_p_ImGuiViewport__void value) {
    CImGuiJNI.ImGuiPlatformIO_Renderer_DestroyWindow_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport__void getRenderer_DestroyWindow() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Renderer_DestroyWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport__void(cPtr, false);
  }

  public void setRenderer_SetWindowSize(SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void value) {
    CImGuiJNI.ImGuiPlatformIO_Renderer_SetWindowSize_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void getRenderer_SetWindowSize() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Renderer_SetWindowSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport_ImVec2__void(cPtr, false);
  }

  public void setRenderer_RenderWindow(SWIGTYPE_p_f_p_ImGuiViewport_p_void__void value) {
    CImGuiJNI.ImGuiPlatformIO_Renderer_RenderWindow_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport_p_void__void getRenderer_RenderWindow() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Renderer_RenderWindow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport_p_void__void(cPtr, false);
  }

  public void setRenderer_SwapBuffers(SWIGTYPE_p_f_p_ImGuiViewport_p_void__void value) {
    CImGuiJNI.ImGuiPlatformIO_Renderer_SwapBuffers_set(swigCPtr, this, SWIGTYPE_p_f_p_ImGuiViewport_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_ImGuiViewport_p_void__void getRenderer_SwapBuffers() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Renderer_SwapBuffers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_ImGuiViewport_p_void__void(cPtr, false);
  }

  public void setMonitors(ImVector_ImGuiPlatformMonitor value) {
    CImGuiJNI.ImGuiPlatformIO_Monitors_set(swigCPtr, this, ImVector_ImGuiPlatformMonitor.getCPtr(value), value);
  }

  public ImVector_ImGuiPlatformMonitor getMonitors() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Monitors_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiPlatformMonitor(cPtr, false);
  }

  public void setMainViewport(ImGuiViewport value) {
    CImGuiJNI.ImGuiPlatformIO_MainViewport_set(swigCPtr, this, ImGuiViewport.getCPtr(value), value);
  }

  public ImGuiViewport getMainViewport() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_MainViewport_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiViewport(cPtr, false);
  }

  public void setViewports(ImVector_ImGuiViewportPtr value) {
    CImGuiJNI.ImGuiPlatformIO_Viewports_set(swigCPtr, this, ImVector_ImGuiViewportPtr.getCPtr(value), value);
  }

  public ImVector_ImGuiViewportPtr getViewports() {
    long cPtr = CImGuiJNI.ImGuiPlatformIO_Viewports_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiViewportPtr(cPtr, false);
  }

  public ImGuiPlatformIO() {
    this(CImGuiJNI.new_ImGuiPlatformIO(), true);
  }

}
