/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImPool_ImGuiTabBar {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImPool_ImGuiTabBar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImPool_ImGuiTabBar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImPool_ImGuiTabBar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBuf(ImVector_ImGuiTabBar value) {
    CImGuiJNI.ImPool_ImGuiTabBar_Buf_set(swigCPtr, this, ImVector_ImGuiTabBar.getCPtr(value), value);
  }

  public ImVector_ImGuiTabBar getBuf() {
    long cPtr = CImGuiJNI.ImPool_ImGuiTabBar_Buf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVector_ImGuiTabBar(cPtr, false);
  }

  public void setMap(ImGuiStorage value) {
    CImGuiJNI.ImPool_ImGuiTabBar_Map_set(swigCPtr, this, ImGuiStorage.getCPtr(value), value);
  }

  public ImGuiStorage getMap() {
    long cPtr = CImGuiJNI.ImPool_ImGuiTabBar_Map_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImGuiStorage(cPtr, false);
  }

  public void setFreeIdx(int value) {
    CImGuiJNI.ImPool_ImGuiTabBar_FreeIdx_set(swigCPtr, this, value);
  }

  public int getFreeIdx() {
    return CImGuiJNI.ImPool_ImGuiTabBar_FreeIdx_get(swigCPtr, this);
  }

  public ImPool_ImGuiTabBar() {
    this(CImGuiJNI.new_ImPool_ImGuiTabBar(), true);
  }

}
