/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImRect {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImRect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImRect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImRect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMin(ImVec2 value) {
    CImGuiJNI.ImRect_Min_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getMin() {
    long cPtr = CImGuiJNI.ImRect_Min_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setMax(ImVec2 value) {
    CImGuiJNI.ImRect_Max_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getMax() {
    long cPtr = CImGuiJNI.ImRect_Max_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public ImRect() {
    this(CImGuiJNI.new_ImRect(), true);
  }

}
