/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class ImVec2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImVec2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImVec2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_ImVec2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    CImGuiJNI.ImVec2_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return CImGuiJNI.ImVec2_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    CImGuiJNI.ImVec2_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return CImGuiJNI.ImVec2_y_get(swigCPtr, this);
  }

  public ImVec2() {
    this(CImGuiJNI.new_ImVec2(), true);
  }

}
