/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class StbTexteditRow {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public StbTexteditRow(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StbTexteditRow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_StbTexteditRow(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX0(float value) {
    CImGuiJNI.StbTexteditRow_x0_set(swigCPtr, this, value);
  }

  public float getX0() {
    return CImGuiJNI.StbTexteditRow_x0_get(swigCPtr, this);
  }

  public void setX1(float value) {
    CImGuiJNI.StbTexteditRow_x1_set(swigCPtr, this, value);
  }

  public float getX1() {
    return CImGuiJNI.StbTexteditRow_x1_get(swigCPtr, this);
  }

  public void setBaseline_y_delta(float value) {
    CImGuiJNI.StbTexteditRow_baseline_y_delta_set(swigCPtr, this, value);
  }

  public float getBaseline_y_delta() {
    return CImGuiJNI.StbTexteditRow_baseline_y_delta_get(swigCPtr, this);
  }

  public void setYmin(float value) {
    CImGuiJNI.StbTexteditRow_ymin_set(swigCPtr, this, value);
  }

  public float getYmin() {
    return CImGuiJNI.StbTexteditRow_ymin_get(swigCPtr, this);
  }

  public void setYmax(float value) {
    CImGuiJNI.StbTexteditRow_ymax_set(swigCPtr, this, value);
  }

  public float getYmax() {
    return CImGuiJNI.StbTexteditRow_ymax_get(swigCPtr, this);
  }

  public void setNum_chars(int value) {
    CImGuiJNI.StbTexteditRow_num_chars_set(swigCPtr, this, value);
  }

  public int getNum_chars() {
    return CImGuiJNI.StbTexteditRow_num_chars_get(swigCPtr, this);
  }

  public StbTexteditRow() {
    this(CImGuiJNI.new_StbTexteditRow(), true);
  }

}
