/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cimgui.internal;

public class StbUndoState {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public StbUndoState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StbUndoState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CImGuiJNI.delete_StbUndoState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUndo_rec(StbUndoRecord value) {
    CImGuiJNI.StbUndoState_undo_rec_set(swigCPtr, this, StbUndoRecord.getCPtr(value), value);
  }

  public StbUndoRecord getUndo_rec() {
    long cPtr = CImGuiJNI.StbUndoState_undo_rec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StbUndoRecord(cPtr, false);
  }

  public void setUndo_char(SWIGTYPE_p_unsigned_short value) {
    CImGuiJNI.StbUndoState_undo_char_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getUndo_char() {
    long cPtr = CImGuiJNI.StbUndoState_undo_char_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setUndo_point(short value) {
    CImGuiJNI.StbUndoState_undo_point_set(swigCPtr, this, value);
  }

  public short getUndo_point() {
    return CImGuiJNI.StbUndoState_undo_point_get(swigCPtr, this);
  }

  public void setRedo_point(short value) {
    CImGuiJNI.StbUndoState_redo_point_set(swigCPtr, this, value);
  }

  public short getRedo_point() {
    return CImGuiJNI.StbUndoState_redo_point_get(swigCPtr, this);
  }

  public void setUndo_char_point(int value) {
    CImGuiJNI.StbUndoState_undo_char_point_set(swigCPtr, this, value);
  }

  public int getUndo_char_point() {
    return CImGuiJNI.StbUndoState_undo_char_point_get(swigCPtr, this);
  }

  public void setRedo_char_point(int value) {
    CImGuiJNI.StbUndoState_redo_char_point_set(swigCPtr, this, value);
  }

  public int getRedo_char_point() {
    return CImGuiJNI.StbUndoState_redo_char_point_get(swigCPtr, this);
  }

  public StbUndoState() {
    this(CImGuiJNI.new_StbUndoState(), true);
  }

}
