name: Build

on: [push, pull_request]

jobs:
  build:
    name: 'Build and Test project'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: 'Install SWIG'
        run: |
          case $THE_OS in
              "windows-latest")
                  choco install swig
              ;;
              "ubuntu-latest")
                  sudo apt install -y swig
              ;;
              "macos-latest")
                  brew install swig
              ;;
              *) echo "Unknown OS!";;
          esac
        shell: bash
        env:
          THE_OS: ${{ matrix.os }}

      - name: 'Install OpenGL'
        run: |
          sudo apt-get update
          sudo apt install -y libglu1-mesa-dev
        if: matrix.os == 'ubuntu-latest'

      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: 'Clone Repo'
        uses: actions/checkout@v1

      - name: 'Compile and Link'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'assemble --stacktrace'
          wrapper-cache-enabled: false

      - name: 'Test'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'check --stacktrace'
          wrapper-cache-enabled: false

      - name: 'Publish to BinTray'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'smartPublish --stacktrace'
          wrapper-cache-enabled: false
        if: startsWith(github.ref, 'refs/tags/')
        env:
          BINTRAY_API_KEY: ${{ secrets.bintray_api_key }}
          BINTRAY_USER: ${{ secrets.bintray_user }}
